dapr/components-contrib

bindings/Readme.md

Change-Id: I9ed68882624f65203ec0bb472a8729951a662d87
Signed-off-by: Philippe Coval <p.coval@samsung.com>

docs: Fix RabbitMQ link

---

exporters/metadata.go
exporters/zipkin/zipkin_exporter_test.go
go.mod

Update metadata properties from map of interfaces to map of strings so it's consistent with other components

update metadata properties from map of interfaces to map of strings

---

bindings/blobstorage/blobstorage.go

Fix typo in comment in blobstorage.go
N/A
N/A

Fix typo in comment in blobstorage.go

---

Readme.md

To add build badge as mentioned in https://github.com/dapr/components-contrib/issues/58
https://github.com/dapr/components-contrib/issues/58

To add the build badge for github action

---

bindings/kafka/kafka.go
bindings/kafka/kafka_test.go

Added support for SASL auth in Kafka binding component
Issue #72 

Updated Kafka binding component to add SASL authentication

---

state/Readme.md

Add link to examples

---

state/Readme.md

Update Readme text with Zookeeper and latest interface name

Update Readme with Zookeeper

---

secretstores/vault/vault.go

Add the VaultRequest SSRF protection header.

secretstores: adding X-Vault-Request header

---

pubsub/azureservicebus/azureservicebus.go

Azure ServiceBus bug 107 fix

---

state/mongodb/mongodb.go

Implementing the Transactions interface for MongoDB.
That would make MongoDB be able to operate multi-operation transactions 
#87 
Please reference the issue this PR will close: #87

Adding transactions support to MongoDB

---

pubsub/azureservicebus/azureservicebus.go
pubsub/azureservicebus/azureservicebus_test.go

Fix azure service bus error message typo
I haven't created an issue since it is a simple typo fix. If needed, I can create one and associate it.

Fix azure service bus error message typo

---

servicediscovery/kubernetes/kubernetes.go
servicediscovery/kubernetes/kubernetes_test.go
servicediscovery/mdns/mdns.go
servicediscovery/servicediscovery.go

This adjusts the interface a bit.  It also fixes a lint error on the main repo side when including components contrib.

Adjust interface a bit, fix indirect lint error

---

bindings/requests.go
bindings/responses.go

Split the requests and responses for input/output bindings
Closes #135 

Split the requests and responses for input/output bindings

---

secretstores/Readme.md
secretstores/aws/secretmanager/secretmanager.go
secretstores/aws/secretmanager/secretmanager_integ_test.go
secretstores/aws/secretmanager/secretmanager_test.go

Addressed https://github.com/dapr/components-contrib/issues/112
Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/112

Support AWS secret manager as secret store

---

bindings/azure/storagequeues/storagequeues.go
bindings/azure/storagequeues/storagequeues_test.go
go.mod
go.sum

Added a binding for azure storage queues
Please reference the issue this PR will close: #143

Azure storage queue binding implementation

---

bindings/rabbitmq/rabbitmq.go

fix close channel by queue redecleration

---

bindings/azure/storagequeues/storagequeues.go
bindings/azure/storagequeues/storagequeues_test.go

Changed schema for azure/storagequeue to be consistent with azure/blobstorage
dapr/dapr#920

Changed schema to be consistent with blobstorage

---

pubsub/redis/redis.go
pubsub/redis/redis_test.go

fix redis streams waiting for handler

---

state/cassandra/cassandra.go
state/cassandra/cassandra_test.go

Updated Cassandra state store to allow users to pass in a custom port
Issue #123 

Added port option to cassandra state store

---

pubsub/azure/servicebus/servicebus.go

Changed the logic in the Azure ServiceBus pubsub to recover from network failure.
It appears the subscription needs to be closed before recalling `Receive(...)` as that will result in a segfault.
TODO: How to handle error during graceful error handling?
Please reference the issue this PR will close: #180 
__issue TLDR:__
When running with the Azure ServiceBus pubsub component, if your network disconnects, the component doesn't recover properly when the network reconnects.

Fixed retry logic for Azure ServiceBus pubsub

---

bindings/twilio/sms.go
bindings/twilio/sms_test.go

This adds an output binding for Twilio SMS.

Added Twilio binding

---

.github/workflows/components-contrib.yml
.golangci.yml
bindings/twilio/sms.go
state/cloudstate/cloudstate_crdt.go
state/sqlserver/sqlserver.go
state/sqlserver/sqlserver_integration_test.go

Upgrade go to 1.13.7 and linter to 1.23.2 and fix all linter errors
https://github.com/dapr/dapr/issues/997

Upgrade go to 1.13.7 and linter to 1.23.2

---

pubsub/azure/servicebus/servicebus.go

Close azure service bus sender connection

---

state/mongodb/mongodb.go
state/mongodb/mongodb_test.go

Add params for mongoDB

---

bindings/Readme.md

Updated bindings readme to point to how-to guide & individual specs
Break apart bindings into cloud groupings
Closes #211

Update bindings doc

---

state/sqlserver/sqlserver.go

Fix sql server get empty response

---

state/aerospike/aerospike.go

fix wrong pkg

---

state/aws/dynamodb/dynamodb.go
state/aws/dynamodb/dynamodb_test.go

Fix linter errors

---

secretstores/Readme.md

Adding Hashicorp Vault to the list of supported secret stores.
* [X ] Extended the documentation

Adding Hashicorp Vault to the list

---

bindings/Readme.md

Updates to the bindings portion to coincide with the updates to dapr docs

Updated binding docs to point to dapr docs

---

state/couchbase/couchbase.go

Couchbase state store: don't treat non-existent keys as errors
This PR will close: #261 

Couchbase state store: don't treat non-existent keys as errors

---

bindings/azure/eventhubs/eventhubs.go

Added `partitionID` and `partitionKey` fields in metadata.
If the partitionID is configured in metadata,  the eventhub is created with PartitionedSender options with the configured partitionID. `Write` method will send the event to the configured partition id.
If the partitionKey is configured in metadata, or from the request metadata, the partitionKey is set to the event object.
```
event := &eventhub.Event{
Data: req.Data,
}
...
event.PartitionKey = &partitionKey
...
err := a.hub.Send(context.Background(), event)
```
If the partitionID is configured in metadata, setting up the event receiver on the configured partition. I see the EPH implementation is done in existing binding. 
I created a new partitioned receiver implementation without using EPH. 
From what I've researched, there is no …

Updated EventHub bindings to read and write from same partition

---

state/hazelcast/hazelcast.go

Updated implementation to ensure that non-existent keys are not treated as errors
Issue #262 

Hazlecast state store: don't treat non-existent keys as errors

---

bindings/alicloud/oss/oss.go
bindings/alicloud/oss/oss_test.go
go.mod
go.sum

added new output bining component for integration with alicloud objectstorageservice 

Alicloudoss

---

bindings/azure/blobstorage/blobstorage.go

Add system and custom metadata support to Azure Blob Storage Binding.
Please reference the issue this PR will close: #280 

Add metadata support to Azure Blob binding

---

pubsub/Readme.md
pubsub/hazelcast/hazelcast.go
pubsub/hazelcast/metadata.go
pubsub/hazelcast/metadata_test.go

Hazelcast pubsub support
Issue https://github.com/dapr/components-contrib/issues/243

Add hazelcast pubsub support

---

Makefile

Increase linter timeout to 20m
N/A

Increase linter timeout to 20m

---

.github/workflows/components-contrib.yml

Turn off linter for windows because of inconsistent errors.
n/a

Turn off linter for windows

---

.github/workflows/components-contrib.yml

Fix linter check

---

.github/pull_request_template.md

Initiative to ensure docs are in line to current feature set.
@yaron2 as discussed, pls review

Update PR template to include doc issue ref

---

bindings/kafka/kafka.go

Add ability to specify Kafka partition keys on write calls.

Add partitionKey to kafka binding

---

bindings/twitter/twitter.go
bindings/twitter/twitter_test.go
go.mod
go.sum

Encapsulates Twitter search stream API in dapr binding

Added Twitter search input binding

---

pubsub/aws/snssqs/snssqs.go
pubsub/aws/snssqs/snssqs_test.go

Add a pubsub binding for AWS SNS/SQS

Add AWS SNS/SQS support 

---

pubsub/Readme.md
pubsub/mqtt/metadata.go
pubsub/mqtt/mqtt.go
pubsub/mqtt/mqtt_test.go

Implements pubsub interface for mqtt broker.
#326 

Add pubsub support for mqtt

---

secretstores/json/jsonsecretstore.go
secretstores/json/jsonsecretstore_test.go

Added JSON Secret Store as proposed in: #327
Please reference the issue this PR will close: #327

Added jsonsecretstore

---

servicediscovery/mdns/mdns.go

revert defer cancel back

---

state/mongodb/mongodb.go

Fix for `context deadline exceeded`  when attempting to persist state to a MongoDB instance, adding operationtimeout to get honored correctly.
#359 

Fix for context deadline exceeded issue - to use correct operation timeout

---

bindings/cron/cron.go
bindings/cron/cron_test.go
go.mod
go.sum

Addresses schedule binding #226 issue

Add scheduler binding #226

---

pubsub/envelope.go
pubsub/envelope_test.go

Assigns the serialized object into the CE data. Fixes #390

CloudEvent data serialized object

---

bindings/cron/cron.go
bindings/cron/cron_test.go

Fixes cron page name issue #394

renames the cron package

---

state/sqlserver/sqlserver.go

Save the db object during Init() so it can be used for operations - don't recreate it every time.
Also fixes an issue when using grpc - the data should not be marshalled if it's already []byte.
Please reference the issue this PR will close: #397, #398

Sql component should save db object on Init instead of creating a new

---

bindings/Readme.md

Update common operations list docs

---

.github/workflows/components-contrib.yml
bindings/twitter/twitter.go

Upgrade Go to 1.15

---

pubsub/envelope.go
pubsub/envelope_test.go
pubsub/requests.go

These are changes in the components-contrib repo corresponding to multi pubsub changes in dapr/dapr.
Please reference the issue this PR will close: #433

Corresponding changes for multi pubsub

---

go.mod
pubsub/natsstreaming/natsstreaming.go

update logger form nats-io's to dapr's
https://github.com/dapr/components-contrib/issues/448
Please reference the issue this PR will close: #448 
don't need to change the doc and test.

update logger form nats-io's to dapr's

---

state/azure/cosmosdb/cosmosdb.go

As in title.
Please reference the issue this PR will close: #446

Use metadata at top level instead of per request

---

pubsub/responses.go

Adding PubSub response type.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1340

Adding PubSub response type.

---

bindings/azure/blobstorage/blobstorage.go

Add get operation for azure blob storage binding

---

CODEOWNERS
OWNERS

Updating CODEOWNERS to align with new org teams

Update and rename OWNERS to CODEOWNERS

---

state/Readme.md

Updated state store list in `state/Readme.md`.  Sorted, added missing, and de-duplicated.
Please reference the issue this PR will close: #488

Fixed #488 - Update state store list in readme.

---

docs/developing-component.md

Update component-contrib update commands
n/a

Update component-contrib update commands

---

pubsub/azure/eventhubs/eventhubs.go

Adds missing Close method to Event Hubs pub/sub component.

Add close method to event hubs pub/sub

---

bindings/azure/blobstorage/blobstorage.go

Closes https://github.com/dapr/components-contrib/issues/515

Fix azure blob storage json payload

---

pubsub/rabbitmq/metadata.go
pubsub/rabbitmq/rabbitmq.go
pubsub/rabbitmq/rabbitmq_test.go

Auto-reconnect rabbitmq pubsub
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1688

Auto-reconnect rabbitmq pubsub

---

pubsub/envelope.go
pubsub/envelope_test.go

Respect content-type for PubSub data.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2080

Respect content-type for PubSub data.

---

state/aerospike/aerospike.go
state/aws/dynamodb/dynamodb.go
state/azure/blobstorage/blobstorage.go
state/azure/cosmosdb/cosmosdb.go
state/azure/tablestorage/tablestorage.go
state/cassandra/cassandra.go
state/cloudstate/cloudstate_crdt.go
state/couchbase/couchbase.go
state/gcp/firestore/firestore.go
state/hashicorp/consul/consul.go
state/hazelcast/hazelcast.go
state/memcached/memcached.go
state/mongodb/mongodb.go
state/postgresql/postgresdbaccess.go
state/postgresql/postgresql.go
state/redis/redis.go
state/responses.go
state/rethinkdb/rethinkdb.go
state/sqlserver/sqlserver.go
state/store.go
state/store_test.go
state/zookeeper/zk.go
state/zookeeper/zk_test.go

Add BulkGet method on state store.
This Pr is for Plan B:
- Adding BulkGet method on state store which will return (bool, response, error)
- Dapr will calls BulkGet method first
* if store supports BulkGet, it will return true with resposne list
* if store doesn't support BulkGet, it will return false with nil response; dapr need to fallback to call get method one by one
https://github.com/dapr/dapr/issues/2368

Add bulk get in state store  - Plan B

---

pubsub/requests.go

The subscribeRequest and PublishRequest both need Metadata.
https://github.com/dapr/dapr/issues/2495

The subscribeRequest and PublishRequest both need Metadata.

---

bindings/azure/blobstorage/blobstorage.go

Closes https://github.com/dapr/components-contrib/issues/548

Add access level to azure blob storage

---

state/couchbase/couchbase.go

Fix couchbase serialization

---

bindings/azure/servicebusqueues/servicebusqueues.go
bindings/azure/servicebusqueues/servicebusqueues_integration_test.go
bindings/azure/servicebusqueues/servicebusqueues_test.go
bindings/azure/storagequeues/storagequeues.go
bindings/azure/storagequeues/storagequeues_test.go
bindings/rabbitmq/rabbitmq.go
bindings/rabbitmq/rabbitmq_integration_test.go
bindings/rabbitmq/rabbitmq_test.go
metadata/utils.go
pubsub/Readme.md
pubsub/aws/snssqs/snssqs.go
pubsub/azure/eventhubs/eventhubs.go
pubsub/azure/servicebus/servicebus.go
pubsub/envelope.go
pubsub/envelope_test.go
pubsub/feature.go
pubsub/gcp/pubsub/pubsub.go
pubsub/hazelcast/hazelcast.go
pubsub/kafka/kafka.go
pubsub/mqtt/mqtt.go
pubsub/nats/nats.go
pubsub/natsstreaming/natsstreaming.go
pubsub/pubsub.go
pubsub/pulsar/pulsar.go
pubsub/rabbitmq/rabbitmq.go
pubsub/redis/redis.go

Added TTL in PubSub.
Please reference the issue this PR relates to: https://github.com/dapr/dapr/issues/2216

TTL in PubSub.

---

pubsub/envelope.go
pubsub/envelope_test.go

This PR adds a dedicated method to check if a payload is a Cloud Event.

Add method to check if payload is a cloudevent

---

pubsub/envelope.go
pubsub/envelope_test.go

This PR adds additional fields to the custom Cloud Event creation method, needed by `daprd`.

Extend custom cloud event

---

pubsub/envelope.go
pubsub/envelope_test.go

This PR fixes a regression in JSON serialization

fix data serialization in cloudevent

---

secretstores/Readme.md

Adds BulkGetSecrets method to the SecretStore interface

---

pubsub/concurrency.go
pubsub/concurrency_test.go
pubsub/rabbitmq/metadata.go
pubsub/rabbitmq/rabbitmq.go
pubsub/rabbitmq/rabbitmq_test.go

Closes https://github.com/dapr/components-contrib/issues/574

Add concurrency mode to rabbitMQ pub/sub

---

state/errors.go
state/errors_test.go

export etag error kind

---

contenttype/utils.go
pubsub/envelope.go
pubsub/envelope_test.go

Refactor and fix contenttype logic for pubsub.
Please reference the issue this PR will close: #506 

Refactor and fix contenttype logic for pubsub.

---

pubsub/gcp/pubsub/pubsub.go

Fix gcp pub/sub multiple subscriptions

---

docs/developing-component.md

Update sample links

---

.github/workflows/conformance.yml

Add a manual dispatched workflow to run the conformance tests.
Please reference the issue this PR will close: #601 

Workflow to run conformance tests

---

tests/conformance/secretstores/secretstores.go

Please reference the issue this PR will close: #407 

Fix bulk get secret conformance tests

---

.github/workflows/conformance.yml
go.mod
tests/config/state/cosmosdb/statestore.yaml
tests/config/state/tests.yml
tests/conformance/README.md
tests/conformance/common.go
tests/conformance/common_test.go

Add CosmosDB conformance tests.
Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/599

Add CosmosDB state store conformance tests

---

.github/workflows/conformance.yml
tests/config/bindings/azure/blobstorage/bindings.yml
tests/config/bindings/azure/storagequeues/bindings.yml
tests/config/bindings/output_tests.yml
tests/conformance/common.go
tests/conformance/common_test.go

Conformance tests for Azure Blob Storage & Storage Queue output bindings
Please reference the issue this PR will close: #593 #595 

Conformance tests for Azure Blob Storage & Storage Queue output bindings

---

.github/workflows/conformance.yml
tests/config/state/mongodb/statestore.yml
tests/config/state/tests.yml
tests/conformance/common.go

Conformance tests for MongoDB State Store.
Please reference the issue this PR will close: #618 

Conformance tests for MongoDB State Store

---

.github/workflows/conformance.yml

Run conformance tests every 30 min & fail workflow if no tests found
Please reference the issue this PR will close: #620 

Run conformance tests every 30 min & fail workflow if no tests found

---

.github/workflows/conformance.yml
tests/config/pubsub/azure/servicebus/pubsub.yml
tests/config/pubsub/tests.yml
tests/conformance/README.md
tests/conformance/common.go
tests/conformance/common_test.go
tests/conformance/output_bindings_test.go
tests/conformance/pubsub/pubsub.go
tests/conformance/pubsub_test.go
tests/conformance/secretstores_test.go
tests/conformance/state_test.go

Please reference the issue this PR will close: #596 

Azure service bus conf tests

---

.github/workflows/conformance.yml

The conformance workflow is failing the workflow even though the tests pass as seen here: 
https://github.com/dapr/components-contrib/runs/1746420737?check_suite_focus=true#step:10:112
With the change in file ... reproduced local run: 
```
go test -v -tags=conftests -count=1 ./tests/conformance/... -run="${TEST_NAME}/${COMPONENT_NAME}"
=== RUN   TestPubsubConformance
=== RUN   TestPubsubConformance/azure.servicebus
common.go:220: error running conformance test for azure.servicebus: required env var is not set AzureServiceBusConnectionString
--- FAIL: TestPubsubConformance (0.00s)
--- FAIL: TestPubsubConformance/azure.servicebus (0.00s)
FAIL
FAIL    github.com/dapr/components-contrib/tests/conformance    0.224s
?       github.com/dapr/components-contrib/tests/conformance/bindings/output …
```

Fix conformance workflow file

---

secretstores/hashicorp/vault/vault.go

Fix get bulk secret for hashicorp vault.
Please reference the issue this PR will close: None

Fix get bulk secret for hashicorp vault.

---

tests/conformance/README.md
tests/conformance/bindings/bindings.go
tests/conformance/bindings_test.go
tests/conformance/common_test.go
tests/conformance/pubsub/pubsub.go
tests/conformance/pubsub_test.go
tests/conformance/secretstores/secretstores.go
tests/conformance/secretstores_test.go
tests/conformance/state/state.go
tests/conformance/state_test.go
tests/conformance/utils/utils.go
tests/conformance/utils/utils_test.go

add license header to conf test files. 

add license header to conf test files

---

.github/workflows/conformance.yml

Fix conf test workflow file to use bindings instead of output-bindings.

Fix conformance test workflow

---

.github/workflows/conformance.yml
tests/config/bindings/azure/servicebusqueues/bindings.yml
tests/config/bindings/tests.yml
tests/conformance/common.go

Add Azure Service Bus Queues binding to tests
Closes: #619 

Add Azure Service Bus Queues binding to tests

---

.github/workflows/conformance.yml
tests/config/bindings/azure/eventgrid/bindings.yml
tests/config/bindings/tests.yml
tests/conformance/bindings/bindings.go
tests/conformance/common.go

Adds conf test for Azure Event Grid.
Please reference the issue this PR will close: #594 
Works locally:
```bash
$ go test -v -tags=conftests -count=1 ./tests/conformance -run=TestBindingsConformance/azure.eventgrid
=== RUN   TestBindingsConformance
=== RUN   TestBindingsConformance/azure.eventgrid
=== RUN   TestBindingsConformance/azure.eventgrid/init
=== RUN   TestBindingsConformance/azure.eventgrid/operations
=== RUN   TestBindingsConformance/azure.eventgrid/read
=== RUN   TestBindingsConformance/azure.eventgrid/create
=== RUN   TestBindingsConformance/azure.eventgrid/verify_read
--- PASS: TestBindingsConformance (24.82s)
--- PASS: …
```

Adds conf test for Azure Event Grid.

---

.github/workflows/conformance.yml

Run ngrok only for azure eventgrid.
Please reference the issue this PR will close: #594

Run ngrok only for azure eventgrid.

---

bindings/azure/eventgrid/eventgrid.go
tests/conformance/common.go

Add verbosity to conf tests. More debug logging in eventgrid binding.

Add verbosity to conf tests. More debug logging in eventgrid binding.

---

bindings/azure/eventgrid/eventgrid.go
tests/config/bindings/tests.yml

Increase timeout for conf test + more logging for EventGrid.

Increase timeout for conf test + more logging for EventGrid.

---

.github/workflows/conformance.yml
tests/config/secretstores/azure/keyvault/azure-keyvault.yaml
tests/config/secretstores/tests.yml
tests/conformance/common.go

Add conformance tests for Azure Keyvault Secret Store.
Please reference the issue this PR will close: #604 

Add conformance tests for Azure Keyvault Secret Store

---

bindings/kafka/kafka.go
bindings/kafka/kafka_test.go
pubsub/kafka/kafka.go
pubsub/kafka/kafka_test.go

Add kafka max message bytes and pubsub partition key

---

.github/workflows/conformance.yml

Run conformance tests not requiring secrets automatically for pull requests.

Run conformance tests for PRs, whenever that is possible

---

contenttype/utils.go
pubsub/envelope.go
pubsub/envelope_test.go

Handles binary data in cloud event.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2612

Handles binary data in cloud event.

---

secretstores/azure/keyvault/keyvault.go

`BulkGetSecret` checks if secrets returned by the `GetSecrets` API are enabled before fetching the values.
Please reference the issue this PR will close: #656

Checking that returned secrets are enabled #656

---

.github/workflows/conformance.yml

Display ngrok log for conf tests.
Please reference the issue this PR will close: #N/A

Display ngrok log for conf tests.

---

.github/workflows/conformance.yml
tests/config/bindings/tests.yml

Stop ngrok when done running conf tests.
Increase eventgrid test timeout.
Please reference the issue this PR will close:  N/A

Stop ngrok when done running conf tests.

---

.github/workflows/conformance.yml
state/azure/cosmosdb/cosmosdb.go
state/azure/cosmosdb/cosmosdb_test.go
state/mongodb/mongodb.go
tests/config/state/mongodb/statestore.yml
tests/config/state/tests.yml
tests/conformance/state/state.go

Validation in this run:
https://github.com/dapr/components-contrib/runs/1868788838?check_suite_focus=true
Please reference the issue this PR will close: #407 
Will also close: #684 
Will also close: #685

Conf state trx + Change mongodb get result for key not found  + Fix byte[] in cosmosdb

---

.github/workflows/conformance.yml
Makefile
tests/config/kind-data.yaml
tests/config/secretstores/kubernetes/kubernetes-secrets.yaml
tests/config/secretstores/tests.yml
tests/conformance/common.go
tests/conformance/secretstores/secretstores.go

Run conformance tests for K8s secret store.
Please reference the issue this PR will close: #597 

Run conformance tests for Kuberentes secret store

---

.github/workflows/conformance.yml
go.mod
go.sum
pubsub/kafka/kafka.go
tests/config/pubsub/kafka/pubsub.yml
tests/config/pubsub/tests.yml
tests/conformance/common.go
tests/conformance/pubsub/pubsub.go

Fix pubsub retry in Kafka.
Add kafka to conf test.
Please reference the issue this PR will close: #687

Fix pubsub retry for Kafka

---

.github/infrastructure/docker-compose-natsstreaming.yml
.github/workflows/conformance.yml
tests/config/pubsub/natsstreaming/pubsub.yml
tests/config/pubsub/tests.yml
tests/conformance/common.go

Adds conf test for natsstreaming.
Please reference the issue this PR will close: #689 

Adds conf test for natsstreaming.

---

tests/config/bindings/tests.yml
tests/config/pubsub/tests.yml
tests/config/secretstores/tests.yml
tests/config/state/tests.yml
tests/conformance/README.md

Update conf test readme
Added the supported operations comments in each test.yml
Please reference the issue this PR will close: #411 
* [] Created/updated tests

Update conf test readme

---

.github/workflows/conformance.yml
go.mod
go.sum
pubsub/kafka/kafka.go
tests/config/pubsub/kafka/pubsub.yml
tests/config/pubsub/tests.yml
tests/conformance/common.go
tests/conformance/pubsub/pubsub.go

Merge release 1.0.0 into master
Please reference the issue this PR will close: endgame

Merge release 1.0.0 into master

---

docs/developing-component.md

Added a small amount if text at the top of the page to call out that Go is the programming language for creating custom components.
Might address #297

Mention Go as the language we use to create components

---

state/mongodb/mongodb.go

Adds etag support to MongoDB.
Please reference the issue this PR will close: #726 
Validated using the new E2E test for actors using etag for reminders:
```txt
$ DAPR_E2E_TEST=actor_reminder make test-e2e-all
DAPR_CONTAINER_LOG_PATH=./dist/container_logs GOOS=darwin DAPR_TEST_NAMESPACE=dapr-tests DAPR_TEST_TAG=dev-linux-amd64 DAPR_TEST_REGISTRY=docker.io/artursouza DAPR_TEST_MINIKUBE_IP=192.168.64.41 go test -p 2 -count=1 -v -tags=e2e ./tests/e2e/actor_reminder/...
2021/02/26 18:05:53 Running setup...
2021/02/26 18:05:53 Installing test apps...
2021/02/26 18:05:53 …
```

Adds etag support to MongoDB.

---

state/mongodb/mongodb.go

* Adds etag support to MongoDB.
* Addressing PR comments.
* Remove empty etag check.
Adds etag support to MongoDB. (#729)
Please reference the issue this PR will close: #726

Adds etag support to MongoDB. (#729)

---

tests/config/bindings/tests.yml

fix duration for event grid conf test

---

state/aerospike/aerospike.go
state/aws/dynamodb/dynamodb.go
state/azure/blobstorage/blobstorage.go
state/azure/cosmosdb/cosmosdb.go
state/azure/tablestorage/tablestorage.go
state/cassandra/cassandra.go
state/cloudstate/cloudstate_crdt.go
state/couchbase/couchbase.go
state/feature.go
state/gcp/firestore/firestore.go
state/hashicorp/consul/consul.go
state/hazelcast/hazelcast.go
state/memcached/memcached.go
state/mongodb/mongodb.go
state/mysql/mysql.go
state/postgresql/postgresql.go
state/redis/redis.go
state/rethinkdb/rethinkdb.go
state/sqlserver/sqlserver.go
state/store.go
state/store_test.go
state/zookeeper/zk.go
tests/conformance/state/state.go

Add Feature list for state store.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2890

Add Feature list for state store.

---

secretstores/aws/parameterstore/parameterstore.go
secretstores/aws/parameterstore/parameterstore_integ_test.go
secretstores/aws/parameterstore/parameterstore_test.go

Add a new secret store implementation - AWS SSM Parameter Store. 
Please reference the issue this PR will close: #746

AWS SSM Parameter Store

---

bindings/Readme.md
bindings/aws/kinesis/kinesis.go
bindings/aws/sqs/sqs.go
bindings/azure/eventgrid/eventgrid.go
bindings/azure/eventhubs/eventhubs.go
bindings/azure/servicebusqueues/servicebusqueues.go
bindings/azure/storagequeues/storagequeues.go
bindings/azure/storagequeues/storagequeues_test.go
bindings/cron/cron.go
bindings/cron/cron_test.go
bindings/gcp/pubsub/pubsub.go
bindings/input_binding.go
bindings/kafka/kafka.go
bindings/kubernetes/kubernetes.go
bindings/mqtt/mqtt.go
bindings/rabbitmq/rabbitmq.go
bindings/responses.go
bindings/rethinkdb/statechange/statechange.go
bindings/rethinkdb/statechange/statechange_test.go
bindings/twitter/twitter.go
bindings/twitter/twitter_test.go
tests/conformance/bindings/bindings.go

This PR adds the ability for an app to response with a payload in response to an input binding event.
Part of https://github.com/dapr/dapr/issues/2628

Add app response to input binding event

---

.github/scripts/automerge.py
.github/workflows/dapr-automerge.yml

Allows automerge of approved PRs.

Automerge in contrib.

---

state/aerospike/aerospike.go
state/aws/dynamodb/dynamodb.go
state/azure/blobstorage/blobstorage.go
state/azure/cosmosdb/cosmosdb.go
state/azure/tablestorage/tablestorage.go
state/cassandra/cassandra.go
state/cloudstate/cloudstate_crdt.go
state/couchbase/couchbase.go
state/gcp/firestore/firestore.go
state/hashicorp/consul/consul.go
state/hazelcast/hazelcast.go
state/memcached/memcached.go
state/mongodb/mongodb.go
state/mysql/mysql.go
state/postgresql/postgresql.go
state/redis/redis.go
state/redis/redis_test.go
state/rethinkdb/rethinkdb.go
state/sqlserver/sqlserver.go
state/store.go
state/store_test.go
state/zookeeper/zk.go
tests/conformance/state/state.go

I have added `Ping` to the `Store` interface for health check endpoint.
dapr/dapr#2167

add Ping operation to`store` interface.

---

state/cloudstate/proto/crdt.pb.go
state/cloudstate/proto/crdt.proto

Signed-off-by: Long Dai <long0dai@foxmail.com>
Fix a typo.

fix a typo

---

nameresolution/consul/Readme.md

Fixing bad yaml in nr consul readme configuration samples
dapr/docs#1531

Name resolution Consul - fixed malformed yaml in Readme

---

bindings/mqtt/mqtt.go

Signed-off-by: Long Dai <long0dai@foxmail.com>
Please reference the issue this PR will close: #900

mqtt: implement Close

---

bindings/alicloud/dingtalk/webhook/webhook.go
bindings/alicloud/rocketmq/rocketmq_test.go
bindings/localstorage/localstorage.go
middleware/http/oauth2/oauth2_middleware.go
middleware/http/oauth2clientcredentials/mocks/mock_TokenProviderInterface.go
nameresolution/consul/consul_test.go
secretstores/azure/keyvault/authutils_test.go
state/sqlserver/sqlserver_integration_test.go
state/sqlserver/sqlserver_test.go
state/zookeeper/zk_mock.go

`gofumpt` was enabled in #887. The linter check is now failing in some other PRs and the errors are in files the author didn't change. This PR fixes the few formatting issues reported by the `gofumpt`.
/cc @artursouza

Resolving gofumpt issues

---

internal/retry/retry_test.go

Use a channel to signal that the retry go routine has started and hopefully remove the race condition that makes this a flaky test.

Fix flaky retry test w/ cancel

---

state/mongodb/mongodb.go
state/mongodb/mongodb_test.go

Added more unit tests for MongoDB state store component
Please reference the issue this PR will close: #904

Add more tests for MongoDB state store component

---

state/memcached/memcached.go
state/memcached/memcached_test.go

Adds support for TTL in Memcached State Store
This fixes up PR https://github.com/dapr/components-contrib/pull/992
Thanks to @UmutComlekci for the original PR (commits included here) which I am fixing up in time for the release code freeze today.
Please reference the issue this PR will close: #306 

Adds support for TTL in Memcached State Store (PR Fixup)

---

go.mod
go.sum

Signed-off-by: Long <long0dai@foxmail.com>
Fix https://github.com/dapr/components-contrib/issues/1033

fix build error on Arm 32-bit

---

.github/workflows/dapr-bot.yml

Supports bot assignment via /assign.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/3245

Supports bot assignment via /assign.

---

bindings/smtp/smtp.go

When you try to send an email to several recepients with emailTo field you get the error: binding smtp: error from smtp binding, sending email failed: gomail: could not send email 1: gomail: invalid address "email.one@dapr.io; email.two@dapr.io": mail: expected single address, got "; email.two@dapr.io"}
If you use EmailCC and EmailBCC you don't get any error due dapr isn't using the correct headers for CC and BCC recipients (https://github.com/go-gomail/gomail/blob/81ebce5c23dfd25c6c67194b37d3dd3f338c98b1/send.go#L78) - You must use Cc and Bcc instead of CC and BCC
- Created a method to parse email addresses and set correctly to, cc and bcc values
- Updated Cc and Bcc fields
_curl -X POST -H 'Content-Type: application/json' http://localhost:3500/v1.0/bindings/smtp -d '{ "data": "Hi!", …

biinding smtp: fix multiple recipients

---

go.mod
go.sum

Signed-off-by: Long <long0dai@foxmail.com>
Upgrade to the release version, ref https://github.com/dapr/components-contrib/pull/1045

upgrade sentinel-golang to release version

---

bindings/rabbitmq/rabbitmq.go
bindings/requests.go
metadata/utils.go
metadata/utils_test.go

Signed-off-by: Long <long0dai@foxmail.com>
Support rabbitmq binding send any content types.
Please reference the issue this PR will close: #1144

bindings: support rabbitmq send any content types

---

.github/workflows/dapr-bot.yml

Fix syntax errors introduced in dapr-bot.yml after #1091
Example workflow failures:
https://github.com/dapr/components-contrib/actions/runs/1304509381 
https://github.com/dapr/components-contrib/actions/runs/1304451259 

Fix syntax errors in dapr-bot.yml

---

.github/workflows/certification.yml
.github/workflows/dapr-bot.yml

Add github workflow for building and running certification tests on PR and in schedule
N/A. Dev-ops improvement to ensure that no build breaks are introduced as new certification tests are being merged into master. 

Add certification test workflow

---

bindings/smtp/smtp.go

This fixes a problem with the body of e-mail messages sent by the
SMTP binding.
When the SMTP binding was invoked over GRPC it would not translate the
data of the request to the right format in the e-mail. Instead it would
send an empty body. When the SMTP binding was invoked over HTTP it would
correctly unquote the data of the request.
Now when you call the SMTP binding, it will try to unquote the body content to handle the data coming in over HTTP. When the data can't be unquoted, we use the incoming data as-is as it comes over GRPC and is already in a usable format.
Fixes https://github.com/dapr/components-contrib/issues/1253

Fix body content parsing for SMTP binding

---

.github/workflows/certification.yml

Added PR job for pubsub.rabbitmq certification test

add PR job for pubsub.rabbitmq certification test

---

state/azure/cosmosdb/cosmosdb_query_test.go
state/mongodb/mongodb_query_test.go
state/query/query_test.go

update package name

---

state/Readme.md
state/store.go

Added README for State Query API

add README for State Query API

---

pubsub/rabbitmq/rabbitmq.go
tests/certification/embedded/embedded.go
tests/certification/flow/flow.go
tests/certification/flow/sidecar/sidecar.go
tests/certification/go.sum
tests/certification/pubsub/rabbitmq/go.mod
tests/certification/pubsub/rabbitmq/rabbitmq_test.go

Also these tweaks to certification test:
* Added `amqpReady` function to wait for RabbitMQ readiness.
* Tweaks to when subscribed is signaled in the test.
Builds upon #954

RabbitMQ certification: Fixing publish/subscribe race condition.

---

bindings/azure/cosmosdbgremlinapi/cosmosdbgremlinapi.go
bindings/azure/cosmosdbgremlinapi/cosmosdbgremlinapi_test.go

rename CosmosGraphDB binding component to CosmosDBGremlinAPI #1246

---

tests/certification/go.mod
tests/certification/go.sum
tests/certification/pubsub/kafka/go.mod
tests/certification/pubsub/kafka/go.sum
tests/certification/pubsub/rabbitmq/go.mod
tests/certification/pubsub/rabbitmq/go.sum
tests/certification/secretstores/azure/keyvault/go.mod
tests/certification/secretstores/azure/keyvault/go.sum
tests/certification/state/sqlserver/go.mod
tests/certification/state/sqlserver/go.sum

Updating certification go.mod files to the latest dapr/dapr commit in master

Certification go.mod updates to latest dapr/dapr

---

tests/certification/secretstores/azure/keyvault/go.sum

Fixes certification test failure for AKV

go mod tidy for KV certification test

---

pubsub/kafka/kafka.go
pubsub/kafka/kafka_test.go
tests/certification/secretstores/azure/keyvault/go.sum

Merge #1275 release branch.
Also includes #1286 for KV certification test failure

Merge #1275 Kafka Broker Version into Release 1.5

---

.devcontainer/Dockerfile

Update to use latest Dev Container (introduced in https://github.com/dapr/dapr/pull/3887)

Update to use latest Dev Container

---

pubsub/rabbitmq/rabbitmq.go
pubsub/rabbitmq/rabbitmq_test.go
tests/certification/pubsub/rabbitmq/components/alpha/rabbitmq-alpha.yml
tests/certification/pubsub/rabbitmq/components/beta/rabbitmq-beta.yml
tests/certification/pubsub/rabbitmq/go.mod
tests/certification/pubsub/rabbitmq/go.sum
tests/certification/pubsub/rabbitmq/rabbitmq_test.go

add troubleshooting info and fix race conditions in rabbitmq pubsub component

add troubleshooting info and fix race conditions

---

middleware/http/ratelimit/ratelimit_middleware.go

when i read ratelimit_middleware.go ,i found some comments are not right ,so i update some ratelimit_middleware.go comments

update some ratelimit_middleware.go comments

---

state/query/query.go
tests/conformance/state/state.go
tests/state/query/q1.json
tests/state/query/q2.json
tests/state/query/q4.json

fixed typo in Query JSON
Please reference the issue this PR will close: #1343

fixed typo in Query JSON

---

pubsub/rabbitmq/rabbitmq.go
pubsub/rabbitmq/rabbitmq_test.go
tests/certification/pubsub/rabbitmq/components/alpha/rabbitmq-alpha.yml
tests/certification/pubsub/rabbitmq/components/beta/rabbitmq-beta.yml
tests/certification/pubsub/rabbitmq/go.mod
tests/certification/pubsub/rabbitmq/go.sum
tests/certification/pubsub/rabbitmq/rabbitmq_test.go

Cherry-pick into release 1.5 PR #1278

Cherry-pick into release 1.5 PR #1278

---

bindings/azure/cosmosdb/cosmosdb.go
go.mod
go.sum
state/azure/cosmosdb/cosmosdb.go
tests/config/bindings/azure/cosmosdb/bindings.yml
tests/config/bindings/tests.yml
tests/conformance/common.go
tests/conformance/common_test.go

As per the 1.4.4 checklist, these changes have been cherry-picked from master into the `release-1.4` branch. From here, they can be tagged into an RC/release.
https://github.com/dapr/dapr/issues/3938

Cherry-pick required changes for 1.4.4

---

.github/infrastructure/conformance/azure/conf-test-azure.bicep
.github/infrastructure/conformance/azure/setup-azure-conf-test.sh

Fixes a small bug in the test infrastructure setup script

Fix test infrastructure setup script

---

pubsub/rabbitmq/rabbitmq.go

Fixed subscription error 
Please reference the issue this PR will close: #1372

pub/sub rabbitmq: fix subscribe error

---

pubsub/gcp/pubsub/pubsub.go
tests/certification/pubsub/kafka/go.sum
tests/certification/pubsub/rabbitmq/go.sum

fix nits: duplicated err handle

---

tests/certification/bindings/azure/cosmosdb/go.sum
tests/certification/bindings/azure/servicebusqueues/go.sum
tests/certification/go.sum
tests/certification/pubsub/kafka/go.sum
tests/certification/pubsub/rabbitmq/go.sum
tests/certification/secretstores/azure/keyvault/go.sum
tests/certification/state/sqlserver/go.sum
tests/config/bindings/tests.yml

Sends the correct request data for the List operation in the Azure Blobstorage Bindings Conformance test. While this also changes the request data for the other operations, this does not actually matter as we don't care about the specific content written to blob storage.
Fixes #1407 

Fix Blobstorage Bindings Conformance Test

---

.github/workflows/components-contrib.yml
Makefile

Automation: Ensures that all go.mods are tidied before PR merge

Automation: Ensures that all go.mods are tidied before PR merge

---

pubsub/aws/snssqs/snssqs.go

Signed-off-by: Amit Mor <amit.mor@hotmail.com>
bugfixes
1. reset visibility timeout to zero so other consumer can immediately consume retried but failed messages
2. not setting/rewritting SQS attributes when DLQ is set and also disableEntityManagement 
Please reference the issue this PR will close: #1445 

bugfixes: visibility timeout, dlq queue attributes

---

tests/certification/bindings/azure/blobstorage/go.mod
tests/certification/bindings/azure/blobstorage/go.sum
tests/certification/bindings/azure/cosmosdb/go.mod
tests/certification/bindings/azure/cosmosdb/go.sum
tests/certification/bindings/azure/servicebusqueues/go.mod
tests/certification/bindings/azure/servicebusqueues/go.sum
tests/certification/go.mod
tests/certification/go.sum
tests/certification/pubsub/kafka/go.mod
tests/certification/pubsub/kafka/go.sum
tests/certification/pubsub/mqtt/go.mod
tests/certification/pubsub/mqtt/go.sum
tests/certification/pubsub/rabbitmq/go.mod
tests/certification/pubsub/rabbitmq/go.sum
tests/certification/secretstores/azure/keyvault/go.mod
tests/certification/secretstores/azure/keyvault/go.sum
tests/certification/state/sqlserver/go.mod
tests/certification/state/sqlserver/go.sum

pin certification tests to Daprd v1.6.0-rc.3
```
cd tests/certification
go get github.com/dapr/dapr@v1.6.0-rc.3
cd ../../
make modtidy-all
```

pin certification tests to Daprd v1.6.0-rc.3

---

configuration/redis/redis.go
configuration/requests.go
configuration/store.go

Signed-off-by: LaurenceLiZhixin <382673304@qq.com>
Add Configuration unsubscribe API

Fix: add configuration unsubscribe api

---

.devcontainer/Dockerfile

Update devcontainer to dapr-dev:0.1.6

Update devcontainer to dapr-dev:0.1.6

---

state/postgresql/postgresql_query.go
state/postgresql/postgresql_query_test.go
tests/conformance/state/state.go

update conformance tests
Please reference the issue this PR will close: #1490

update conformance tests

---

go.mod
go.sum
tests/certification/bindings/azure/blobstorage/go.sum
tests/certification/bindings/azure/cosmosdb/go.sum
tests/certification/bindings/azure/servicebusqueues/go.sum
tests/certification/go.sum
tests/certification/pubsub/kafka/go.mod
tests/certification/pubsub/kafka/go.sum
tests/certification/pubsub/mqtt/go.sum
tests/certification/pubsub/rabbitmq/go.sum
tests/certification/secretstores/azure/keyvault/go.sum
tests/certification/state/sqlserver/go.sum

Upgrade pulsar client to 0.8.0, it solves https://github.com/apache/pulsar-client-go/releases/tag/v0.8.0

Upgrade pulsar client to 0.8.0

---

.github/infrastructure/docker-compose-redisjson.yml
.github/workflows/conformance.yml
metadata/utils.go
state/redis/metadata.go
state/redis/redis.go
state/redis/redis_query.go
state/redis/redis_query_schema.go
state/redis/redis_query_schema_test.go
tests/config/state/redis/statestore.yaml
tests/config/state/tests.yml
tests/conformance/state/state.go

implement state query API for Redis statestore
Please reference the issue this PR will close: #1211

redis statestore: implement state query API

---

bindings/aws/s3/s3.go
bindings/aws/s3/s3_test.go

Closes https://github.com/dapr/components-contrib/issues/1554.

Add disablessl option to s3 config

---

state/redis/redis_query.go
state/redis/redis_query_test.go
tests/state/query/q6.json

fixed a bug in querying numeric values
Please reference the issue this PR will close: #1594

redis: fix querying numeric values

---

state/mongodb/mongodb.go

Fix mongodb conf

---

state/mongodb/mongodb.go
state/mongodb/mongodb_query.go
tests/conformance/state/state.go

1.5 Hotfix for MongoDB serialization issues
Addresses #1355

1.5 Hotfix for MongoDB serialization issues

---

state/mongodb/mongodb.go
state/mongodb/mongodb_query.go
tests/conformance/state/state.go

1.6 Hotfix for MongoDB serialization issues
Addresses #1355

1.6 Hotfix for MongoDB serialization issues

---

secretstores/secret_store.go

Signed-off-by: ZhangJian He <shoothzj@gmail.com>
Fix the typo of annotation in `secret_store.go`

fix annotation typo

---

tests/config/pubsub/tests.yml

Signed-off-by: GitHub <noreply@github.com>
Unfortunately this is a hard coded value that needs to be updated for the conformance test.

Update EventHubs conformance test topic

---

go.mod
go.sum
tests/certification/bindings/azure/cosmosdb/go.mod
tests/certification/bindings/azure/cosmosdb/go.sum

Fixes an issue with DBs or collections with uppercase characters not working, as reported by users testing 1.7 RC
(Re-do of #1629 against `release-1.7` branch)

Bumped version of a8m/documentdb

---

go.mod
go.sum
state/azure/cosmosdb/cosmosdb.go
tests/certification/bindings/azure/cosmosdb/go.mod
tests/certification/bindings/azure/cosmosdb/go.sum

This is fixed by upgrading the upstream SDK
Also added a missing handling of throttling in the Delete method

Yet another Cosmos DB auth fix

---

.github/workflows/dapr-bot.yml

Small fix for dapr-bot

---

tests/certification/bindings/azure/blobstorage/go.mod
tests/certification/bindings/azure/blobstorage/go.sum
tests/certification/bindings/azure/cosmosdb/go.mod
tests/certification/bindings/azure/cosmosdb/go.sum
tests/certification/bindings/azure/servicebusqueues/go.mod
tests/certification/bindings/azure/servicebusqueues/go.sum
tests/certification/go.mod
tests/certification/go.sum
tests/certification/pubsub/kafka/go.mod
tests/certification/pubsub/kafka/go.sum
tests/certification/pubsub/mqtt/go.mod
tests/certification/pubsub/mqtt/go.sum
tests/certification/pubsub/rabbitmq/go.mod
tests/certification/pubsub/rabbitmq/go.sum
tests/certification/secretstores/azure/keyvault/go.mod
tests/certification/secretstores/azure/keyvault/go.sum
tests/certification/state/sqlserver/go.mod
tests/certification/state/sqlserver/go.sum
tests/certification/state/sqlserver/sqlserver_test.go

Merge release 1.7 into master

---

.devcontainer/devcontainer.json

Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>
changes to devcontainer.json file.
Refer PR - 
https://github.com/dapr/dapr/commit/47dbc4893803b8556012b0b318fe15afdfed1256
https://github.com/dapr/dapr/commit/55ae94e39c7c515dde00ebb38ac893dfbaebd7da
Please reference the issue this PR will close: Endgame

Update dev container file to support latest changes

---

go.sum
pubsub/aws/snssqs/metadata.go
pubsub/aws/snssqs/snssqs.go
pubsub/aws/snssqs/snssqs_test.go
tests/config/pubsub/aws/snssqs/pubsub.yml

based on metadata property: `concurrencyMode` call subscriber' handler either concurrently or one message at a time (sequentially, as it is before this PR)
Please reference the issue this PR will close: #1650 

Concurrent downstream

---

pubsub/pulsar/pulsar.go

Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/1659

Fixing pubsub-pulsar not use format topic problem

---

pubsub/pulsar/pulsar.go

Signed-off-by: saberwang <saberwang@hotmail.com>
Cherry pick #1660

Cherry-pick of #1660 Fixing pubsub-pulsar not use format topic problem

---

bindings/rabbitmq/rabbitmq.go
bindings/zeebe/command/activate_jobs.go
bindings/zeebe/command/activate_jobs_test.go
bindings/zeebe/command/cancel_instance.go
bindings/zeebe/command/cancel_instance_test.go
bindings/zeebe/command/command.go
bindings/zeebe/command/command_test.go
bindings/zeebe/command/complete_job.go
bindings/zeebe/command/complete_job_test.go
bindings/zeebe/command/create_instance.go
bindings/zeebe/command/create_instance_test.go
bindings/zeebe/command/deploy_process.go
bindings/zeebe/command/deploy_process_test.go
bindings/zeebe/command/fail_job.go
bindings/zeebe/command/fail_job_test.go
bindings/zeebe/command/publish_message.go
bindings/zeebe/command/publish_message_test.go
bindings/zeebe/command/resolve_incident.go
bindings/zeebe/command/resolve_incident_test.go
bindings/zeebe/command/set_variables.go
bindings/zeebe/command/set_variables_test.go
bindings/zeebe/command/throw_error_test.go
bindings/zeebe/command/topology.go
bindings/zeebe/command/update_job_retries.go
bindings/zeebe/command/update_job_retries_test.go
bindings/zeebe/jobworker/jobworker.go
tests/e2e/bindings/zeebe/helper.go

Signed-off-by: Wang Bing <wangbing.adam@gmail.com>
amendment of https://github.com/dapr/components-contrib/pull/1681
missed rabbitmq and zeebee

Add context in bindings

---

bindings/Readme.md

Signed-off-by: pigletfly <wangbing.adam@gmail.com>
update readme of bindings after https://github.com/dapr/components-contrib/pull/1681 merged

Update readme of bindings

---

pubsub/mqtt/mqtt.go

This helps avoiding issues when multiple subscribers are added in a short period of time
Closes #1709

Better handling of concurrency in MQTT Subscribe method

---

internal/component/kafka/consumer.go
tests/certification/bindings/kafka/kafka_test.go
tests/certification/pubsub/kafka/kafka_test.go

improve log of kafkaf components cert test
https://github.com/dapr/components-contrib/issues/1799

improve log of kafka components cert test

---

.github/workflows/certification.yml

Tiny workflow change to correctly show workflow step failing

Do not continue workflow on error

---

lock/redis/standalone.go

Signed-off-by: seeflood <349895584@qq.com>
Distributed Lock Redis tests do not run.
fix #1811 
Please reference the issue this PR will close: #1811 

fix: redis lock ut

---

bindings/alicloud/dubbo/context.go
bindings/alicloud/dubbo/dubbo_output.go

Ensure context is propagated in Dubbo input binding

---

bindings/aws/dynamodb/dynamodb.go

Ensure context propagation in PutItem and other minor changes

Improvements to DynamoDB binding

---

bindings/alicloud/dingtalk/webhook/webhook.go
bindings/alicloud/dingtalk/webhook/webhook_test.go

Improvements to bindings.dingtalk.webhook

---

bindings/aws/s3/s3.go
bindings/aws/s3/s3_test.go
internal/utils/utils.go

Ensure context propagation in output bindings + other fixes

Improvements to S3 binding

---

bindings/azure/signalr/signalr.go
bindings/azure/signalr/signalr_test.go

Ensure context propagation in signalr Invoke

---

bindings/graphql/graphql.go
bindings/http/http.go

Ensure context propagation in output bindings + other fixes

Improvements to HTTP and graphQL bindings

---

bindings/aws/sns/sns.go

Ensure context propagation in SNS binding

---

Readme.md
bindings/Readme.md
configuration/Readme.md
docs/developing-component.md
middleware/Readme.md
nameresolution/Readme.md
pubsub/Readme.md
secretstores/Readme.md
state/Readme.md

Updated our docs for contributing to Dapr and other MD files in the repo which contained outdated info.

Updated development docs

---

.github/workflows/conformance.yml
state/azure/blobstorage/blobstorage.go
tests/config/bindings/azure/blobstorage/bindings.yml
tests/config/state/azure/blobstorage/statestore.yaml
tests/config/state/tests.yml
tests/conformance/common.go
tests/conformance/state/state.go

Accidentally discovered that there were no conformance tests for the state.azure.blobstorage component. Once I added the tests (included in this PR), the component was failing, primarily with issues related to managing etags.
Because this component is a stable one, this PR targets release-1.8

[release-1.8] Azure Blob Storage state store conformance tests

---

bindings/azure/servicebusqueues/metadata.go
bindings/azure/servicebusqueues/metadata_test.go

This is the original PR by @cmendible from #1847 but rebased onto the release-1.8. Somehow @cmendible's PR got messed up so I re-added the commit here.
All credits go to @cmendible (and the authorship of the Git commit is preserved).
Fixes #1845

Fixing #1845

---

pubsub/redis/redis.go

Previously, ACKs could fail if the context was canceled.
Also, do not log errors for "context canceled" during shutdown

pubsub.redis: better ack for messages

---

pubsub/mqtt/mqtt.go
pubsub/mqtt/mqtt_test.go
tests/certification/pubsub/mqtt/components/consumer1/mqtt.yaml
tests/certification/pubsub/mqtt/components/consumer3/mqtt.yaml
tests/certification/pubsub/mqtt/mqtt_test.go

This PR backports #1882 into release-1.8 and fixes #1881 for the release branch.
Because of the very large number of changes in master, this is a separate PR and should not be cherry-picked back into master. For master, please merge #1882.

Backporting #1882 (MQTT fix) into release-1.8

---

pubsub/mqtt/mqtt.go
pubsub/mqtt/mqtt_test.go
tests/certification/pubsub/mqtt/components/consumer3/mqtt.yaml
tests/certification/pubsub/mqtt/mqtt_test.go

pubsub.mqtt: support wildcard and shared subscriptions

---

bindings/alicloud/rocketmq/rocketmq.go

Signed-off-by: 1046102779 <seachen@tencent.com>
relatived PR : https://github.com/dapr/components-contrib/pull/1884
solved DCO.
/cc @ItalyPaleAle @daixiang0

modify error msg

---

.github/workflows/certification.yml
.github/workflows/conformance.yml

Fixes a bug introduced in #1902 by me.

Remove pre-condition from cert & conf test workflow

---

pubsub/aws/snssqs/metadata.go
pubsub/aws/snssqs/snssqs.go
pubsub/aws/snssqs/snssqs_test.go

Fixes #1907
Signed-off-by: Clare Liguori <liguori@amazon.com>

pubsub.snssqs: Support regions in other AWS partitions

---

tests/certification/secretstores/local/env/go.mod
tests/certification/secretstores/local/env/go.sum
tests/certification/secretstores/local/file/go.mod
tests/certification/secretstores/local/file/go.sum

updated local secret stores certification test dependencies
Please reference the issue this PR will close: #1947

updated local secret stores certification test dependencies

---

.github/workflows/dapr-bot.yml

I introduced a tiny bug in Dapr Bot before. This fixes it. Sorry!

Fix dapr bot

---

bindings/ipfs/ipfs_test.go

/cc @ItalyPaleAle 
relative issue: https://github.com/dapr/components-contrib/pull/1951#issuecomment-1211523181

fix: bindings.ipfs unit test

---

.github/workflows/certification.yml

make certification tests fail on build failure

make certification tests fail on build failure

---

.github/infrastructure/conformance/hashicorp/setup-hashicorp-vault-secrets.sh
.github/infrastructure/docker-compose-hashicorp-vault.yml
.github/workflows/conformance.yml
tests/config/secretstores/hashicorp/vault/hashicorp-vault.yml
tests/config/secretstores/tests.yml
tests/conformance/common.go

This PR adds conformance tests for Hashicorp Vault secret store component.
This will help brining this component to stable status.
This addresses **but does not fix** #1926.

Conformance tests for Hashicorp Vault.

---

state/aws/dynamodb/dynamodb.go
state/aws/dynamodb/dynamodb_test.go

This change adds support for first-write concurrency to the AWS DynamoDB state store.
Please reference the issue this PR will close: #1982 
* [*] Code compiles correctly
* [*] Created/updated tests
* [n/a] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

AWS DynamoDB first write concurrency support

---

.github/workflows/conformance.yml
tests/config/bindings/postgres/bindings.yml
tests/config/bindings/tests.yml
tests/conformance/common.go

Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>
Added postgres conformance test for binding.
Please reference the issue this PR will close: #1984 

Added postgres conformance test for binding

---

.gitignore

Add macOS .DS_Store to gitignore

Add macOS .DS_Store to gitignore

---

pubsub/azure/eventhubs/eventhubs.go
pubsub/azure/eventhubs/eventhubs_test.go

This PR allows bulk publish capabilities in Azure Event Hubs. 
Please reference the issue this PR will close: #2090 

Add bulk publish support to Azure Event Hubs

---

.github/workflows/components-contrib.yml

Run unit tests and linter on feature branches

Run unit tests and linter on feature branches

---

bindings/azure/blobstorage/blobstorage.go

Follow-up from #2112
`unicode.IsLetter(r)` allows all runes that are part of the `L` category in Unicode, which contains over 100,000 characters. Changed to allow only ASCII characters.

Do not allow Unicode letters in sanitized metadata

---

internal/component/kafka/consumer.go
middleware/http/bearer/bearer_middleware.go
middleware/http/oauth2/oauth2_middleware.go
middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware.go
middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware_test.go
middleware/http/opa/middleware.go
middleware/http/ratelimit/ratelimit_middleware.go
middleware/http/routerchecker/routerchecker_middleware.go
middleware/http/sentinel/middleware.go
middleware/http/sentinel/middleware_test.go

This adds back the session done select. 
Merges master into feature/pubsub-batching.
Adding back - change that was by mistake removed the session.Done() case was missing.
https://github.com/dapr/components-contrib/pull/2049/

Fix kafka session done merge master

---

state/azure/cosmosdb/cosmosdb_query.go

Signed-off-by: Ryan Lettieri <ryanLettieri@microsoft.com>
Fixed page size limit bug in cosmosdb statestore
No issue to reference

Fixing page limit on cosmosdb

---

internal/component/kafka/consumer.go
internal/component/kafka/utils.go
metadata/utils.go
pubsub/kafka/kafka.go
pubsub/requests.go
tests/conformance/pubsub/pubsub.go

Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>
This PR simply updates key name to keep consistency.
Please reference the issue this PR is related to: https://github.com/dapr/dapr/issues/2218

Renames key to keep consistency

---

pubsub/azure/eventhubs/eventhubs.go

Add context to the BulkPublish signature in Azure EventHubs 
Main issue: dapr/dapr#2218

Azure EventHubs update Bulk Publish signature

---

bindings/aws/s3/s3.go

Follow up for https://github.com/dapr/components-contrib/issues/2074.

Add AWS S3 standalone presign operation

---

internal/component/azure/servicebus/subscription.go
internal/component/kafka/consumer.go
internal/component/kafka/kafka.go
internal/component/kafka/producer.go
pubsub/azure/servicebus/message.go
pubsub/azure/servicebus/servicebus.go
pubsub/kafka/kafka.go
pubsub/requests.go
pubsub/responses.go
pubsub/responses_test.go
tests/conformance/pubsub/pubsub.go

Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>
Please refer discussion https://github.com/dapr/dapr/pull/5256#discussion_r982864283.
Please reference the issue this PR is related to: https://github.com/dapr/dapr/issues/2218

Update EntryID to EntryId

---

internal/httputils/requests.go
internal/httputils/requests_test.go
middleware/http/wasm/basic/basic.go

I noticed some edge cases working on http-wasm, so figured I would raise a PR.

Handles request URI edge cases

---

go.mod
secretstores/gcp/secretmanager/secretmanager.go
secretstores/gcp/secretmanager/secretmanager_test.go

Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/5320

Fix bulk get from gcp secret store

---

.devcontainer/devcontainer.json
tests/certification/pubsub/azure/servicebus/topics/components/authentication/service_bus.yaml
tests/certification/pubsub/azure/servicebus/topics/components/consumer_one/service_bus.yaml
tests/certification/pubsub/azure/servicebus/topics/components/consumer_two/service_bus.yaml
tests/certification/pubsub/azure/servicebus/topics/components/default_ttl/service_bus.yaml
tests/certification/pubsub/azure/servicebus/topics/components/entity_mgmt/service_bus.yaml
tests/certification/pubsub/azure/servicebus/topics/servicebus_test.go

More fixes to ASB cert tests

---

nameresolution/mdns/mdns.go
nameresolution/mdns/mdns_test.go

Release 1.9: Cherry-Pick #2220

Release 1.9: Cherry-Pick #2220

---

nameresolution/mdns/mdns.go
nameresolution/mdns/mdns_test.go

Release 1.7: Cherry-Pick #2220

Release 1.7: Cherry-Pick #2220

---

nameresolution/mdns/mdns.go
nameresolution/mdns/mdns_test.go

Release 1.8: Cherry-Pick #2220

Release 1.8: Cherry-Pick #2220

---

.github/workflows/components-contrib.yml
.golangci.yml
bindings/alicloud/dingtalk/webhook/webhook_test.go
bindings/gcp/bucket/bucket.go
bindings/rethinkdb/statechange/statechange.go
pubsub/jetstream/metadata_test.go
pubsub/rabbitmq/rabbitmq.go
secretstores/azure/keyvault/keyvault.go
secretstores/hashicorp/vault/vault.go
state/oci/objectstorage/objectstorage.go
state/sqlserver/migration.go
tests/conformance/utils/utils.go

Upgrade linter to v1.50.1
Fix linter issues
Disable deprecated linters

Upgrade linter and fix linter issues

---

tests/conformance/workflows/workflows.go
workflows/metadata.go
workflows/requests.go
workflows/temporal/temporal.go

Updated Temporal Init to allow for custom namespaces

Updating Temporal Init to allow for custom namespaces

---

tests/certification/pubsub/azure/servicebus/topics/servicebus_test.go

Fix servicebus topics certification test

Fix servicebus topics certification test

---

go.mod
go.sum
pubsub/mqtt/mqtt.go
tests/certification/pubsub/mqtt/go.mod
tests/certification/pubsub/mqtt/go.sum

There has been changes in  upstream mqtt sdk to handle a race condition in https://github.com/dapr/components-contrib/blob/84cd16677fc555570f7f261f0a6bb0bb1c774b42/pubsub/mqtt/mqtt.go#L193
This issue is very specific to steps described in the issue #2264 i.e. When there are two subscriptions and messages are being published only to the 1st topic(If we reverse it or introduced even an extra route for any 3rd topic for which there is no subscription it does not get reproduced) and subscriber gets killed after publishing few message. If the subscriber comes online and there has been few (>2) messages published already then it only delivers the 1st pending message and gets stuck.
The reason is when it will try to subscribe for the 2nd topic, it will try to reset the subscription and call …

[hotfix-1.9] Upgrade mqtt component

---

.github/workflows/conformance.yml
state/in-memory/in_memory.go
state/in-memory/in_memory_test.go
tests/config/state/in-memory/statestore.yaml
tests/config/state/tests.yml
tests/conformance/common.go

This PR adds conformance tests for the in-memory state store and fixes a large number of issues with the component. The component now passes conf tests

Fix state.in-memory and enable conformance tests

---

.github/scripts/dapr_bot.js
.github/workflows/dapr-bot.yml

Refactor dapr bot to read from a file instead of YAML embedded JavaScript.
Add support to create issues based on labels
- `documentation required` for dapr/docs 
From https://github.com/dapr/dapr/pull/5543#issuecomment-1322852245
Partially addresses https://github.com/dapr/components-contrib/issues/2209 

Dapr bot refactoring and label handling

---

tests/config/state/tests.yml
tests/conformance/state/state.go

Updates conformance tests to validate TTLs and enables the test for state stores that support that

Add conformance test for TTL in state stores

---

state/azure/cosmosdb/cosmosdb.go
tests/certification/state/azure/cosmosdb/cosmosdb_test.go

This is a cherry-pick from release into master of the Cosmos DB Etag hotfix. #2322

Cherry-pick from release into master: Cosmos DB Etag hotfix

---

.github/workflows/conformance.yml

Hopefully this fixes the Kubernetes secret store conformance test

Fix kubernetes secretstore conformance test

---

pubsub/mqtt/mqtt.go

Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>
Cherry-picking this commit from https://github.com/dapr/components-contrib/pull/2310 to go in 1.9 Hotfix.
Please reference the issue this PR will close: #2300 

[1.9 Hotfix] Mqtt/Pub-sub: Ack Retained Message

---

bindings/cron/cron_test.go
tests/certification/bindings/cron/cron_test.go

Signed-off-by: Sarthak Sharma <sartsharma@microsoft.com>
Add fix for flaky cron certification tests

Fix flaky tests for cron binding certification

---

pubsub/jetstream/jetstream.go
pubsub/jetstream/metadata.go
pubsub/jetstream/metadata_test.go

Add AckPolicy option to NATS pub/sub

---

.github/infrastructure/docker-compose-postgresql.yml
.github/workflows/conformance.yml
tests/certification/state/postgresql/postgresql_test.go

**PLEASE DO NOT SQUASH**
This PR cherry-picks 3 commits from master into release-1.9 so that cert/conf tests can pass in the release branch.

[release-1.9] backport fixes to tests [DO NOT SQUASH] 

---

.github/workflows/certification.yml
.github/workflows/conformance.yml

Fix conf & cert test workflow

---

go.mod
go.sum

This updates [wazero](https://wazero.io/) to [1.0.0-pre.6](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.6).
Notably, v1.0.0-pre.6:
* improves module compilation and initialization performance
While not used yet here, if someone asks for filesystem writes, it is now possible due to these features.
* adds `writefs.NewDirFS` which lets you add new files.
* `path_open` `O_CREAT` flags, `path_remove_directory` `path_rename` `path_unlink_file`
* adds `NewFilesystemLoggingListenerFactory` with dramatically improved logging.
This also includes changes described in [1.0.0-pre.5](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.5).
* [n/a] Created/updated tests
* [n/a] Extended …

deps: updates wazero to 1.0.0-pre.6

---

.github/infrastructure/terraform/certification/pubsub/aws/snssqs/snssqs.tf

Adds certification test specific terraform files for AWS

Add certification test terraform files

---

.github/workflows/certification.yml

Signed-off-by: Roberto J Rojas <robertojrojas@gmail.com>
Fixes for the following workflow error:
https://github.com/dapr/components-contrib/actions/runs/3907360587/jobs/6676509630

state.aws.DynamoDB: Fixes Certification Test Workflow Error

---

go.mod
go.sum

Hopefully addresses dapr/dapr#5695 ARM build issue.

Update to wazero 1.0.0pre7 with http-wasm-go 0.3.1

---

go.mod
go.sum
state/zookeeper/zk.go
state/zookeeper/zk_mock.go
state/zookeeper/zk_test.go

Replace deprecated zookeeper library

---

internal/authentication/azure/auth.go

The Azure CLI is now issuing client certificates in an "unusual" format: a single file containing 2 PEM-encoded DER blocks with both the certificate and key. This updates our Azure AD auth layer to support that format too, in addition to the "usual" PKCS#12/PFX.
Fixes #2396

Support PEM certificates from Azure AD

---

bindings/azure/eventgrid/eventgrid.go
bindings/azure/eventgrid/eventgrid_test.go
go.mod
go.sum
tests/config/bindings/azure/eventgrid/bindings.yml

1. Updated management SDK to "track 2"
2. If the Event Grid endpoint needs to be updated, do not override the previously-set properties
3. Be more tolerant with "subscriberEndpoint" if path ("/api/events") is missing
Fixes https://github.com/dapr/components-contrib/issues/2454

Updates and fixes to Event Grid binding

---

.devcontainer/devcontainer.json

Uses the new devcontainers from dapr/dapr
Additionally, adds some settings that are useful when working with Dapr

Updated devcontainer.json

---

.github/infrastructure/conformance/azure/setup-eventgrid-sp.ps1

Fixes a bug when the script is run the first time (before, it required running the script twice).
Note: this only impacts tests, so doesn't need to be included in a new RC

[release-1.10] Fix small bug in PowerShell script for Azure setup

---

bindings/twitter/twitter.go

Deprecate the Twitter Binding. For details see #2503.
Work towards #2503.
Deprecation planned for 1.11.

Deprecate Twitter Binding

---

.github/workflows/components-contrib-all.yml
.github/workflows/components-contrib.yml
.github/workflows/conformance.yml

Added a PR comment to the complete build matrix action run when using `/ok-to-test`
Also enabled the Linux cache again for the PR workflow.

Workflow improvements - enable workflows for merge queues.

---

internal/component/azure/servicebus/subscription.go

Follow-up from #2533, where some channels were not handled correctly. Also improved log messages further by showing number of messages whose locks were renewed (and how many failed)

[release-1.10] Small concurrency fixes

---

.github/scripts/dapr_bot.js
bindings/azure/servicebusqueues/metadata.yaml

Includes a test commit for merge queue testing.
Fixes a GitHub workflow.

Fix Dapr Bot Failure when PR is labeled

---

.github/scripts/dapr_bot.js

Adds joshvanl to dapr_bot list

---

middleware/http/oauth2/oauth2_middleware.go
middleware/http/oauth2/oauth2_middleware_test.go
middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware.go
middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware_test.go

Fix OAuth2 Client Credentials middleware too

---

middleware/http/oauth2/oauth2_middleware.go
middleware/http/oauth2/oauth2_middleware_test.go
middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware.go
middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware_test.go

Backports #2616 and #2629 into release-1.10

[release-1.10] Backport OAuth middlewares fixes into 1.10 [DO NOT SQUASH]

---

.github/workflows/dapr-bot-schedule.yml

Add @ItalyPaleAle to dapr bot maintainers

Add italypaleale to dapr bot maintainers

---

.devcontainer/devcontainer.json

Moved `extensions` and `settings` sections in `devcontainer.json` as per the schema  tooltips in VS Code
Please reference the issue this PR will close: #2648

Move vscode settings in devcontainer.json

---

pubsub/redis/metadata.yaml

modify component metadata.type for pubsub.redis
Please reference the issue #2580.

modify component metadata.type for pubsub.redis

---

.github/workflows/generate-component-metadata-for-tag.yml

This workflow generates and adds the component metadata bundle on push to tags.

Generate metadata bundle for tags

---

.github/workflows/generate-component-metadata-for-tag.yml

fix workflow to upload bundle json asset

Fix workflow: upload metadata bundle for real

---

bindings/cron/metadata.yaml

Create component metadata for bindings.cron
Please reference the issue #2572 .

Create component metadata for bindings.cron

---

state/postgresql/metadata.yaml

Create component metadata for state.postgresql
Please reference the issue #2589 .

Create component metadata for state.postgresql

---

internal/component/postgresql/postgresdbaccess.go

Fix Postgres state store hardcoding table name in Delete method

---

metadata/utils.go
middleware/http/bearer/bearer_middleware.go
middleware/http/bearer/metadata.go
middleware/http/oauth2/oauth2_middleware.go
middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware.go
middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware_test.go
middleware/http/opa/middleware.go
middleware/http/ratelimit/ratelimit_middleware.go
middleware/http/ratelimit/ratelimit_middleware_test.go
middleware/http/routeralias/routeralias_middleware.go
middleware/http/routerchecker/routerchecker_middleware.go
middleware/http/sentinel/middleware.go
middleware/http/wasm/httpwasm.go
middleware/middleware.go
workflows/temporal/temporal.go
workflows/workflow.go

Refactor metadata parsing in middlewares and workflows

Refactor metadata parsing in middlewares and workflows

---

internal/component/postgresql/postgresdbaccess.go
state/mysql/mysql.go
state/oracledatabase/oracledatabaseaccess.go
state/sqlite/sqlite_dbaccess.go
tests/conformance/state/state.go

Also adds conformance tests
Fixes #2722

State stores should always allow values that are empty strings

---

state/mysql/mysql.go
state/oracledatabase/oracledatabaseaccess.go
state/postgresql/postgresdbaccess.go
state/sqlite/sqlite_dbaccess.go
tests/conformance/state/state.go

Backports #2723 into release-1.10

[release-1.10] Backport #2723

---

state/cockroachdb/cockroachdb_integration_test.go
state/oracledatabase/oracledatabase_integration_test.go
state/oracledatabase/oracledatabaseaccess.go

Since release-1.10 was made with "cherry-picked" things (even when they were manually applied), this PR doesn't bring in much except a few changes in tests.
However, merging release-1.10 into master allows us to keep the branches in sync.
> This is a merge PR, so please don't squash. Also, DCO will fail.

Merge release-1.10 into master [DO NOT SQUASH]

---

secretstores/hashicorp/vault/metadata.yaml

Create component metadata for secretstores.hashicorp.vault
Please reference the issue: #2585.

Create component metadata for secretstores.hashicorp.vault

---

bindings/azure/storagequeues/metadata.yaml

Metadata YAML for Azure Storage Queues binding

---

pubsub/azure/servicebus/topics/metadata.yaml

Add Service Bus Topics Pubsub Metadata

Add Service Bus Topics Pubsub Metadata

---

.build-tools/pkg/metadataschema/builtin-authentication-profiles.go
bindings/azure/blobstorage/metadata.yaml
bindings/azure/cosmosdb/metadata.yaml
secretstores/azure/keyvault/metadata.yaml
state/azure/blobstorage/metadata.yaml

Add component metadata YAML for Azure CosmosDB output binding.
Verified with `make check-component-metadata && make bundle-component-metadata`

Add component metadata YAML for Azure CosmosDB output binding.

---

bindings/azure/storagequeues/metadata.yaml
bindings/azure/storagequeues/storagequeues.go
bindings/azure/storagequeues/storagequeues_test.go

Azure Storage Queues: Make polling interval configurable

---

bindings/azure/cosmosdbgremlinapi/metadata.yaml

Add component metadata YAML for Azure Cosmos DB (Gremlin API) output binding

Add component metadata YAML for Azure Cosmos DB (Gremlin API) output binding

---

state/redis/metadata.yaml

Minor updates to state.redis template

Minor updates to state.redis template

---

configuration/redis/metadata.yaml

Add component metadata YAML for configuration.redis.

Add component metadata YAML for configuration.redis.

---

bindings/mysql/metadata.yaml

Create Azure Component template for bindings.mysql

Create Azure Component template for bindings.mysql

---

pubsub/kubemq/kubemq.go
pubsub/kubemq/kubemq_events.go
pubsub/kubemq/kubemq_eventstore.go

This PR fixes panic of dapr on close component and fixes small issues needed for production 
* [x ] Code compiles correctly
* [x ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

Update KubeMQ components (Fix panic and small production issues)

---

go.mod
go.sum
tests/certification/pubsub/pulsar/go.mod
tests/certification/pubsub/pulsar/go.sum

Downgrade Sarama to 1.37.2 for Kafka

Hotfix 1.10.6: Kafka: Downgrade Sarama to 1.37.2

---

pubsub/jetstream/jetstream_test.go

@berndverst @JoshVanL Here are a couple unit tests as a follow-up to #2835

Add JetStream pubsub unit tests

---

.github/workflows/certification.yml

I was searching for something in one of my other dapr repos in my VSCode workspace when I came across these lines that look like they should be cleaned up. Not sure if this was an addition prepping for 1.11 release, or if this should be removed now. Thoughts? @ItalyPaleAle @berndverst 

build: rm branch to clean up build

---

.build-tools/go.mod
.build-tools/go.sum
go.mod
go.sum
tests/certification/go.mod
tests/certification/go.sum
tests/e2e/pubsub/jetstream/go.mod
tests/e2e/pubsub/jetstream/go.sum

Update dapr/kit for quality of life improvement related to Crypto APIs.
Minor but meaningful improvement for dealing with trailing spaces in keys.

[Release 1.11] Update dapr/kit to `0.11.1`

---

state/memcached/memcached.go
state/memcached/memcached_test.go
tests/certification/state/memcached/memcached_test.go

memached: if tllInSeconds larger than 30 days, convert to unix timestamp

---

state/memcached/memcached.go
state/memcached/memcached_test.go
tests/certification/state/memcached/memcached_test.go

Backport from https://github.com/dapr/components-contrib/pull/2890

memached: if tllInSeconds larger than 30 days, convert to unix timestamp 

---

state/mysql/mysql.go
state/mysql/mysql_integration_test.go
state/mysql/mysql_test.go
state/responses.go
tests/certification/state/mysql/mysql_test.go

See https://github.com/dapr/components-contrib/pull/2863

mysql: return ttlExpiryTime in GetResponse

---

state/aws/dynamodb/dynamodb.go
state/aws/dynamodb/dynamodb_test.go
tests/certification/state/aws/dynamodb/dynamodb_test.go

See https://github.com/dapr/components-contrib/pull/2863

dynamodb: return ttlExpiryTime in GetResponse

---

state/azure/cosmosdb/cosmosdb.go

See https://github.com/dapr/components-contrib/pull/2863

cosmosdb: return ttlExpiryTime in GetResponse

---

state/sqlserver/migration.go
state/sqlserver/sqlserver.go
tests/certification/state/sqlserver/sqlserver_test.go

See https://github.com/dapr/components-contrib/pull/2863

sqlserver: return ttlExpiryTime in GetResponse

---

.devcontainer/devcontainer.json

We need a new tag in the dev container

Updated Go tags in dev container

---

state/cloudflare/workerskv/metadata.yaml

Adds Cloudflare Workers KV Component Metadata Schema.
this PR will close: #2907

[Cloudflare Workers KV] Adds Component Metadata Schema

---

.github/infrastructure/docker-compose-sqlserver.yml
state/sqlserver/migration.go
state/sqlserver/sqlserver.go
state/sqlserver/sqlserver_integration_test.go
tests/certification/state/sqlserver/docker-compose.yml
tests/certification/state/sqlserver/sqlserver_test.go

[release-1.11] Cherry-pick sql server fixes #2912

[release-1.11] Cherry-pick sql server fixes #2912

---

go.mod
go.sum

Fixes unlicensed indirect dependencies. One of those was accidentally removed in #2927

Fix unlicensed indirect dependencies

---

state/mongodb/mongodb.go
state/mongodb/mongodb_test.go

Added a close function for mongodb store.
https://github.com/dapr/components-contrib/issues/2949
Please reference the issue this PR will close: #2949 

feat: close mongo db

---

internal/component/azure/blobstorage/client.go
internal/component/azure/blobstorage/client_test.go

Cherry-pick #2959 into the release-1.11 branch

[release-1.11] Azure Blob Storage: gracefully handle setting "endpoint" to non-emulator (#2959)

---

state/cassandra/cassandra.go

Added a close method for Cassandra.
Please reference the issue this PR will close: #2951

feat: add close method for Cassandra

---

bindings/azure/blobstorage/metadata.yaml
bindings/azure/cosmosdb/cosmosdb.go
bindings/azure/cosmosdb/metadata.yaml
bindings/azure/cosmosdbgremlinapi/metadata.yaml
bindings/azure/eventgrid/metadata.yaml
bindings/azure/eventhubs/metadata.yaml
bindings/http/metadata.yaml
bindings/postgres/metadata.yaml
bindings/redis/metadata.yaml
configuration/azure/appconfig/metadata.yaml
pubsub/azure/eventhubs/metadata.yaml
pubsub/azure/servicebus/queues/metadata.yaml
pubsub/azure/servicebus/topics/metadata.yaml
state/azure/blobstorage/metadata.yaml
state/sqlserver/metadata.yaml

Some linting in metadata.yaml files
Also removed a superfluous log statement in Cosmos DB binding that could have logged PII.

Some linting in metadata.yaml files

---

go.mod
go.sum
tests/certification/pubsub/pulsar/go.mod
tests/certification/pubsub/pulsar/go.sum

[release-1.10] Upgrade avro dependency

---

go.mod
go.sum
tests/certification/go.mod
tests/certification/go.sum

[release-1.11] Upgrade avro dependency

---

state/couchbase/couchbase.go

Implement io.closer for couchbase to improve shutdown process and not consume db resources
Please reference the issue this PR will close: #close

Add closer to couchbase

---

tests/certification/bindings/azure/servicebusqueues/servicebusqueue_test.go

Also added prefix to all sent messages so tests don't fail if there are multiple concurrent runners (hopefully)

Fixed flaky cert test for ASB Queue binding

---

state/cockroachdb/metadata.yaml

Continuation from issue 3054 - updates as per PR review
This PR will close: #3054

[State CockroachDB] Continuation from issue 3054

---

.github/infrastructure/conformance/azure/conf-test-azure-appconfig.bicep
.github/infrastructure/conformance/azure/conf-test-azure.bicep
.github/infrastructure/conformance/azure/setup-azure-conf-test.sh

Test infra for Azure App Config Configuration Store

Add Azure App Config to Conf Test infra

---

README.md

fix a readme url error
fix: #3091

fix readme url error

---

state/etcd/etcd.go

Define ETCD Transaction limit
Because the transaction limit in ETCD depends on the server (via server flag `--max-txn-ops`), but with a default of 128 if unset I have also exposed this configuration option via a new `maxTxnOps` component metadata option.

Define ETCD Transaction limit

---

pubsub/gcp/pubsub/metadata.yaml

[PubSub GCP] Fixes Metadata name typo.

[PubSub GCP] Fixes Metadata Name typo

---

bindings/kafka/metadata.yaml
internal/component/kafka/auth.go
internal/component/kafka/metadata.go
internal/component/kafka/sasl_oauthbearer.go
pubsub/kafka/metadata.yaml

Originally implemented by @teachmeabhinav (who gets credits for the commits) in #3123
Fixes #3123
Fixes #3008

Enhance Kafka pubsub OIDC auth support to support oauthbearer.extensions

---

bindings/wasm/output.go
bindings/wasm/output_test.go
go.mod
go.sum

Cherry-pick #3077 into release-1.12

[release-1.12] Cherry-pick #3077: Fix wasm binding wasi http

---

tests/certification/go.mod
tests/certification/go.sum

Pin runtime 1.12.0 in cert tests

---

nameresolution/consul/consul.go
nameresolution/consul/consul_test.go

[Release 1.12 Patch] Fix 3204: consul to accept hostnames again

---

internal/component/azure/eventhubs/metadata.go

Fix incorrect Eventhubs error message

---

internal/component/azure/eventhubs/metadata.go

Cherry pick fix for #3210 into release-1.12

[Release-1.12] Fix incorrect Eventhubs error message (#3210)

---

nameresolution/consul/consul.go
nameresolution/consul/consul_test.go

Fix 3204: consul to accept hostnames again

---

bindings/azure/blobstorage/metadata.yaml
internal/component/azure/blobstorage/client.go
internal/component/azure/blobstorage/metadata.go
state/azure/blobstorage/metadata.yaml

Cherry-pick #3213 for AzBlob DisableEntityMgmt

Cherry-pick #3213 for AzBlob DisableEntityMgmt

---

go.mod
go.sum
tests/certification/go.mod
tests/certification/go.sum

[release-1.12] Upgrade sarama to 1.42.1

---

pubsub/solace/amqp/metadata.yaml

Added metadata.yaml for pubsub.solace.amqp
Please reference the issue this PR will close: #3242 

chore: solace-amqp metadata.yaml

---

state/postgresql/v2/postgresql.go

Fixup from #3250 
If the etag is not a UUID, return an UUID mismatch error short-circuiting the query. This is necessary for E2E tests in dapr/dapr to pass

Postgres v2 state: handle invalid etag format

---

state/requests.go
state/sqlite/sqlite.go
state/sqlite/sqlite_dbaccess.go
state/store.go
tests/config/state/tests.yml
tests/conformance/state/state.go

Adds conformance tests for the DeleteWithPrefix method in state stores
See: #3262
CC: @RyanLettieri

Added conformance tests for DeleteWithPrefix

---

workflows/requests.go

This PR adds support for recursive terminate and purge in workflow requests. The related runtime PR: https://github.com/dapr/dapr/pull/7340

Enable recursive terminate/purge

---

common/component/kafka/consumer.go

Fixes https://github.com/dapr/components-contrib/issues/3263.
The way the Kafka component was handling subscription topics was not inline with how Sarama should be correctly used. Until this change, for every new subscription added, the consumer group was closed and started again which in many cases could (and did as reported by users) lead to a cluster-wide outage, as that action involved a rebalance of Kafka partitions. Depending on the number of topics, messages and consumers, Dapr processes would take sometimes minutes to load and in the worst case causing a bottleneck in the Kafka brokers.
This PR fixes that by cancelling and recreating the context for the `Consume` function every time a subscription is added instead of closing down the entire consumer group. This is the correct way …

Fix Kafka consumer

---

nameresolution/kubernetes/kubernetes.go
nameresolution/nameresolution.go
nameresolution/requests.go

[1.12] Nameresolvers: add support for ResolveIDMulti

---

common/authentication/azure/auth.go

Backport of #3338
PS: opened from "upstream" so Azure tests will run automatically

[1.13] Azure auth: do not use CLI provider by default when running in a cloud service

---

common/component/azure/eventhubs/eventhubs.go

[release 1.13] Cherry Pick: Recover interrupted eventhubs subscriptions (#3344)
Fixes EventHubs bindings and pubsub subscription failure scenarios with additional retries (until context is canceled).

[release 1.13] Cherry Pick: Recover interrupted eventhubs subscriptions (#3344)

---

configuration/azure/appconfig/appconfig.go
configuration/azure/appconfig/appconfig_test.go

Cherry pick of #3358 into 1.13

1.13 Cherry-pick: Fix Azure App Config not working with gRPC (#3358)

---

bindings/kafka/kafka.go
common/component/kafka/consumer.go
common/component/kafka/kafka.go
common/component/kafka/mocks/consumergroup.go
common/component/kafka/mocks/mock_ISchemaRegistryClient.go
common/component/kafka/subscriber.go
common/component/kafka/subscriber_test.go
pubsub/kafka/kafka.go
tests/certification/go.mod
tests/certification/go.sum

Cherry pick https://github.com/dapr/components-contrib/pull/3363

[1.13] PubSub Kafka: Respect Subscribe context

---

common/component/kafka/kafka.go
common/component/kafka/kafka_test.go

Fixing bug with new Avro conversion when message values are NULL
Cherry pick bug fix for issue #3388
#3388

Cherry pick bug fix for issue #3388

---

state/azure/cosmosdb/cosmosdb.go

Remove some unnecessary loglines

---

state/azure/cosmosdb/cosmosdb.go

Fixes https://github.com/dapr/components-contrib/pull/3411/files#r1589800894

Fix linter for cosmosdb

---

common/component/kafka/producer.go

Fixes panic in Kafka bulk publisher

Kafka bulk publisher fix

---

.github/scripts/dapr_bot.js

Request to add myself to the bot so I can trigger cert tests with the azure secrets - currently looking into stable cert test failures involving two azure components.
N/A

request: add mikeee to daprbot

---

bindings/http/http.go

Backport of https://github.com/dapr/components-contrib/pull/3466

[1.14] Bindings http default transport

---

go.mod
go.sum
tests/certification/go.mod
tests/certification/go.sum
tests/e2e/pubsub/jetstream/go.mod
tests/e2e/pubsub/jetstream/go.sum

the pkg I bumped is vulnerable as identified in the pr here: 
https://github.com/dapr/dapr/pull/7681

security: fix last vulnerable dep

---

.build-tools/go.mod
go.mod
tests/certification/go.mod
tests/e2e/pubsub/jetstream/go.mod

Pin runtime 1.14.0rc1 in Cert tests, Update Go to 1.22.5

Pin runtime 1.14.0rc1 in Cert tests, Update Go to 1.22.5

---

pubsub/aws/snssqs/snssqs.go
tests/certification/flow/dockercompose/dockercompose.go
tests/certification/pubsub/pulsar/pulsar_test.go
tests/certification/state/cockroachdb/v1/README.md

Fix init in sqssns + Docker Compose update

---

secretstores/aws/secretmanager/secretmanager.go
secretstores/aws/secretmanager/secretmanager_test.go

Cherry picks https://github.com/dapr/components-contrib/pull/3519

[1.14] Cherrypicks Removes check for dummy key in AWS Secrets manager

---

common/component/kafka/kafka.go
common/component/kafka/kafka_test.go

Addressed issue in Kafka-pubsub for avro null messages (#3531)

---

conversation/echo/echo.go

Add echo implement
Please reference the issue this PR will close: #3544

conversation: add echo implement

---

Makefile

fix make target

---

conversation/anthropic/anthropic.go
conversation/aws/bedrock/bedrock.go
conversation/converse.go
conversation/openai/openai.go
conversation/temperature.go

Adds support for response temperature across all models and to the interface.

Add temperature support to conversational api

---

.github/scripts/dapr_bot.js

I need to be able to freely run the tests in my PRs please:
https://github.com/dapr/components-contrib/pull/3591

feat: add me to bot owners to run tests

---

bindings/aws/dynamodb/dynamodb.go
bindings/aws/kinesis/kinesis.go
bindings/aws/s3/s3.go
bindings/aws/ses/ses.go
bindings/aws/sns/sns.go
bindings/aws/sqs/sqs.go
pubsub/aws/snssqs/snssqs.go
secretstores/aws/parameterstore/parameterstore.go
secretstores/aws/secretmanager/secretmanager.go
state/aws/dynamodb/dynamodb.go

I fixed this in a diff PR, but figured it would be best to bring this change out separately.

fix(aws): update close if aws auth provider is nil

---

bindings/azure/eventhubs/metadata.yaml
common/component/azure/eventhubs/eventhubs.go
common/component/azure/eventhubs/metadata.go
pubsub/azure/eventhubs/eventhubs.go
pubsub/azure/eventhubs/metadata.yaml

Closes https://github.com/dapr/components-contrib/issues/3570
Closes https://github.com/dapr/components-contrib/issues/2530

Enable eventhubs binding to read all message properties

---

common/authentication/aws/static.go
common/authentication/aws/x509.go

Just doing some cleaning on the conditionals on postgres static, and leaving comments on x509 side of things as well.

style: pg cleaning up for things

---

.build-tools/go.mod
conversation/deepseek/deepseek.go
conversation/deepseek/metadata.go
conversation/deepseek/metadata.yaml
go.mod
go.sum
tests/certification/go.mod
tests/e2e/pubsub/jetstream/go.mod

This PR adds Deepseek support to the conversational API

Add deepseek support, update Go to 1.23.5

---

.github/workflows/certification.yml
.github/workflows/conformance.yml

Bumps the deprecated action versions, re-enabling the tests

ci: bump upload/download actions

---

.build-tools/go.sum
go.mod
go.sum
tests/certification/go.mod
tests/certification/go.sum
tests/e2e/pubsub/jetstream/go.sum

Update deepseek dependency

---

bindings/gcp/bucket/bucket.go

Fix gcp bucket binding create + improve error messages.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/8517

[1.15] Fix gcp bucket binding create + improve error messages.

---

.github/workflows/certification.yml
.github/workflows/conformance.yml

Backport actions fix

---

go.mod
go.sum
state/oracledatabase/oracledatabaseaccess.go

Fixes issue where checking if a table already exists requires admin privileges.

[1.14] Fix table exists logic for Oracle database

---

state/oracledatabase/dbaccess.go
state/oracledatabase/oracledatabase.go
state/oracledatabase/oracledatabase_integration_test.go
state/oracledatabase/oracledatabase_test.go
state/oracledatabase/oracledatabaseaccess.go

Implementing usage of IN condition in SELECT statement
Please reference the issue this PR will close: #3801 

Add custom BulkGet method to Oracle Statestore

---

common/component/kafka/consumer.go
common/component/kafka/consumer_test.go

This is a backport of #3850 to 1.15.
Please reference the issue this PR will close: #3849

Backport to 1.15: Fixed Kafka PubSub intermittently dropping messages while retrying

---

.github/infrastructure/docker-compose-coherence.yml

Fix minor typo in coherence state docker compose github workflow file.
Please reference the issue this PR will close: #3862
Note: This doesn't actually affect the testing

Coherence store: Fix minor typo in coherence state docker-compose file

---

bindings/kubernetes/kubernetes.go
configuration/postgres/postgres.go
middleware/http/opa/middleware.go

Update release-1.16 from main

---

common/component/kafka/kafka.go
common/component/kafka/kafka_test.go
go.mod
go.sum
tests/certification/go.mod
tests/certification/go.sum

Cherry pick fix in #4026
#4020
**Note:** We expect contributors to open a corresponding documentation PR in the [dapr/docs](https://github.com/dapr/docs/) repository. As the implementer, you are the best person to document your work! Implementation PRs will not be merged until the documentation PR is opened and ready for review.

Fix regression in pubsub.kafka Avro message publication -- Cherry pick to Main (#4026)

---

state/aws/dynamodb/dynamodb.go
state/aws/dynamodb/dynamodb_test.go

Backport of https://github.com/dapr/components-contrib/pull/3658 that merged on 1.15.5 but failed to reach 1.16

Feature/backport-3658-2 (#3877)
