dapr/components-contrib

- .golangci.yml
Set modules-download-mode to vendor. 
Reference: https://github.com/golangci/golangci-lint/issues/395
N/A
> [golangci] Set modules-download-mode to vendor

- pubsub/redis/metadata.go
- pubsub/redis/redis.go
- pubsub/redis/redis_test.go
This PR allows Redis Pub/Sub to established a secured connection to TLS enabled Redis servers.
Closes #95.
> Add TLS connection option to Redis pub sub

- pubsub/nats/nats.go
- pubsub/nats/nats_test.go
`consumerID` is the well known ID used by pub-sub implementations to create a group of logical consumers.
Dapr uses this known field to pass in the `daprID` associated with the application.
This is consistent with Redis Streams and the upcoming Azure Service Bus.
> Use consumerID for queue name

- servicediscovery/mdns/mdns.go
Don't cache zeroconf resolver.  For some reason if it's cached the first lookup works normally, but subsequent ones cannot resolve the target app.  
> don't cache zeroconf resolver

- state/requests.go
Currently custom metadata to a state store implementation is only supported through a SetRequest.
This proposes to add passing metadata with GetRequest and DeleteRequest also.
#101 
> Adding metadata to State Delete and Get requests

- state/cosmosdb/cosmosdb.go
See https://github.com/dapr/components-contrib/issues/132.  The fix is to return default response.
See https://github.com/dapr/components-contrib/issues/132
Please reference the issue this PR will close: #_132_
> Don't return nil for response when length of items is 0

- bindings/azure/signalr/signalr.go
- bindings/azure/signalr/signalr_test.go
- go.mod
- go.sum
- pubsub/rabbitmq/metadata_test.go
- pubsub/rabbitmq/rabbitmq.go
Add support to Azure SignalR as output binding
#147 
> Add Azure SignalR binding

- state/azure/sqlserver/sqlserver.go
- state/azure/sqlserver/sqlserver_integration_test.go
- state/azure/sqlserver/sqlserver_test.go
Rename SQLServer state constructor to follow current convention. From NewSQLServerStore to NewSQLServer**State**Store.
Current state stores:
```golang
// Load state stores
func Load() {
RegisterStateStore("redis", func() state.Store {
return redis.NewRedisStateStore()
})
RegisterStateStore("consul", func() state.Store {
return consul.NewConsulStateStore()
})
RegisterStateStore("azure.cosmosdb", func() state.Store {
return cosmosdb.NewCosmosDBStateStore()
})
RegisterStateStore("etcd", func() state.Store {
return etcd.NewETCD()
})
RegisterStateStore("cassandra", func() state.Store {
return cassandra.NewCassandraStateStore()
})
RegisterStateStore("memcached", func() state.Store {
return memcached.NewMemCacheStateStore()
})
RegisterStateStore("mongodb", func() state.Store {
return …
```
> Rename SQLServer state ctor to existing pattern

- bindings/responses.go
Need to change the AppResponse struct to have the store name and state requests separately to support multiple state stores support in Dapr.
This is needed to support this requirement : dapr/dapr#636
Added the store name in the AppResponse and requests separately.
#182 
> Modify the AppResponse struct to have the store name 

- secretstores/azure/keyvault/authutils.go
- secretstores/azure/keyvault/authutils_test.go
- secretstores/azure/keyvault/keyvault.go
Adding support for Manage Identities in the Azure Key Vault Secret Store
Code in _authutils.go_ now extends _keyvaultSecretStore_ in such a way that calling the _GetAuthorizer()_ method result in using a client certificate to call the key vault if all the needed configuration is provided or fall back to using Managed Identities pretty much like the Azure SDK does when calling _GetAuthorizer_  in the autorest code found [here](https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go)
Please reference the issue this PR will close: #184
If you think …
> [WIP] Adding support for Manage Identities in the Azure Key Vault Secret Store

- go.mod
- go.sum
- state/Readme.md
- state/azure/tablestorage/tablestorage.go
- state/azure/tablestorage/tablestorage_test.go
Azure Table storage state provider. This is using the official Azure Go SDK from Microsoft.
1. Cloned dapr repository and changed cmd/daprd/main.go:
state store import:
```go
state_azure_tablestorage "github.com/dapr/components-contrib/state/azure/tablestorage"
```
registered the store:
```go
state_loader.New("azure.tablestorage", func() state.Store {
return state_azure_tablestorage.NewAzureTablesStateStore()
}),
```
2. In dapr repo, changed `go.mod` to redirect to local copy of `components-contrib`:
```
replace (
github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.0+incompatible
github.com/dapr/components-contrib => ../components-contrib
github.com/dapr/components-contrib v0.0.0-20200116212630-381777dc3b3e => ../components-contrib
k8s.io/client => …
```
> Azure Table Storage state

- secretstores/azure/keyvault/authutils.go
- secretstores/azure/keyvault/authutils_test.go
Wrong condition was preventing the Key Vault secret store to fallback to MSI authentication when needed.
* [ x] Code compiles correctly
* [ x] Created/updated tests
> Fixed issue preventing authentication fallback to MSI

- middleware/http/nethttpadaptor/nethttpadaptor.go
- middleware/http/nethttpadaptor/nethttpadaptor_test.go
Add a check for `nil` body in input `http.Request` in `nethttpadaptor.NewNetHTTPHandlerFunc`.
Add a new unit test to cover this scenario.
Please reference the issue this PR will close: #217
> Added check to handle nil request body in nethttpadaptor

- middleware/http/nethttpadaptor/nethttpadaptor.go
- middleware/http/nethttpadaptor/nethttpadaptor_test.go
Originally I was converting the protomajor and protominor from ints to string using a basic cast, however, this results in the string being a UTF encoded unicode code point which is not what we want. I've updated it to use an explicit conversion.
Please reference the issue this PR will close: [dapr #1060](https://github.com/dapr/dapr/issues/1060)
> Changed how proto header is converted to string

- secretstores/aws/secretmanager/secretmanager.go
This PR makes consistent the `version_id` metadata property between GCP and AWS Secret managers and conforms `version_stage` to the casing format.
> change version params for aws secrets manager

- go.mod
- go.sum
- pubsub/envelope.go
- pubsub/envelope_test.go
This extention is to allow carrying correlation ID in cloud event envelop.
> extend envelop to include a subject field

- bindings/twilio/sms.go
- bindings/twilio/sms_test.go
In Twilio Binding spec the toNumber is required in the metadata. The application is NOT able to send the recipient number dynamically from the POST endpoint data. The toNumber passed in metadata is not used to send in Twilio API.
Changing this implementation to
1. Optional toNumber field in metadata.
2. The toNumber can be both configured as metadata or send as POST data to the endpoint.
3. Added tests to make sure the call to Twilio is covered. 
4. Change the code to mock the HTTP client in tests.
Please reference the issue this PR will close: #255 
> Twilio Binding - Get To Number from Request

- secretstores/azure/keyvault/keyvault.go
Azure Key Vault should use the request secret name instead of the current default value.
> Fix key for Azure KeyVault

- state/memcached/memcached.go
Updated implementation to ensure that non-existent keys are not treated as errors
Issue #263 
> Memcached state store: don't treat non-existent keys as errors

- bindings/aws/kinesis/kinesis.go
- bindings/aws/kinesis/kinesis_test.go
- go.mod
- go.sum
Implemented the bindings for the AWS Kinesis data stream. This binding supports both shared throughput mode and extended fanout mode.
1. The metadata includes AWS credentials, Stream Name, Consumer Name, and mode.
2. If the mode is "Shared throughput",  the worker-client is created to process the records and track checkpoints in dynamodb and monitor using cloud watch alarms. There is no internal support in [aws-sdk-go](https://github.com/aws/aws-sdk-go) library. Used the [vmware/vmware-go-kcl](https://github.com/vmware/vmware-go-kcl) - Kinesis client library with custom checkpoint implementation using dynamodb.
3. If the mode is "Extended Fanout - Dedicated throughput", subscribing to all shards using kinesis subscriber API using [aws-sdk-go](https://github.com/aws/aws-sdk-go)  library. …
> Add Kinesis data stream binding

- state/aerospike/aerospike.go
If the err is ErrKeyNotFound, return an empty response for the aerospike datastore
PR will close: #260 
> Empty response when aerospike state key not found

- middleware/http/ratelimit/ratelimit_middleware.go
Two misspellings of the word middleware in the error messages reported to users
None
> Small misspellings in ratelimit middleware error messages

- bindings/redis/metadata.go
- bindings/redis/redis.go
- bindings/redis/redis_test.go
- go.mod
- go.sum
Added TLS support for bindings.redis component.
* Refactored to use go-redis library instead of joomcode/redis 
Please reference the issue this PR will close: [#_[286]_](https://github.com/dapr/components-contrib/issues/286)
> Add TLS support for bindings.redis

- state/zookeeper/zk.go
- state/zookeeper/zk_test.go
- updated implementation to return an empty response with non-existent keys
- updated corresponding test cases
issue #264 
> Zookeeper state store: don't treat non-existent keys as errors

- bindings/azure/servicebusqueues/servicebusqueues.go
- bindings/azure/servicebusqueues/servicebusqueues_integration_test.go
- bindings/azure/servicebusqueues/servicebusqueues_test.go
- bindings/azure/storagequeues/storagequeues.go
- bindings/azure/storagequeues/storagequeues_test.go
- bindings/rabbitmq/rabbitmq.go
- bindings/rabbitmq/rabbitmq_integration_test.go
- bindings/rabbitmq/rabbitmq_test.go
- bindings/utils.go
- pubsub/rabbitmq/rabbitmq_test.go
Add time to live when writing to RabbitMQ, Azure Service Bus and Azure Storage Queue bindings. Time to live is defined in seconds. It can be defined in two places:
-  binding definition, setting the `ttl`  property (in RabbitMQ and Service Bus sets the default time to live in the queue definition)
- when writing to the binding, setting the property `ttl` in the request metadata (overrides the binding definition if one was set)
I have added integration tests for RabbitMQ and Service Bus. They are skipped unless specific environment variables are set. It would be great to enable them at some point. Please let me know if I can assist some how.
#126 (Sub-item "As a publisher I want to define message TTL in order to expire stale content")
Please make sure you've completed the relevant tasks …
> Add message time to live in RabbitMQ, Azure Service Bus/Storage Queue bindings

- state/sqlserver/sqlserver_integration_test.go
When asserting that a user does not exist in the state store, changed an ```assert.NotNil``` statement to ```assert.Nil```
Please reference the issue this PR will close: #324
> Fixed SQL Server state store integration tests (#324)

- middleware/http/nethttpadaptor/nethttpadaptor.go
This change copies the uservalues from the original request context into the new request.
Please reference the issue this PR will close: #332 
> Add support for UserValues in Nethttpadaptor

- pubsub/azure/servicebus/metadata.go
- pubsub/azure/servicebus/servicebus.go
- pubsub/azure/servicebus/servicebus_test.go
Rather than just applying concurrency controls to the message handlers, I've update it to handle it in the receiver as well. This way dapr doesn't pull a message it cannot immediately process.
More details in the original [issue](https://github.com/dapr/dapr/issues/1526).
I've smoke tested this locally, I'd like to check this resolves @programaka issue before merging.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1526
> Fix issue with ASB pubsub throttling

- authentication/aws/aws.go
- bindings/aws/dynamodb/dynamodb.go
- bindings/aws/dynamodb/dynamodb_test.go
- bindings/aws/kinesis/kinesis.go
- bindings/aws/kinesis/kinesis_test.go
- bindings/aws/s3/s3.go
- bindings/aws/s3/s3_test.go
- bindings/aws/sns/sns.go
- bindings/aws/sns/sns_test.go
- bindings/aws/sqs/sqs.go
- bindings/aws/sqs/sqs_test.go
- pubsub/aws/snssqs/snssqs.go
- secretstores/aws/secretmanager/secretmanager.go
- secretstores/aws/secretmanager/secretmanager_test.go
- state/aws/dynamodb/dynamodb.go
This PR builds on the changes made in #340 , using the shared credentials resolver package for all aws clients. I also discovered that the `sqssns` pubsub package implements an "endpoint" parameter, so I added that to the auth abstraction package, and implemented it in all aws packages. This is especially powerful when developing locally against a local DynamoDB container instead of an actual DynamoDB Table running at AWS - should allow some new and interesting integration test scenarios aswell, using libraries such as https://github.com/spulec/moto to mock various aws services.
The only package I'm unsure of is the `sqssns` pubsub package. It uses different param names than all other aws-related packages in dapr, and the best would probably be to get everything aligned now that the …
> Use shared aws auth package

- .github/workflows/components-contrib.yml
- .golangci.yml
- go.mod
- middleware/http/nethttpadaptor/nethttpadaptor_test.go
- middleware/http/oauth2/oauth2_middleware.go
- pubsub/natsstreaming/natsstreaming.go
- pubsub/rabbitmq/rabbitmq.go
- pubsub/rabbitmq/rabbitmq_test.go
- secretstores/azure/keyvault/authutils_test.go
- secretstores/get_secret_request.go
- servicediscovery/kubernetes/kubernetes_test.go
- state/aerospike/aerospike.go
- state/aws/dynamodb/dynamodb.go
- state/azure/cosmosdb/cosmosdb.go
- state/azure/tablestorage/tablestorage.go
- state/cassandra/cassandra.go
- state/cloudstate/cloudstate_crdt.go
- state/couchbase/couchbase.go
- state/etcd/etcd.go
- state/gcp/firestore/firestore.go
- state/hashicorp/consul/consul.go
- state/hazelcast/hazelcast.go
- state/memcached/memcached.go
- state/mongodb/mongodb.go
- state/redis/redis.go
- state/sqlserver/sqlserver.go
- state/zookeeper/zk.go
Upgrade go version to 1.14 
Upgrade linter version to 1.26.0
[Linters](https://golangci-lint.run/usage/linters/)
For now removed following linters:
[godot](https://github.com/tetafro/godot) --- 90+ files being touched 
[goerr113](https://github.com/Djarvur/go-err113) --- touches so many files (should probably be done as a separate work)
[testpackage](https://github.com/maratori/testpackage) --- changing package of `_test` files might break code 
Some Changes: 
* fixed int32 parsing for ETag
* fixed implicit reference in ranged for loop to indexed, base references 
* fixed a WriteFile permission in a test file to 600 
#334 
> Upgrade go version to 1.14.3 and linter version to 1.26.0

- servicediscovery/mdns/mdns.go
- servicediscovery/requests.go
- servicediscovery/servicediscovery.go
Cancel context when service is found. 
The current implementation is always waiting for 1 second even if service is discovered. So we can always see 1 second delay for service invocation. This will cancel earlier to fix this issue when service is discovered.
Before (using helloworld python app)
```
ℹ️  Updating metadata for app command: python3 app.py
✅  You're up and running! Both Dapr and your app logs will appear here.
== APP == Time elapsed: 1.0576
== APP == Time elapsed: 1.0166
```
After this fix
```
== APP == Time elapsed: 0.0151
ℹ️  Updating metadata for app command: python3 app.py
✅  You're up and running! Both Dapr and your app logs will appear here.
== APP == Time elapsed: 0.0085
== APP == Time elapsed: 0.0097
== APP == Time elapsed: 0.0097
== APP == Time elapsed: 0.0100
== APP …
```
> Cancel context when service is discovered

- secretstores/local/localsecretstore.go
- secretstores/local/localsecretstore_test.go
Refactored JSONSecretStore into LocalSecretStore and removed the use of the DAPR_ENABLE_JSON_SECRET_STORE environment variable as suggested here: dapr/dapr#1633
Please reference the issue this PR will close: #360
> Rename JSONSecretStore into LocalSecretStore and remove DAPR_ENABLE_JSON_SECRET_STORE envvar

- pubsub/pulsar/pulsar.go
the enabletls does the opposite of what the config suggests
Closes https://github.com/dapr/components-contrib/issues/374
> Make enableTLS work correctly

- bindings/azure/eventhubs/eventhubs.go
Handle errors in AzureEventHubs.Read.
While following [this article](https://dev.to/azure/learn-how-to-use-azure-event-hubs-with-the-dapr-framework-333h) on how to use dapr with Azure EventHubs, I was facing the problem that the `storageAccountKey` was in the wrong format (only base64 value was required, but I was using this format instead `DefaultEndpointsProtocol=https;AccountName=daprazure;AccountKey=<the key which was needed as base64>==;EndpointSuffix=core.windows.net`.
The problem is that the error was not visible in the logs of the dapr sidecar.
Now they are:
```
time="2020-06-26T09:05:12.490481193Z" level=error msg="error reading from input binding eventhubs-input: illegal base64 data at input byte 24" app_id=goapp-input-bindingapp instance=goapp-input-binding-7cf48cfc46-jhvsj …
```
> Handle errors in AzureEventHubs.Read

- pubsub/envelope.go
- pubsub/envelope_test.go
This fixes the issue with string array not being parsed as valid JSON and adds unit tests based on what's tested in end to end tests to catch early
> Fizes JSON array envelope parsing, adds unit tests

- pubsub/envelope.go
- pubsub/envelope_test.go
As referenced in https://github.com/dapr/dapr/pull/1803
This change adds the topic to the Cloud Event envelope at publish time.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1786 
> Add topic to cloud events envelope

- state/azure/cosmosdb/cosmosdb.go
- state/mongodb/mongodb.go
- state/postgresql/postgresql.go
- state/postgresql/postgresql_integration_test.go
- state/postgresql/postgresql_test.go
- state/redis/redis.go
- state/requests.go
- state/sqlserver/sqlserver.go
- state/sqlserver/sqlserver_integration_test.go
- state/transactional_store.go
Introduce metadata for transactional request. This metadata is used for custom options for transactional operations.
https://github.com/dapr/dapr/issues/1736
> Add metadata property to TransactionalRequest

- pubsub/mqtt/metadata.go
- pubsub/mqtt/mqtt.go
- pubsub/mqtt/mqtt_test.go
This PR aims at adding support of mqtt over TLS.
Additional metadata added to accept required TLS parameters are:
```
caCert     string
clientCert string
clientKey  string
```
**NOTE**: recommended way to provide certificate and key details is by using k8s secrets.
#357 
> Add pubsub support for mqtt over TLS

- pubsub/rabbitmq/metadata.go
- pubsub/rabbitmq/metadata_test.go
- pubsub/rabbitmq/rabbitmq.go
This PR does the following:
1. Adhere to Dapr's pub/sub consumer group guarantees for allowing a scale out of multiple consumers within a group, by setting exclusive to `false`.
2. The implementation confused durability with exclusivity. This PR enables durability by default for Dapr's at-least-once delivery guarantees.
> Fix consumer exclusivity

- secretstores/local/env/envstore.go
- secretstores/local/env/envstore_test.go
- secretstores/local/file/filestore.go
- secretstores/local/file/filestore_test.go
Refactors local secrets (used for development) into `local.file` and adds `local.env` implementation. 
[dapr issue #1961](https://github.com/dapr/dapr/issues/1961)
> refactors local secret, adds env var imp dapr issue #1961

- pubsub/mqtt/mqtt.go
- Listen on multiple topics when those are provided for subscription.
- Improve the current logic to use dedicated function from paho client.
- Reset synchronisation (close and reset existing subscription to broker) when listening to multiple topics.
> Improve mqtt pubsub for multiple topics

- state/azure/cosmosdb/cosmosdb.go
- state/memcached/memcached.go
- state/postgresql/postgresdbaccess.go
- state/redis/redis.go
- state/sqlserver/sqlserver.go
- state/utils/utils.go
Found an issue for Transaction API via Java Integration Tests. 
When the state is stored via an **upsert** call made and the got back via the normal getState API call, it can be observed that there is an extra Json Marshal happening in the code. 
Example:
```json
data: "\"{\\\"propertyA\\\":\\\"data in property A\\\",\\\"propertyB\\\":\\\"data in property B\\\"}\""
```
Instead of 
```json
data: "{\"propertyA\":\"data in property A\",\"propertyB\":\"data in property B\"}"
````
The second output is what we have when we have a normal save and get state call done via Dapr. 
The code change here, checks if the incoming request value is a byte array or not and then properly serializes the value. 
We strive to have all PR being opened based on an issue, where the problem or feature have been …
> Properly handle serialization deserizliation for redis transaction api.

- docs/developing-component.md
Fix Dapr home bin directory in dev doc
n/a
> Fix Dapr home bin directory in dev doc

- bindings/postgres/postgres.go
- bindings/postgres/postgres_test.go
The initial PR was missing error context on SQL format error. 
Integration tests are grouped into operation type now
> postgres binding w/ better tests, cleaner errors

- pubsub/requests.go
This adds optional metadata for both pub/sub implementations to be able to send additional data and for consumers to pass in additional context.
> Add metadata to pubsub message

- state/redis/redis.go
- state/redis/redis_test.go
Fixing redis delete without etag on trx.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2126
> Fixing bug where trx del in redis fails without etag.

- pubsub/aws/snssqs/snssqs.go
- pubsub/azure/servicebus/servicebus.go
- pubsub/gcp/pubsub/pubsub.go
- pubsub/hazelcast/hazelcast.go
- pubsub/kafka/kafka.go
- pubsub/mqtt/mqtt.go
- pubsub/nats/nats.go
- pubsub/natsstreaming/natsstreaming.go
- pubsub/pubsub.go
- pubsub/pulsar/pulsar.go
- pubsub/rabbitmq/rabbitmq.go
- pubsub/redis/redis.go
As Pub/Sub components encapsulate the lifecycle management of their subscriptions, it's beneficial to provide consumers the ability to explicitly close an implementation and thereby all of it's underlying connections and/or subscriptions.
This issue participates in closing https://github.com/dapr/dapr/issues/1172.
> Add close method to pub/sub

- secretstores/azure/keyvault/keyvault.go
Azure Key Vault Secret Store now reads the secret version from metadata, if provided
Please reference the issue this PR will close: #522
> Key Vault Secret Store now reads the secret version from metadata (Fixing #522)

- bindings/aws/sqs/sqs.go
the sqs binding didn't correctly initialize its logger, which caused the application to crash on log writes. This fixes that.
Please reference the issue this PR will close: #529
> properly initialize logger in bindings/sqs

- authentication/aws/aws.go
- bindings/aws/dynamodb/dynamodb.go
- bindings/aws/dynamodb/dynamodb_test.go
- bindings/aws/kinesis/kinesis.go
- bindings/aws/kinesis/kinesis_test.go
- bindings/aws/s3/s3.go
- bindings/aws/s3/s3_test.go
- bindings/aws/sns/sns.go
- bindings/aws/sns/sns_test.go
- bindings/aws/sqs/sqs.go
- bindings/aws/sqs/sqs_test.go
- pubsub/aws/snssqs/snssqs.go
- pubsub/aws/snssqs/snssqs_test.go
- secretstores/aws/secretmanager/secretmanager.go
- state/aws/dynamodb/dynamodb.go
- Implemented support for AWS session token (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) in the shared `authentication/aws` function
- Cleaned up the sns/sqs pubsub attributes so that its configuration attribute set matches the rest of the aws resources (created an alias lookup thing so that the old attribute names still work, added tests for that)
As far as I can see, the existing sns/sqs pubsub binding simply cannot have worked - the way it mixes account id and access key ist just... strange. In any case, this PR attempts to fix all of that so that all aws-related things can be configured in the same way. I'm not sure if the aliasing is really needed, as I strongly doubt anyone using it in its current state, but I figure it never hurts to be …
> Various AWS improvements

- pubsub/requests.go
Added a metadata field to a SubscribeRequest to allow additional data to be provided to the pubsub component.
Please reference the issue this PR will close: #[Dapr/2379](https://github.com/dapr/dapr/issues/2379)
> Add metadata to SubscribeRequest

- secretstores/local/file/filestore.go
- secretstores/local/file/filestore_test.go
Fixing file secretstore to support custom separator.
Please reference the issue this PR will close: #550
> Fixing file secretstore to support custom separator.

- pubsub/rabbitmq/metadata.go
- pubsub/rabbitmq/metadata_test.go
- pubsub/rabbitmq/rabbitmq.go
- pubsub/rabbitmq/rabbitmq_test.go
Adds support for the "prefetch" parameter in rabbitmq, allowing clients to only prefetch a portion of the available messages, instead of all of them.
I can do a separate PR to update rabbitmq docs according to https://v1-rc2.docs.dapr.io/operations/components/component-schema/
I'm not sure if I should just switch to intsince that's what the Qos function expects natively. I figured I'd use the same numeric format as other parameters in the same module. Happy to change that.
I'm also not sure if it should default to 0 (which disables the prefetch functionality) or 1 (which IMHO is the safe and "correct" setting). 
https://github.com/dapr/components-contrib/issues/560
> Add support for prefetch

- secretstores/kubernetes/kubernetes.go
- secretstores/kubernetes/kubernetes_test.go
Fallback to NAMESPACE env for get secret on K8s.
Please reference the issue this PR will close: #563 
> Fallback to NAMESPACE env for get secret on K8s.

- pubsub/envelope.go
- pubsub/envelope_test.go
This PR replaces the body check to determine if a payload is a CloudEvent or not by relying on `daprd` to make the decision based on a user supplied information, either via a header on HTTP or a special field in proto.
Determining a cloud event by inspecting the body has the following drawbacks:
1. Performance hit in terms of CPU
2. The method to determine if a Cloud Event is compliant to the spec will need to be maintained long term to keep up with any changes to the spec
In addition, the PR corrects a long time error in treating the `subject` field as a way to store the trace ID.
Based on this change, trace IDs will be saved in a `daprtraceid` extension field.
A method has been added to add the trace field to existing CE json based payloads.
> Replace content cloud event check, add settraceid

- pubsub/envelope.go
- pubsub/envelope_test.go
This PR does a small refactor that introduces a new method that returns a Cloud Event map based on an existing Cloud Event.
> Add new cloudevents creation method

- pubsub/concurrency.go
- pubsub/concurrency_test.go
- pubsub/rabbitmq/metadata.go
- pubsub/rabbitmq/metadata_test.go
- pubsub/rabbitmq/rabbitmq.go
This PR moves the concurrency logic to the correct place due to how the RabbitMQ Golang driver operates over channels.
Fixes PR #575
> Fix RabbitMQ concurrency

- state/aerospike/aerospike.go
- state/azure/blobstorage/blobstorage.go
- state/azure/cosmosdb/cosmosdb.go
- state/azure/tablestorage/tablestorage.go
- state/couchbase/couchbase.go
- state/errors.go
- state/errors_test.go
- state/postgresql/postgresdbaccess.go
- state/redis/redis.go
- state/sqlserver/sqlserver.go
- state/zookeeper/zk.go
This PR consolidates error handling for possible etag mismach and invalid etags across all state stores.
Partially closes https://github.com/dapr/dapr/issues/2619
> Treat etag errors across all state stores

- state/aerospike/aerospike.go
- state/azure/cosmosdb/cosmosdb.go
- state/azure/tablestorage/tablestorage.go
This PR adds a few nil error checks for state stores. A follow up for https://github.com/dapr/components-contrib/pull/579
> Add missing error checks for etag errors

- bindings/rabbitmq/rabbitmq.go
- bindings/rabbitmq/rabbitmq_integration_test.go
- bindings/rabbitmq/rabbitmq_test.go
Adding the Exclusive flag to the RabbitMQ binding to allow creation of exclusive queues;
Please reference the issue this PR will close: #_577_
* [X ] Code compiles correctly
* [X ] Created/updated tests
> Added Exclusive Flag to RabbitMQ queues

- state/aerospike/aerospike.go
- state/azure/blobstorage/blobstorage.go
- state/azure/cosmosdb/cosmosdb.go
- state/azure/tablestorage/tablestorage.go
- state/cloudstate/cloudstate_crdt.go
- state/couchbase/couchbase.go
- state/postgresql/postgresdbaccess.go
- state/postgresql/postgresql_integration_test.go
- state/redis/redis.go
- state/redis/redis_test.go
- state/requests.go
- state/rethinkdb/rethinkdb.go
- state/rethinkdb/rethinkdb_test.go
- state/sqlserver/sqlserver.go
- state/sqlserver/sqlserver_integration_test.go
- state/zookeeper/zk.go
- state/zookeeper/zk_test.go
This PR is the first of two PRs to solve https://github.com/dapr/dapr/issues/2320.
This PR provides a distinction (where needed) between a missing etag and a blank etag.
> Provide distinction between missing and empty etags

- pubsub/mqtt/mqtt.go
- pubsub/mqtt/mqtt_test.go
Remove useless random ID logic for mqtt's consumerID.
Related to: #589 
> Remove useless random ID logic for mqtt's consumerID.

- secretstores/Readme.md
- secretstores/aws/secretmanager/secretmanager.go
- secretstores/aws/secretmanager/secretmanager_integ_test.go
- secretstores/azure/keyvault/keyvault.go
- secretstores/hashicorp/vault/vault.go
- secretstores/kubernetes/kubernetes.go
- secretstores/local/env/envstore.go
- secretstores/local/env/envstore_test.go
- secretstores/local/file/filestore.go
- secretstores/local/file/filestore_test.go
- secretstores/responses.go
- secretstores/secret_store.go
`BulkGetSecret` method now returns a `map[string]map[string]string`
Please reference the issue this PR will close: #590
> Fixed #590

- secretstores/gcp/secretmanager/secretmanager.go
- secretstores/gcp/secretmanager/secretmanager_test.go
BulkGetSecret method now returns a map[string]map[string]string
Please reference the issue this PR will close: #590
> Updated GCP SecretManager BulkGetSecret #590

- tests/config/bindings/output_tests.yml
- tests/config/bindings/redis/bindings.yml
- tests/conformance/bindings/output/output_bindings.go
- tests/conformance/common.go
- tests/conformance/output_bindings_test.go
This commit adds new conformance tests for output binding components.
Redis is being used as a the introductory binding example.
Closes: #409 
This change is currently built atop @mukundansundar's PR for the template and is subject to change based off of the feedback received there. Once that is committed, this PR will represent a single commit and no longer be a draft.
https://github.com/dapr/components-contrib/pull/586
> Add conformance tests for output bindings

- .github/workflows/conformance.yml
- Makefile
- tests/config/bindings/output_tests.yml
- tests/conformance/README.md
- tests/conformance/bindings/output/output_bindings.go
- tests/conformance/common.go
- tests/conformance/common_test.go
- tests/conformance/output_bindings_test.go
- tests/conformance/pubsub/pubsub.go
- tests/conformance/pubsub_test.go
- tests/conformance/secretstores/secretstores.go
- tests/conformance/secretstores_test.go
- tests/conformance/state/state.go
- tests/conformance/state_test.go
- tests/conformance/utils/utils.go
- tests/conformance/utils/utils_test.go
Fix running output bindings with errors.
Refactor tests to make it simpler for go test filtering.
Generate UUID dynamically when configured to do so.
Add get operation for blobstorage binding.
Fail particular tests if correct environment variables are not set.
```
$ make conf-tests
=== RUN   TestDecodeYaml
=== RUN   TestDecodeYaml/valid_yaml
=== RUN   TestDecodeYaml/invalid_yaml
17:23:24 W common.go:157> error parsing string as yaml yaml: line 2: did not find expected key
--- PASS: TestDecodeYaml (0.00s)
--- PASS: TestDecodeYaml/valid_yaml (0.00s)
--- PASS: TestDecodeYaml/invalid_yaml (0.00s)
=== RUN   TestIsYaml
--- PASS: TestIsYaml (0.00s)
=== RUN   TestLookUpEnv
--- PASS: TestLookUpEnv (0.00s)
=== RUN   TestConvertMetadataToProperties
=== RUN …
```
> Refactor conformance tests

- docs/developing-component.md
Adding golangci-lint as a prerequisite otherwise the make lint command will not work.
Description
One of the steps to confirm your machine is ready to contribute a component is to type
make lint
However, that will fail unless you install golangci-lint.
Issue reference
Addresses part of #2529
> Add golangci-lint as prerequisite

- contenttype/utils.go
- pubsub/envelope.go
- pubsub/envelope_test.go
Added base64 encoding for binary data types
Added binary data type detection based on mime type.
Base 64 encoded binary data.
This will not fix any issue but help in https://github.com/dapr/dapr/issues/2612
> Added binary data type detection

- pubsub/azure/servicebus/servicebus.go
Reported performance benchmarks have shown that a new topic creation on every Publish event is costly.
This PR introduces on-demand creation of topics and removes a redundant Close function after every Publish operation.
> Fix service bus new topic creation

- pubsub/envelope.go
- pubsub/envelope_test.go
Fixes bug where a default cloud events envelope would be produced with a missing subject field.
> Fix missing subject

- tests/conformance/bindings/bindings.go
- tests/conformance/utils/utils.go
The http server required for the http binding tests was not up
before the tests began to execute. This change adds a channel to
allow the server to block until it's ready.
No issue, just a fix.
> Use a channel to block server start before tests

- state/aws/dynamodb/dynamodb.go
- state/aws/dynamodb/dynamodb_test.go
Dont fail if aws access key/secret vars are empty. This is part of the "implicit aws auth flow" which we changed a way back. Dynamodb had some hard-coded checks that this PR removes.
Looks like we simply don't have any documentation for the dymamodb state store yet (https://v1-rc2.docs.dapr.io/operations/components/setup-state-store/supported-state-stores/) so I can try and get that in after this is merged (marking docs as "done" in the list below, since there's no doc updates blocking this PR)
See also https://github.com/dapr/dapr/issues/2469
Please reference the issue this PR will close: #647
> State:Dynamodb - Dont require access key/secret

- docs/developing-component.md
This PR adds documentation for when and how to create Version 2 of a component and beyond.
Resolves #526
PR for adding component versioning support is dapr/dapr#2757
> Added documentation on versioning Dapr components

- secretstores/azure/keyvault/keyvault.go
Fix Azure KeyVault secretstore BulkGet URI parsing of the GetSecretsComplete response to make it works with URI of form `{vaultURI}/secrets/{itemID}` in the GetSecretsComplete response.
Please reference the issue this PR will close: #655 
> Fix Azure KeyVault secretstore BulkGet URI parsing of the GetSecretsComplete response

- .github/workflows/conformance.yml
- bindings/http/http.go
- bindings/http/http_test.go
- go.mod
- tests/config/bindings/http/bindings.yml
- tests/config/bindings/tests.yml
- tests/config/state/tests.yml
- tests/conformance/bindings/bindings.go
- tests/conformance/common.go
Improving the versatility of the HTTP output binding. Removed the `Read` method since it is not an input binding.
Related to dapr/docs#153. Will update the docs for this binding as a follow up.
> Improving the versatility of the HTTP output binding

- .github/workflows/conformance.yml
Change conformance test job name to avoid having env var / secret names in the title. Even though these are visible in the workflow file already, it's nice not to have a super long job name with a long list of env vars.
> Change conformance test job name to avoid having env var / secret names in the title

- go.mod
As discussed in #649, an issue in the azure-service-bus-go sdk meant that credentials would eventually expire for the lock renewal connection. This was original raised by @XavierGeerinck on discord. We've detected the issue in the sdk as discussed in [this thread](https://github.com/Azure/azure-service-bus-go/issues/155). This has been fixed in `v0.10.10` so this PR bumps the version of the sdk we use from `v0.10.6` to `v0.10.10`.
I'm currently running soak tests to validate the fix and will publish the PR once confirmed.
Please reference the issue this PR will close: #649 
Please make sure you've completed the relevant tasks for this PR, out of the following …
> Fix Azure Service Bus connection issue

- .github/workflows/conformance.yml
- tests/config/pubsub/tests.yml
Setting `pipefail` option in Github workflow and purposefully making the Redis test fail to verify that the build fails (as expected)
It is expected that this build will fail initially. ~~If it does not, **PLEASE DO NOT MERGE**~~. A comment will follow when the bug is fixed.
Closes #714
> Make failing conformance tests also fail the build

- tests/conformance/pubsub/pubsub.go
- tests/conformance/utils/utils.go
Added a simple check to ignore already processed messages in case the pubsub broker redelivers the messages while retries are taking place. Without this check, the test can fail the in-order processing check.
The following log shows the current issue:
```
time="2021-02-26T02:20:41.762829894Z" level=debug msg="Processing MQTT message testTopic/7" instance=fv-az177-944 scope=testLogger type=log ver=edge
time="2021-02-26T02:20:42.763089578Z" level=error msg="Error processing MQTT message: testTopic/7. Retrying..." instance=fv-az177-944 scope=testLogger type=log ver=edge
time="2021-02-26T02:20:47.763361684Z" level=debug msg="Processing MQTT message testTopic/7" instance=fv-az177-944 scope=testLogger type=log ver=edge
time="2021-02-26T02:20:47.763461085Z" level=info msg="Successfully processed …
```
> Conformance Test: PubSub - Ignore already processed messages

- state/mongodb/mongodb.go
- tests/config/state/tests.yml
- tests/conformance/state/state.go
ETags are used to enable concurrency guarantees and are part of the
statestore specification. Not all stores need to use them, however
if the store chooses to, it should be part of the certification
process. This commit adds a simple ETag test scenario that verifies
the basic behaviors of ETags.
https://github.com/dapr/components-contrib/issues/711
Closes: #711 
> Add ETag operation to statestore conformance test

- .github/infrastructure/docker-compose-hazelcast.yml
- .github/workflows/conformance.yml
- pubsub/hazelcast/hazelcast.go
- pubsub/hazelcast/metadata.go
- tests/config/pubsub/hazelcast/pubsub.yml
- tests/config/pubsub/tests.yml
- tests/conformance/common.go
This PR adds the Hazelcast pubsub component to the conformance tests and fixes some issues to make it pass the tests.
The setting `backOffMaxRetries` was added to allow for a fixed number of retries or setting it to `-1` for unlimited retries. The default value is `0` which disables retries. A Docker Compose for Hazelcast was created.
Resolves #697 #723 
Docs issue: dapr/docs/issues/1270
> Added Hazelcast to conformance tests and retry to prevent message loss

- state/aerospike/aerospike.go
- state/azure/blobstorage/blobstorage.go
- state/azure/cosmosdb/cosmosdb.go
- state/azure/tablestorage/tablestorage.go
- state/couchbase/couchbase.go
- state/hashicorp/consul/consul.go
- state/mongodb/mongodb.go
- state/mysql/mysql.go
- state/mysql/mysql_integration_test.go
- state/postgresql/postgresdbaccess.go
- state/postgresql/postgresql_integration_test.go
- state/redis/redis.go
- state/redis/redis_test.go
- state/responses.go
- state/rethinkdb/rethinkdb.go
- state/sqlserver/sqlserver.go
- state/sqlserver/sqlserver_integration_test.go
- state/zookeeper/zk.go
- state/zookeeper/zk_test.go
- tests/conformance/state/state.go
Per #731, this PR allows the ETag in `state.GetResponse` and `state.BulkGetResponse` to be returned as a `nil`. This is to make these structs consistent with `state.SetRequest` and `state.DeleteRequest` and to be able to copy the `ETag` field as-is when going between read and write operations.
Since there are not e2e tests for each of the changed state components, there is no way to verify these changes without a significant time investment to test test manually. These changes are fairly simple so I did not go that route but wanted to mention the risk and recommend a high level of scrutiny when reviewing the code.
**If this PR is merged, an issue in `dapr/dapr` should be created to adjust to the `ETag` field being `*string` instead of `string`.**
Resolves #731
> Make state.GetResponse ETag to a *string

- .github/infrastructure/docker-compose-rabbitmq.yml
- .github/workflows/conformance.yml
- pubsub/rabbitmq/metadata.go
- pubsub/rabbitmq/metadata_test.go
- pubsub/rabbitmq/rabbitmq.go
- pubsub/rabbitmq/rabbitmq_test.go
- tests/config/pubsub/rabbitmq/pubsub.yml
- tests/config/pubsub/tests.yml
- tests/conformance/common.go
This PR adds RabbitMQ to the conformance tests.
I also made two small tweaks to the component itself:
* Using the Delivery API to either Ack or Nack a message
* Made consumerID only required when `Subscribe` is called so that an app can publish only
I will be adding retries support in a separate PR.
Resolves #694
> Adding RabbitMQ to the conformance tests

- pubsub/redis/redis.go
Redis component close function called  `r.client.Close()` .
The pollNewMessagesLoop loop run in a goroutine use client to read from redis which will lead to an error: `error retrieving pending Redis messages: redis: client is closed`. 
When err occured this loop will continue. The context closed check will never have chance to run.
```
if err != nil {
r.logger.Errorf("redis streams: error reading from stream %s: %s", stream, err)
continue
}
// below will have no chance to run if client is closed
```
We need move the check to the top of this loop.
> fix pubsub redis close bug

- pubsub/gcp/pubsub/metadata.go
- pubsub/gcp/pubsub/pubsub.go
- pubsub/gcp/pubsub/pubsub_test.go
- Make GCP pubsub support implicit credentials, in addition to explicit
- Clean up GCP pubsub metadata so that it lines up with other dapr pubsubs (separate struct for the gcp auth json stuff, it seemed a bit cleaner)
- make project id (project where subscription/topic should live) separate from "identity project id" (where the service account lives)
> refactor GCP pubsub

- state/azure/cosmosdb/cosmosdb.go
- state/azure/cosmosdb/cosmosdb_test.go
Fix cosmosdb state store to handle content-type, with JSON as default.
Please reference the issue this PR will close: #745 
> Fix cosmosdb state store to handle content-type, with JSON as default.

- pubsub/redis/metadata.go
- pubsub/redis/redis.go
- pubsub/redis/redis_test.go
add some config that can be set from metadata for redis client.
RELEASE NOTES: Added commonly used Redis client settings
> add some redis client config that may be commonly used

- .github/workflows/conformance.yml
- bindings/mqtt/metadata.go
- bindings/mqtt/mqtt.go
- bindings/mqtt/mqtt_test.go
- pubsub/mqtt/mqtt.go
- tests/config/bindings/mqtt/emqx/bindings.yml
- tests/config/bindings/mqtt/mosquitto/bindings.yml
- tests/config/bindings/mqtt/vernemq/bindings.yml
- tests/config/bindings/tests.yml
- tests/conformance/bindings/bindings.go
- tests/conformance/common.go
This PR improve the MQTT binding to use the same options/code as the MQTT pubsub (TLS, qos, ...)
> feat: change binding mqtt options to the same as pubsub

- state/redis/redis.go
This PR fixes password configuration of Redis sentinel state component.
As written in #756, `redisPassword` metadata field did not work on Redis sentinel state.
In this commit, `redisPassword` is passed to FailOverClient as Redis master's password.
Please reference the issue this PR will close: #756
> fix password config for redis sentinel state

- pubsub/azure/servicebus/subscription.go
For the the Azure Service Bus pubsub component, the log statement when closing was changed from `Errorf` to `Warnf`. The reason being that the connection is closing and the error will not cause any side effects. Mainly, we don't want to have this trigger alerts in monitoring tools.
Resolves #809
> Azure Service Bus: Changed log level of error on close to info

- .github/workflows/components-contrib.yml
- .github/workflows/conformance.yml
Increased the timeout for running conformance tests. This error is periodically causing the Github actions workflow to fail.
The default `go test` timeout is `10m`. This PR bumps that up to `15m`. Also added a `go mod download` as a step before the `go test` command so that downloading dependencies does not count against the testing timeout.
At some point we should look at where all the time is being spent.
> Increasing overall test timeout to allow for conformance tests to run

- .github/workflows/components-contrib.yml
- tests/conformance/pubsub/pubsub.go
Lots of go lint errors are showing up in job runs since the `Download Go dependencies` step was added to `.github/workflows/components-contrib.yml`. Hoping removing it resolves the errors.
Also moved the timer in the pubsub conformance tests to a single variable used over each message iteration. Not 100% confident it will resolve the periodic conformance test timeouts but it is probably how the timer should work anyway.
> Removing the Download Go Dependencies step from the build workflow

- docs/developing-component.md
Fixes the shell command in step 6 that backs up your current `daprd` binary under **Validating with Dapr core** in `docs/developing-component.md`
> Fixing backup current daprd command

- pubsub/redis/redis.go
Allow XGroupRead operation to timeout periodically so we will know when a connection has disappeared. There is an existing redis parameter to read timeout, we can use it for our XGroupRead interval.
Please reference the issue this PR will close: #852
> Do not block indefinitely on XGroupRead for redis subscriber

- pubsub/redis/metadata.go
Just a comment change to reflect that the redis/v8 API defaults to 3 retries. This is the desired behavior, since prior to v1.1, we were just hardcoding a value of 3 for this parameter anyway.
> Update redis metadata comments to reflect the new maxRetry default from v8

- go.mod
- go.sum
- state/aerospike/aerospike.go
The Aerospike library was using microsecond precision sleep in a loop in its module init() function for random number generation. Windows, as it turns out, doesn't have microsecond precision sleep, so it was sleeping for for a total of nearly 8s. This is happening any time the daprd binary is invoked on windows. This has been fixed upstream, so the solution is to migrate to a newer version of this library.
With aerospike v2.7.0:
```
$ time dapr --version
CLI version: edge
Runtime version: 1.1.2
real    0m8.827s
user    0m0.000s
sys     0m0.015s
```
With aerospike v4.5.0:
```
$ time dapr --version
CLI version: edge
Runtime version: edge
real    0m0.531s
user    0m0.000s
sys     0m0.046s
```
We strive to have all PR being opened based on an issue, where the problem or feature have been …
> Update Aerospike to v4.5.0

- pubsub/azure/servicebus/subscription.go
Signed-off-by: Long Dai <long0dai@foxmail.com>
As [doc](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-troubleshoot#link-is-closed) said,  the error will not cause any side effects. Mainly, we don't want to have this trigger alerts in monitoring tools.
Please reference the issue this PR will close: #984
> Azure Service Bus: ignore amqp:link:detach-forced error

- .github/workflows/conformance.yml
Change the `env.AZURE_KEYVAULT` variable in conformance.yml to a GitHub secret so that the conformance tests workflow can be executed in private forks without having to edit the workflow definitions.
This replicates the pattern used in dapr/dapr for per repo parameters such as `DOCKER_TEST_REGISTRY` for the dapr tests.
> **⚠ This change requires a maintainer to add the `AZURE_KEYVAULT=dapr-conf-tests` secret to the dapr/components-contrib repo.**
Part of addressing: #1000
> Convert AZURE_KEYVAULT in conformance.yml to a GitHub secret

- bindings/apns/authorization_builder.go
- bindings/azure/signalr/signalr.go
- go.mod
- go.sum
Signed-off-by: Long Dai <long0dai@foxmail.com>
switch to golang-jwt
Please reference the issue this PR will close: #989
> switch to golang-jwt

- bindings/smtp/smtp.go
If a request to invoke the SMTP binding was missing the `emailFrom` property, it would throw an slightly misleading error saying the `fromEmail` was missing.  
> fix typo in error message in case of missing property

- bindings/smtp/smtp.go
- pubsub/azure/servicebus/servicebus.go
- pubsub/azure/servicebus/subscription.go
- pubsub/nats/metadata.go
- pubsub/nats/nats.go
- pubsub/nats/nats_test.go
Reverts dapr/components-contrib#1030
> Revert "Fixing the handling of detach errors"

- pubsub/azure/servicebus/servicebus.go
- pubsub/azure/servicebus/subscription.go
This fixes the handling of `amqp:link:detach-forced` errors from Azure Service Bus. While the log message can be suppressed, this type of error should not be ignored because it prevents the component from reconnecting. Reconnecting is the desired behavior when the link is force detached.
Resolves dapr/dapr#3468
> Azure Service Bus: Fixing the handling of forced detach errors

- .github/infrastructure/conformance/azure/conf-test-azure-eventhubs.bicep
- .github/infrastructure/conformance/azure/conf-test-azure.bicep
- .github/infrastructure/conformance/azure/setup-azure-conf-test.sh
- pubsub/azure/eventhubs/eventhubs.go
- tests/config/bindings/azure/eventhubs/bindings.yml
- tests/config/bindings/tests.yml
- tests/config/pubsub/azure/eventhubs/pubsub.yml
- tests/config/pubsub/tests.yml
- tests/conformance/common.go
- Update automation for setting up Event Hubs resources in Azure for conformance testing
- Add conformance tests for Event Hubs pubsub and bindings components
- Add retry & backoff handling on subscriber handling error to Event Hubs PubSub component for conformance tests.
- Add cancellation context to Azure EventHubs and update Close() to invoke cancel prior to closing the hub, which cleans up both senders and receivers.
> Note that this does not yet add Event Hubs tests to the github conformance.yml workflow as that requires the new Event Hubs resource to be set up in the Dapr production test environment first.
Fulfills the conformance testing requirement necessary for GA certification of Event Hubs components as tracked by #951 and #960 
Please make sure you've completed the relevant …
> Add Event Hubs pubsub and bindings conformance tests

- .github/workflows/conformance.yml
The conformance tests do not currently upload their test results as GitHub workflow artifacts that analytics can be run on. This PR aligns test log reporting with dapr/dapr E2E tests so that maintainers can start applying the same analytics tools to the conformance test results as well.
N/A
> Upload conformance test logs as GitHub workflow artifacts

- tests/config/bindings/tests.yml
- tests/conformance/bindings/bindings.go
- Replace existing 1s sleep after Read with `ReadBindingWait` config property in bindings.go conformance test 
- Customize `ReadBindingWait` for EventGrid bindings test to 8s
Resolves #1003 
> Increase wait between Read and Publish for EventGrid bindings conformance test

- state/redis/metadata.go
- state/redis/redis.go
- state/redis/redis_test.go
Redis unlike other databases that support TTL does not have an option to set a default TTL at the database or table / collection level.
This addition to the Redis State Store component allows defining a default TTL to be used whenever an individual State Store request does not specify a TTL.
Fixes #1060
> Adds Default TTL Option for Redis State Store

- Makefile
Disabled CGO in contrib test run - this is helpful for devs on Windows machines.
RELEASE NOTE: N/A
> Disabled CGO in contrib test run.

- bindings/smtp/smtp.go
- bindings/smtp/smtp_test.go
Update SMTP binding to allow use a SMTP server without authentication by user and password
Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/1082
> smtp allow use smtp server without auth

- bindings/postgres/postgres.go
- bindings/postgres/postgres_test.go
Add Close() function to Postgres binding to clean up client
Resolves [#901](https://github.com/dapr/components-contrib/issues/901)
> add Close() function to Postgres binding

- .github/infrastructure/conformance/azure/conf-test-azure-cosmosdb.bicep
- state/azure/cosmosdb/cosmosdb.go
Update cosmosdb.go to produce semantics consistent with #995 and pass the new state conformance tests.
- When ETag is `nil` or empty string and Concurrency is `FirstWrite`, auto-generate an ETag so that it will block a second write to the same key (cosmosdb permits the first write with a non-matching ETag when no previous key exists).
- Clean up existing setting of ETag when it is non-nil.
- Update conf-test-azure-cosmosdb.bicep to deploy with Strong default consistency configuration.
> ✅  Dapr test Cosmosdb instance has been updated for strong consistency.
> Note: The added `first-write without etag` and `first-write with etag` conformance tests also revealed an existing configuration issue with the Dapr conformance test cosmosdb instance: it only supported default consistency of …
> Update state.cosmosdb component to support first-write without ETags

- secretstores/local/file/filestore.go
- secretstores/local/file/filestore_test.go
This PR adds multi-value secret support to the local file store component. This is attempting to fix issues @paulyuk and I ran into when running through some of the samples.
Resolves #1090
> Adding multi-valued secret support to the local file store component

- .github/infrastructure/docker-compose-influxdb.yml
- .github/workflows/conformance.yml
- tests/config/bindings/influx/bindings.yml
- tests/config/bindings/tests.yml
- tests/conformance/bindings/bindings.go
- tests/conformance/common.go
- Add `OutputData` property to bindings conformance test `TestConfig`.
This is necessary to accommodate bindings like influx, cosmosdbgraph,
alibaba.table and other bindings that require a specific data format.
- Add docker-compose definition and conformance test configuration for
influx binding.
- Add influx bindings to conformance test workflow matrix.
Additional testing for #1114 addressing #898
* ~[ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_~
> Add conformance test for influx bindings

- bindings/influx/influx.go
- Remove incorrect `client.Close()` call on every call to `Invoke()`.
- Add `Close()` method to `bindings.influx` to invoke `client.Close()` on teardown instead.
Fixes #898
> Add Close() method to influx bindings

- state/azure/cosmosdb/cosmosdb.go
PR #1104 introduced a regression in cosmosdb state component `Init()` by creating a `NewConfig()` which sets a new DefaultIdentificationHydrator, which causes a panic later when invoked.
Patch this by restoring the configuration setting to use a struct with `nil` `IdentificationHydrator`.
> ⚠ This also suggests that the use of `NewConfigWithServicePrincipal` in the untested AD auth codepath will also fail and so PR #1104 does not work as intended. Separate testing will need to be done to fix that, and also a deeper investigation into why the `DefaultIdentificationHydrator` is panicking.
Please …
> Patch regression in cosmosdb state component Init

- go.mod
- go.sum
- pubsub/in-memory/in-memory.go
- pubsub/in-memory/in-memory_test.go
- tests/config/pubsub/in-memory/pubsub.yml
- tests/config/pubsub/tests.yml
- tests/conformance/common.go
Added an adapter for a hand-picked in-memory service bus implementation to support integration testing. In [this example](https://github.com/riezebosch/dapr-tdd/blob/main/DaprDemo.Api.IntegrationTests/DemoControllerTests.cs#L48), I use RabbitMQ as the underlying message broker but that makes it hard(er) to run integration tests in CI since you need to first spin it up from the pipeline.
Next thing I'll probably create is a C# wrapper to start and stop the self hosted sidecar from the integration test (and call it Dapr.Wrapr 🤟🏻 ).
Please make sure you've completed the relevant tasks for this PR, …
> feat(pubsub): add in-memory pub/sub

- bindings/kafka/kafka.go
- bindings/kafka/kafka_test.go
- pubsub/kafka/kafka.go
- pubsub/kafka/kafka_test.go
- tests/config/bindings/kafka/bindings.yml
- tests/config/pubsub/kafka/pubsub.yml
Adding `initialOffset` option to Kafka binding and pubsub components which should be useful in e2e tests because Kafka can take a while to start consuming. Because the default is "consume newest", it is unpredictable where the consumer will start. Using "oldest" for this setting will remove the need to sleep or make assumptions e2e tests when the consumers have begun streaming. 
Related to dapr/dapr#3522
Docs PR dapr/docs#1765
> Adding `initialOffset` option to Kafka binding and pubsub components

- state/azure/cosmosdb/cosmosdb.go
Follow-up to #1104 to support AD Auth codepath as well.
`NewConfig()` and `NewConfigWithServicePrincipal()` both set the `Config.IdentificationHydrator` to the `DefaultIdentificationHydrator` in the underlying a8m/documentdb library. That implementation ends up calling `reflect.Value.Elem.FieldByName()`, which requires that the value passed to it is an interface or pointer, otherwise the `Elem()` call fails to dereference which causes a panic.
cosmosdb.go passes the input to `UpsertDocument` by value today, which is eventually passed to the `DefaultIdentificationHydrator`, so changing the value passed to a pointer resolves the failure.
Follow-up to #1119
> Support DefaultIdentificationHydrator in cosmosdb state component

- secretstores/azure/keyvault/keyvault.go
- secretstores/azure/keyvault/keyvault_test.go
#972 accidentally introduced a backwards-incompatible change with a feature added in 1.3. Before, it was possible to specify an Azure environment for the AKV secret store by passing a FQDN as "vaultName" property that included the suffix for the Azure environment.
#972 introduced a better way to handle this (using the "azureEnvironment" metadata property), but accidentally broke the behavior added in 1.3
This patch restores full compatibility with 1.3. Although that behavior should be considered deprecated and thus discouraged (and it will be removed from docs), it will still be supported.
This should be considered a hotfix for the upcoming 1.4
> Restored backwards compatibility with 1.3

- secretstores/azure/keyvault/keyvault.go
- secretstores/azure/keyvault/keyvault_test.go
* Restored backwards compatibility with 1.3
#972 accidentally introduced a backwards-incompatible change with a feature added in 1.3. Before, it was possible to specify an Azure environment for the AKV secret store by passing a FQDN as "vaultName" property that included the suffix for the Azure environment.
#972 introduced a better way to handle this (using the "azureEnvironment" metadata property), but accidentally broke the behavior added in 1.3
This patch restores full compatibility with 1.3. Although that behavior should be considered deprecated and thus discouraged (and it will be removed from docs), it will still be supported.
* Lint
Cherry pick of #1131 into release
We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to …
> Cherry-pick: Restored backwards compatibility with 1.3 (#1131)

- .devcontainer/Dockerfile
Update devcontainer to use dapr-dev:0.1.4 base image
Follow-up to release for Dapr v1.4
> Update devcontainer to use dapr-dev:0.1.4 base image

- .github/workflows/conformance.yml
Add Event Hubs conformance tests to conformance.yml workflow
> Note, this PR depends on updating the Azure conformance test environment used by GitHub. This should have happened already, but the cautious may want to wait on #1091 so that /ok-to-test can be used for this PR. 
Part of the workstream for #960
> Add Event Hubs conformance tests to conformance.yml workflow

- authentication/azure/auth.go
- bindings/azure/blobstorage/blobstorage.go
- bindings/azure/eventgrid/eventgrid.go
- bindings/azure/eventhubs/eventhubs.go
- bindings/azure/servicebusqueues/servicebusqueues.go
- bindings/azure/signalr/signalr.go
- bindings/azure/storagequeues/storagequeues.go
- pubsub/azure/eventhubs/eventhubs.go
- pubsub/azure/servicebus/servicebus.go
- secretstores/azure/keyvault/keyvault.go
- state/azure/blobstorage/blobstorage.go
- state/azure/tablestorage/tablestorage.go
- state/mongodb/mongodb.go
Set custom user agent for `dapr` to be used with various Azure services.
This change prepends `dapr-$version` to the user Agent, or sets this as the user Agent where no other value exists.
#1014 
The upstream components already have tests for setting custom user agents. No additional tests needed here.
> Add dapr user agent for Azure Components

- bindings/azure/servicebusqueues/servicebusqueues_integration_test.go
- bindings/mysql/mysql_integration_test.go
- state/mysql/mysql_integration_test.go
- state/postgresql/postgresql_integration_test.go
Fix existing failures in components integration tests
N/A
> Fix existing integration tests

- state/sqlserver/migration.go
SQLServer upsert procedure is now versioned (new name) to ensure everyone uses the latest correct version of the stored procedure when updating Dapr.
As per #1175 
Manually ran conformance tests and integration tests against Azure SQL Server.
> Version SQLServer stored procedure due to previous changes made

- .github/infrastructure/conformance/azure/conf-test-azure-iothub.bicep
- .github/infrastructure/conformance/azure/conf-test-azure.bicep
- .github/infrastructure/conformance/azure/setup-azure-conf-test.sh
- bindings/azure/eventhubs/eventhubs_integration_test.go
- pubsub/azure/eventhubs/eventhubs_integration_test.go
- tests/scripts/send-iot-device-events.sh
- Add setup of Azure IoT Hub to setup-azure-conf-tests.sh for integration testing with EventHubs bindings/pubsub.
- Backfill functional tests for #1009
Test follow-up to #227 
Test infrastructure to support #951 
> Support setting up Azure IoT Hub for integration testing with EventHubs components

- pubsub/rabbitmq/metadata.go
- pubsub/rabbitmq/metadata_test.go
- pubsub/rabbitmq/rabbitmq.go
Fix  'durable' setting in RabbitMQ
Please reference the issue this PR will close: #1181
> fix 'durable' setting in RabbitMQ

- bindings/azure/servicebusqueues/servicebusqueues.go
Azure Service Bus Queue names are case-insensitive. When one is
created it will always be forced to lowercase. If a queue with a
non-lowercase is provided, it will be created but can never be
matched causing the next Init to fail.
Please reference the issue this PR will close: #1185 
> Force lowercase name for Azure Service Bus Queue

- nameresolution/mdns/mdns.go
- nameresolution/mdns/mdns_test.go
I was just reading the mDNS nameresolver and noticed a few code smells I had left in there during the implementation, namely:
- loop closure variables
- slices of pointers
- over specialized types
- appending to none zero length initialized slices
- using explicit zero value initialization over empty literal initialization
So I've just cleaned these up in the PR.
I have also extended the mDNS address timeout from 45 secs to 60 secs. The addresses are refreshed every 30 secs so this shouldn't actually change any behavior and is just there increase the potential cache lifetime slightly.
> Improve mDNS nameresolver code quality

- .github/infrastructure/conformance/azure/conf-test-azure-sqlserver.bicep
- .github/infrastructure/conformance/azure/conf-test-azure.bicep
- .github/infrastructure/conformance/azure/setup-azure-conf-test.sh
- .github/workflows/conformance.yml
- tests/config/state/azure/sql/statestore.yaml
- tests/config/state/tests.yml
- tests/conformance/common.go
- Add support in setup-azure-conf-test.sh for deploying Azure SQL server the state.sqlserver conformance/integration testing.
- Avoid pre-creating the database as Azure SQL DBs charge for hosting that does not scale to zero.
- Provision the test runner Service Principal as Contributor so it can configure the firewall and create DBs as needed during testing.
- Add conformance test state.azure.sql for exercising state.sqlserver component against Azure SQL instance.
- Add special handling in conformance.yml to configure Azure SQL firewall rules to permit test running IP to connect, and to clean up firewall rule and test DB afterwards.
- Existing sqlserver_integration_test.go can reuse the deployed Azure SQL instance by following similar steps to configure the SQL firewall, and mapping …
> Add state.sqlserver conformance test against Azure SQL

- tests/certification/secretstores/azure/keyvault/go.sum
Test is currently failing due to new go mod tidy check. This fixes it.
> KeyVault Conformance: Fix test by running go mod tidy

- .github/workflows/certification.yml
- tests/certification/secretstores/azure/keyvault/keyvault_test.go
- tests/certification/secretstores/azure/keyvault/managed-identity-app/Dockerfile
- tests/certification/secretstores/azure/keyvault/managed-identity-app/components/keyvault.yaml
- tests/certification/secretstores/azure/keyvault/managed-identity-app/components/localsecrets.yaml
- tests/certification/secretstores/azure/keyvault/managed-identity-app/startup.sh
Adds certification for Managed Identity Authentication to the Azure Key Vault Component.
This builds a container image and stores it using Azure Container Registry, then runs the container image in Azure Container Instances with injected managed identity.
The requisite `dapr2conftestacr` container registry (with standard SKU) has already been created.
closes #959 
> Managed Identity Certification Test for Azure KeyVault Component

- .github/workflows/certification.yml
GitHub Workflow for KV Certification is failing at the moment due to a missing environment variable / secret.
This PR injects the missing environment variable.
> Add missing env variable for KV certification test

- bindings/azure/cosmosdb/cosmosdb.go
- go.mod
- state/azure/cosmosdb/cosmosdb.go
Adds exponential backoff retry on Cosmos DB component initialization for up to 5 minutes total time.
Background: Cosmos DB makes a lot of Metadata requests upon client initialization. This limit is shared by all databases in a single Cosmos DB Account. It is easy to exceed this limits if multiple connections (for example via multiple sidecars) are made to the same Cosmos DB database account. To alleviate this problem we are introducing exponential backoff on init here.
As outlined in https://docs.microsoft.com/azure/cosmos-db/sql/troubleshoot-request-rate-too-large#recommended-solution-3
> Adds retry on CosmosDB Init in case of TooManyRequests error

- bindings/azure/cosmosdb/cosmosdb.go
- state/azure/cosmosdb/cosmosdb.go
> Cherry-pick into release 1.5 PR #1329

- pubsub/aws/snssqs/snssqs.go
Signed-off-by: Amit Mor <amit.mor@hotmail.com>
* conditional creation of sns topic, sns-sqs subscription and sqs queues (here forth: assets)
* sync.Map protecting concurrent r/w access to cached assets references
* major refactoring (aws policy to a file, additional consts, similar assets getOrCreate handling)
* uncaught bugfix: when using deadletters-queue, if for some reason a message was received more times than it should have been, given it should have already been moved to the deadletters-queue, we used to process it as is without any notice - effectively breaking the expected behavior the user defined
Please reference the issue this PR will close: #1313 …
> disable entity creation

- pubsub/aws/snssqs/snssqs.go
bug fix - `disableEntityManagement` feature #1313 introduced the ability to disable the creation of SNS topics, SQS queues and the subscription of the first to the second. However, the implementation of that issue did not disable the creation of SQS policy statement.
This PR simply avoids the creation of the policy if the user specified in the metadata to `disableEntityManagement`
Please reference the issue this PR will close: #1385 
> 1385 disable policy creation

- bindings/aws/s3/s3.go
- bindings/aws/s3/s3_test.go
Add S3ForcePathStyle support for S3 API compatible products, like Minio.
#1322 
> add S3ForcePathStyle support for s3 binding

- authentication/azure/auth.go
- pubsub/azure/eventhubs/eventhubs.go
- pubsub/azure/eventhubs/eventhubs_test.go
- tests/config/pubsub/tests.yml
Rewrite of eventhubs component.
1. Added support for partition keys.
2. Added support for honoring incoming topic names in requests. 
3. Fixed bug on running multiple subscribers for a topic(leaser checkpointer prefix issue).
4. Added support for authentication via AAD.
5. Added support for creating eventHubs/consumer groups on the fly as long as a the event hubs namespace is created and with right permissions. 
Adding more resiliency and retries if needed on connection will be part of the certification task and is left off for this PR.
part of #951 
closes #964 
closes dapr/dapr#3753
closes #1225 
Please make sure you've completed the relevant tasks for this …
> rewrite EventHubs component

- go.mod
- go.sum
- state/oci/objectstorage/objectstorage.go
- state/oci/objectstorage/objectstorage_test.go
The OCI Object Storage Service is a cloud service on Oracle Cloud Infrastructure, very similar in nature to AWS S3 and Azure BlobStorage. This services support creating, retrieving, deleting objects that represent state. It has concurrency control through ETags. I believe that especially for Daprized applications running on OCI – either on OKE, the OCI container engine for Kubernetes or on a compute instance – it can be of value to leverage ObjectStorage as the state store. It is cheap, easily accessible and can easily be integrated into many technologies from within the OCI cloud as well as from elsewhere.
The contribution allows Dapr application operators to configure state store components backed by OCI Object Storage.
The code I submit in this PR has been described in some detail in …
> Implement State Store for OCI ObjectStorage service

- pubsub/kafka/kafka.go
- tests/certification/pubsub/kafka/go.sum
- tests/certification/pubsub/rabbitmq/go.sum
Allows metadata to be set as message headers (except for `partitionKey` which is used to set the message `Key`).
Closes #1408 
> Kafka PubSub: Use metadata as message headers.

- pubsub/aws/snssqs/metadata.go
- pubsub/aws/snssqs/snssqs.go
- pubsub/aws/snssqs/snssqs_test.go
* allow the user to define a timeout for AWS assets related operations, instead of relying on `net/http` timeouts. Assets operations being, but not limited to: SNS topics creation/verification, SQS queues creation/verification, Subscriptions, STS caller identity calls, etc.
* use `context` and `cancel` in all AWS go sdk API calls
* component `Close` method should call the  `cancel` function of the parent context and cleanly cancel child operations
* utilize exponential backoff* when errors in pulling SQS messages occur (such as in network interruptions). This would lower the log flooding with error messages upon retries of the component
* publish messages with user configurable `retry` implementation
* introduce new metadata config field: `disableDeleteOnRetryLimit` the prevent the …
> Pubsub AWS SNS/SQS - adding context, cancellation, timeouts, retrying \w backoff & disable delete of messages on failure

- tests/certification/secretstores/azure/keyvault/keyvault_test.go
The Azure Key Vault Certification test for Key Vault performs a very fragile end to end test to evaluate managed identity behavior.
This test isn't strictly necessary as verifying service principal auth exercises the same underlying code path and underlying SDKs.
For now, this PR disables the failing managed identity test which fails in the infrastructure provisioning stages. We can either remove this test in the future or implement the provisioning of required test infrastructure differently.
> Temporarily disables the AKV managed identity test

- tests/certification/flow/watcher/watcher.go
- tests/certification/pubsub/kafka/kafka_test.go
- tests/certification/pubsub/mqtt/docker-compose.yml
- tests/certification/pubsub/mqtt/mqtt_test.go
This is to fix certification test failure in kafka and mqtt. The tests are failing due to a small concurrency issue in which a message added for tracking before Publish event isn't removed in case the Publish fails. 
It also updates certain environment variables for emqx broker(MQTT) in which the default values ain't enough.
Please reference the issue this PR will close: 
> Fixing Certification tests failure

- bindings/mysql/mysql.go
- bindings/mysql/mysql_integration_test.go
Signed-off-by: zdianjiang <zdianjiang@gmail.com>
bingding/mysql not special case type of TEXT column, add TEXT type to string it.
> bingding/mysql: add TEXT column type to special case

- pubsub/rabbitmq/rabbitmq.go
When rabbitmq server-side close connection or restart, rabbitmq pubsub can not reconnect the server.
The `reset` function will set r.channel to nil, which means https://github.com/dapr/components-contrib/blob/master/pubsub/rabbitmq/rabbitmq.go#L341 should return r. connectionCount.
This change will not break the concurrence reconnect limit.
Please reference the issue this PR will close: dapr/dapr#4143
> Fix rabbitmq pubsub reconnect

- state/azure/cosmosdb/cosmosdb_query.go
- state/azure/cosmosdb/cosmosdb_query_test.go
- state/mongodb/mongodb_query.go
- state/mongodb/mongodb_query_test.go
- state/postgresql/postgresql_query.go
- state/postgresql/postgresql_query_test.go
- state/query/query_test.go
- tests/state/query/q2-token.json
- tests/state/query/q2.json
- tests/state/query/q3.json
- tests/state/query/q4.json
- tests/state/query/q5.json
statestore query API: remove 'value' prefix from key names in query JSON object
Please reference the issue this PR will close: #1490
> statestore query API: remove 'value' prefix from key names in query JSON

- pubsub/rabbitmq/metadata.go
- pubsub/rabbitmq/metadata_test.go
- pubsub/rabbitmq/rabbitmq.go
Supports rabbitmq pubsub set exchangeKind.
Use routingKey metadata as rabbitmq routing key.
Please reference the issue this PR will close: #1502 
> Supports rabbitmq pubsub set exchangeKind

- state/errors.go
- state/sqlserver/sqlserver.go
This PR introduces a logic for only keeping the latest operations per key in a transaction. This is similar to what was proposed in https://github.com/dapr/components-contrib/issues/1209#issuecomment-982731149. For example, say the original transaction is:
```bash
upsert k1 v1  # redundant, gets deleted later
delete k1
delete k2     # redundant, gets set to v2 later
upsert k2 v2
```
Since #1517 was a prerequisite, I have merged the changes with this one. It ignores row mismatch error while using bulk delete in transactions.
Please reference the issue this PR will close: #1505, #1517
* (NA) Created/updated tests - will be added as part of #1210 …
> Fix transaction API for Azure SQL server

- pubsub/azure/servicebus/servicebus.go
Add retriable error conditions for Azure Service Bus PubSub message sending
Utilizing conditions as listed here:
https://docs.microsoft.com/en-us/javascript/api/@azure/amqp-common/conditionstatusmapper?view=azure-node-preview
Fixes #1495
> Add retriable error conditions for Azure Service Bus PubSub message sending

- .devcontainer/Dockerfile
For some reason the Dev Container wasn't even using Dapr 1.6. We had to make another change to the dev container, so pinning this to 0.1.6a now.
Do not merge this PR until https://github.com/dapr/dapr/pull/4316 is merged.
> Update Dev Container Base Image

- pubsub/gcp/pubsub/pubsub.go
Signed-off-by: Ricardo Corrêa <r.c.correa@outlook.com>
Reject the message when an error occurs.
Please reference the issue this PR will close: #1561
> Google Cloud PubSub No Ack (nack) when there is an error

- state/mongodb/mongodb_query.go
- state/mongodb/mongodb_query_test.go
- tests/state/query/q6.json
Fixed a bug in MongoDB state component: querying non-string values returns an error.
Please reference the issue this PR will close: #1583
> mongodb: fix querying non-string values

- state/mongodb/mongodb.go
- state/mongodb/mongodb_query.go
- tests/conformance/state/state.go
Signed-off-by: Mukundan Sundararajan <msundar.ms@outlook.com>
Change to marshal to Ext JSON with Relaxed format instead of Canonical Format. 
Without the change to `canonical` representation as false, the added conformance test scenario fails 
```
state.go:257: Checking value presence for b92a399b3889432782b78babd1169ab8-struct-with-int
state.go:675: 
Error Trace:	state.go:675
state.go:266
Error:      	unmarshal error
Test:       	TestStateConformance/mongodb/get
Messages:   	error: %!w(*json.UnmarshalTypeError=&{object 0x10721fe20 12 IntValueType message}), json: {"message":{"$numberInt":"42"}}
```
Please reference the issue this PR will close: #1582 
Please …
> [WIP] marshal mongodb bson into relaxed json

- go.mod
- go.sum
- tests/certification/bindings/azure/blobstorage/go.mod
- tests/certification/bindings/azure/blobstorage/go.sum
- tests/certification/bindings/azure/cosmosdb/go.mod
- tests/certification/bindings/azure/cosmosdb/go.sum
- tests/certification/bindings/azure/servicebusqueues/go.mod
- tests/certification/bindings/azure/servicebusqueues/go.sum
- tests/certification/go.mod
- tests/certification/go.sum
- tests/certification/pubsub/kafka/go.mod
- tests/certification/pubsub/kafka/go.sum
- tests/certification/pubsub/mqtt/go.mod
- tests/certification/pubsub/mqtt/go.sum
- tests/certification/pubsub/rabbitmq/go.mod
- tests/certification/pubsub/rabbitmq/go.sum
- tests/certification/secretstores/azure/keyvault/go.mod
- tests/certification/secretstores/azure/keyvault/go.sum
- tests/certification/state/sqlserver/go.mod
- tests/certification/state/sqlserver/go.sum
With #1589, we upgraded the github.com/alibabacloud-go/darabonba-openapi package and introduced replace directives to upgrade github.com/alibabacloud-go/alibabacloud-gateway-spi.
Recently, darabonba-openapi had a new release which now points to the latest version of alibabacloud-gateway-spi. This PR removes the replace directives added previously, and points to the latest versions of the packages.
Please reference the issue this PR will close: #1477
* (NA) Created/updated tests
* (NA) Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
> Upgrade alibabacloud-go modules and clean up transitive replace

- bindings/aws/s3/s3.go
- bindings/aws/s3/s3_test.go
Adds a metadata option `insecureSSL` for the S3 binding which allows accepting self-signed TLS certificates. This is especially useful when using Minio (see #1592).
Note: I'm not really sure on the name of the metadata. `insecureSSL` seemed short enough and mirrors `disableSSL` (which switches to using HTTP), and it's aligned with the `--insecure` flag of curl. But open to suggestions.
Closes #1592
> Allow accepting self-signed TLS certs for S3

- nameresolution/mdns/mdns.go
- nameresolution/mdns/mdns_test.go
Resolved feedback items left on https://github.com/dapr/components-contrib/pull/1591 after merge. There isn't any behavioural changes here.
Please reference the issue this PR will close: [#dapr/dapr/4323](https://github.com/dapr/components-contrib/pull/dapr/java-sdk#709)
> Sync mDNS first browse PATCH

- go.mod
- go.sum
- state/azure/cosmosdb/cosmosdb.go
- state/azure/cosmosdb/cosmosdb_query.go
- state/azure/cosmosdb/storedprocedure.go
- tests/certification/bindings/azure/blobstorage/go.sum
- tests/certification/bindings/azure/cosmosdb/go.mod
- tests/certification/bindings/azure/cosmosdb/go.sum
- tests/certification/bindings/azure/servicebusqueues/go.sum
- tests/certification/go.sum
- tests/certification/pubsub/kafka/go.sum
- tests/certification/pubsub/mqtt/go.sum
- tests/certification/pubsub/rabbitmq/go.sum
- tests/certification/secretstores/azure/keyvault/go.sum
- tests/certification/state/sqlserver/go.sum
Fixes #1603
As explained in #1603, wen using Azure AD auth (including MSI) we cannot perform CRUD operations on stored procedures on Cosmos DB, so the component failed to init.
This works around that issue by creating a secondary stored procedure that returns the version of the Dapr SP. If authenticating with AAD, that SP is invoked and if the version mismatches, we guide the user to the docs where they can learn how to set things up (docs update is on my TODO).
> Workaround for Cosmos DB state store unable to launch when using AAD auth

- bindings/azure/cosmosdb/cosmosdb.go
- state/azure/cosmosdb/cosmosdb.go
This PR adds automatic re-try of operations running against Cosmos DB (state store and binding) when the requests are throttled by the service (and only in that case).
Fixes #1611 
> Cosmos DB components handle throttling

- nameresolution/mdns/mdns.go
This fixes daprd runtime from hanging when it is being shutdown.
> mDNS: Add size to channel to fix blocking when .Close is called

- state/azure/cosmosdb/storedprocedures/__dapr_v2__.js
- state/azure/cosmosdb/storedprocedures/__daprver__.js
This is a spin-off from #1634 . Given how close we are to the 1.7 release, this is a much less riskier approach, as these changes do not impact the compiled code.
These are not included in the compiled app and have no effect (for now). However, we need these tagged together with the release so we can use them in docs.
A separate commit (not slated for 1.7) will use Go embed to actually use these in code
> Adding Cosmos DB stored procedure files in the source tree

- .github/workflows/dapr-bot.yml
Adds `/ok-to-test` capability to Daprbot so that we can easily run certification and conformance tests from more PRs, including PRs into release branches.
> Adds /ok-to-test to contrib daprbot

- state/azure/cosmosdb/cosmosdb.go
This, which is possible now because of improvements in the upstream SDK, should speed up delete operations significantly (and reducing RU usage).
Also, this should fix potential concurrency issues.
(Note this is built on top of #1643)
> Cosmos DB: Delete does not need to query for the doc first 

- .github/workflows/certification.yml
Adds a missing secret to the EventHubs PubSub certification workflow
> Fix azure eventhubs pubsub certification test workflow

- .github/workflows/certification.yml
Signed-off-by: Surender Singh Malik <surenderssm@users.noreply.github.com>
Certification tests for azure event hub relies on `AzureIotHubName` environment variable to test IOT scenario.
The same is being added in github workflow
> Adding AzureIotHubName env for eventhub cert workflow

- tests/certification/pubsub/azure/eventhubs/README.md
- tests/certification/pubsub/azure/eventhubs/eventhubs_test.go
- tests/certification/pubsub/azure/eventhubs/send-iot-device-events.sh
Signed-off-by: Surender Singh Malik <surenderssm@users.noreply.github.com>
azure-iot-cli-extension is required for the IOT devise test cases.
The installation of the same is enabled via azure-iot extension without prompt.
https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
https://github.com/Azure/azure-iot-cli-extension
> eh-certification test : Install azure-iot-cli-extension if not found for IOT tests

- tests/certification/bindings/azure/blobstorage/go.mod
- tests/certification/bindings/azure/blobstorage/go.sum
- tests/certification/bindings/azure/cosmosdb/go.mod
- tests/certification/bindings/azure/cosmosdb/go.sum
- tests/certification/bindings/azure/servicebusqueues/go.mod
- tests/certification/bindings/azure/servicebusqueues/go.sum
- tests/certification/go.mod
- tests/certification/go.sum
- tests/certification/pubsub/azure/eventhubs/go.mod
- tests/certification/pubsub/azure/eventhubs/go.sum
- tests/certification/pubsub/kafka/go.mod
- tests/certification/pubsub/kafka/go.sum
- tests/certification/pubsub/mqtt/go.mod
- tests/certification/pubsub/mqtt/go.sum
- tests/certification/pubsub/rabbitmq/go.mod
- tests/certification/pubsub/rabbitmq/go.sum
- tests/certification/secretstores/azure/keyvault/go.mod
- tests/certification/secretstores/azure/keyvault/go.sum
- tests/certification/state/sqlserver/go.mod
- tests/certification/state/sqlserver/go.sum
Pin certification tests to latest daprd with binding context change
This should make the certification tests pass again.
> Pin certification tests to latest daprd with binding context change

- go.mod
- go.sum
- secretstores/Readme.md
- secretstores/huaweicloud/csms/csms.go
- secretstores/huaweicloud/csms/csms_test.go
Add HuaweiCloud Cloud Secret Management Service (CSMS) as a secret component.
https://support.huaweicloud.com/intl/en-us/usermanual-dew/dew_01_9994.html
Please reference the issue this PR will close: #_[[1704](https://github.com/dapr/components-contrib/issues/1704)]_
> Implment a secret store based on Huawei CSMS

- bindings/azure/storagequeues/storagequeues.go
- bindings/azure/storagequeues/storagequeues_test.go
Adds support for a custom endpoint URL for Azure Storage Queues. This is useful for using [production-style URLs](https://github.com/Azure/Azurite#production-style-url) with [Azurite](https://github.com/Azure/Azurite) for local development.
- #581 
- #581 
> Support custom queueEndpoint in Azure Storage Queues

- lock/redis/standalone.go
- lock/redis/standalone_test.go
- lock/requests.go
Signed-off-by: seeflood <349895584@qq.com>
change `Expire` in lock component to `ExpiryInSeconds`
Please reference the issue this PR will close: #1720
> change `Expire` in lock component to `ExpiryInSeconds`

- bindings/azure/servicebusqueues/servicebusqueues.go
- bindings/azure/servicebusqueues/servicebusqueues_test.go
- go.mod
- go.sum
- pubsub/azure/servicebus/metadata.go
- pubsub/azure/servicebus/servicebus.go
- pubsub/azure/servicebus/servicebus_test.go
- pubsub/azure/servicebus/subscription.go
- tests/certification/bindings/azure/servicebusqueues/go.mod
- tests/certification/bindings/azure/servicebusqueues/go.sum
1. Implement a rate limit when messages are retried, as per conversation with @artursouza . Because when a message is abandoned in ASB it gets re-queued immediately and sent to someone else, we need to slow down or in certain situations we can consume all max retries of messages too quickly (possibly at the rate of 100's per second)
- This required adding a new metadata key `maxRetriableErrorsPerSec` in both pubsub and binding
1. Binding: previously, the binding was reconnecting to ASB after receiving every single message. Now the connection is kept open to avoid wasting resources. (I should have noticed that earlier).
1. Do not attempt to reconnect when context was canceled
1. Message finalization uses a background context and not the running ctx, in case the app is shutting down
> Tweaks for ASB pubsub

- pubsub/azure/servicebus/metadata.go
- pubsub/azure/servicebus/servicebus_test.go
Small typo in the JSON key for the `maxRetriableErrorsPerSec` for Azure Service Bus.
> Fixed typo in metadata JSON key

- bindings/aws/s3/s3.go
- bindings/aws/s3/s3_test.go
This PR adds the ability to have Dapr read a file and upload the contents instead of having the user write boilerplate code to read the file and then send the data over the wire, which can be problematic for large file uploads.
> Add file upload to s3

- go.mod
- go.sum
- tests/certification/bindings/alicloud/dubbo/go.mod
- tests/certification/bindings/alicloud/dubbo/go.sum
Pin Dubbo to altest commit in `dubbo.apache.org/dubbo-go/v3@dapr-support`
> Upgrade Apache Dubbo again - pin to Dapr support branch

- lock/requests.go
- lock/responses.go
Needed in order to enable a RESTful API in `dapr/dapr`.
> Add json tags to lock requests/responses

- .github/workflows/certification.yml
- Moves to scheduled certification workflow to run every 12 hours instead of 30 minutes to avoid overlapping test runs. `/ok-to-test` is preferred to evaluate PRs.
- Does not print test logs for tests that pass without error -- avoid verbose mode.
- Combines several test steps such that the "Run tests" step is the step which will fail -- this is much more intuitive for users / developers of Dapr.
> Update certification workflow

- nameresolution/consul/consul.go
- nameresolution/consul/consul_test.go
Signed-off-by: wisdom <153594697@qq.com>
In the absence of an id, different instances of the same service registered to consul will be overwritten.
So, new id is added to distinguish them.
https://github.com/dapr/components-contrib/issues/1513
https://github.com/dapr/components-contrib/issues/1199
> add id when registering services to consul

- pubsub/mqtt/mqtt.go
- pubsub/mqtt/mqtt_test.go
Partially reverts #1810 because support for "retain" is currently broken (working on it for 1.9). Unit tests are passing
> MQTT: re-set "retain" to false as default

- state/oci/objectstorage/objectstorage.go
- state/oci/objectstorage/objectstorage_test.go
Signed-off-by: 1046102779 <seachen@tencent.com>
[kit](github.com/dapr/kit) should add two log api, then we can pass the log via context within the process .
- NewContext(NewContext(ctx context.Context, logger *Logger) context.Context
- FromContextOrDefault(ctx context.Context) *Logger
```golang
// NewContext returns a new Context, derived from ctx, which carries the
// provided Logger.
func NewContext(ctx context.Context, logger *Logger) context.Context {
return context.WithValue(ctx, contextKey{}, logger)
}
// FromContextOrDiscard returns a Logger from ctx.  If no Logger is found, this
// returns a Logger that discards all log messages.
func FromContextOrDefault(ctx context.Context) *Logger {
if v, ok := ctx.Value(contextKey{}).(*Logger); ok {
return v
}
return DefaultZapLogger
}
```
> optimize: move logger from api to struct

- .github/workflows/dapr-bot-schedule.yml
I added the automerge label to contrib some time ago, but this label only can be used by maintainers as indicated here. The maintainer list was wrong and is now updated to include myself.
> Actually let all contrib maintainers use automerge label

- bindings/azure/blobstorage/blobstorage.go
- bindings/azure/blobstorage/blobstorage_test.go
- Adds timeout to container creation to avoid hanging
- Simpler/faster parsing of metadata
- A couple more smaller things
> Small improvements to blobstorage binding

- bindings/twilio/sendgrid/sendgrid.go
- bindings/twilio/sms/sms.go
- go.mod
- go.sum
Ensure output binding propagates context (requires updated SDK)
> Updated Twilio components

- pubsub/azure/eventhubs/eventhubs.go
Event Hubs does need built-in retries as the service does not support N/ACKs for messages. Tests are currently failing without.
This PR reverts #1798 for the `pubsub.azure.eventhubs` component only (and adds a comment explaining why we need that).
> Reverting #1798 for pubsub.azure.eventhubs

- authentication/azure/storage.go
- bindings/azure/blobstorage/blobstorage.go
- bindings/azure/eventhubs/eventhubs.go
- bindings/azure/storagequeues/storagequeues.go
- bindings/azure/storagequeues/storagequeues_test.go
- pubsub/azure/eventhubs/eventhubs.go
- state/azure/blobstorage/blobstorage.go
- tests/certification/bindings/azure/blobstorage/go.mod
- tests/certification/bindings/azure/blobstorage/go.sum
- tests/certification/bindings/azure/cosmosdb/go.mod
- tests/certification/bindings/azure/cosmosdb/go.sum
- tests/certification/bindings/azure/eventhubs/go.mod
- tests/certification/bindings/azure/eventhubs/go.sum
- tests/certification/bindings/azure/servicebusqueues/go.mod
- tests/certification/bindings/azure/servicebusqueues/go.sum
- tests/certification/pubsub/azure/eventhubs/go.mod
- tests/certification/pubsub/azure/eventhubs/go.sum
- tests/certification/secretstores/azure/keyvault/go.mod
- tests/certification/secretstores/azure/keyvault/go.sum
- tests/certification/state/azure/tablestorage/go.mod
- tests/certification/state/azure/tablestorage/go.sum
Adds Azure AD auth support for Azure Storage Queues binding.
Also fixes the test failures in master due to the component, such as: https://github.com/dapr/components-contrib/actions/runs/2599442926
See #1103
> Add support for AAD auth in Azure Storage Queues binding

- pubsub/envelope.go
- pubsub/envelope_test.go
- pubsub/rocketmq/rocketmq.go
Modified the envelope structure of the Cloud Event to receive ActorType and ActorID. Added unit test cases to verify functionality and modified existing test cases. 
Please reference the issue this PR will close: WIP #501 Pubsub for actors
> Modified envelope to accept Actors

- internal/authentication/aws/aws.go
Signed-off-by: Clare Liguori <liguori@amazon.com>
Setting the user agent on the AWS SDK helps provide more context in CloudTrail entries about the API calls made by Dapr, especially where the Dapr sidecar may be using the same credentials as the main app container.
Example CloudTrail entry for an SQS CreateQueue API call made by Dapr using the pubsub quickstart, showing the Dapr user agent:
```
{
"eventVersion": "1.08",
"userIdentity": {
"type": "IAMUser",
"principalId": "XXXXXX",
"arn": "arn:aws:iam::XXXXXX:user/clare",
"accountId": "XXXXXX",
"accessKeyId": "XXXXXX",
"userName": "clare"
},
"eventTime": "2022-07-18T20:31:36Z",
"eventSource": "sqs.amazonaws.com",
"eventName": "CreateQueue",
"awsRegion": "us-west-2",
"sourceIPAddress": "XXXXXX",
"userAgent": "aws-sdk-go/1.41.7 (go1.18; …
```
> Add user agent to AWS requests

- pubsub/feature.go
- pubsub/mqtt/mqtt.go
Currently only the MQTT component seems to have support for subscribing to topics/queues with a wildcard in the name. This adds the capability.
> Added pubsub.FeatureSubscribeWildcards capability

- .github/workflows/certification.yml
- internal/component/azure/servicebus/subscription.go
Signed-off-by: Joni Collinge <jonathancollinge@live.com>
Instead of using the message ID which is not guarenteed to be unique as a key in the map to track the active messages this PR changes to use the messages sequence 
number which is guarenteed to be unique per message.
Please reference the issue this PR will close: #1892
> Use unique message key in Azure ServiceBus PubSub

- .github/workflows/certification.yml
- .github/workflows/conformance.yml
The `skip duplicate actions` workflow is causing more trouble than it is worth. Every time a PR is updated by merging master into the PR branch several required tests are skipped and then the PR becomes unmergeable.
> Do not skip duplicate actions for conf and cert tests

- .github/workflows/components-contrib.yml
- Disabled caching in linter action to prevent timeouts, which seem to be happening frequently
- Added Go module cache explicitly
- Removed unused "skip duplicate" action
> Updated CI

- .github/workflows/components-contrib.yml
- .golangci.yml
Make linter timeout 15 min (hopefully never really needed)
> make linter timeout 15 min

- pubsub/jetstream/jetstream.go
- pubsub/jetstream/metadata.go
- pubsub/jetstream/metadata_test.go
- Configure the NATS client for TLS Client Authentication if a key pair is supplied.
- Closes #1923
> [pubsub/jetstream]: allow tls client authentication

- go.mod
- go.sum
Apache Dubbo has a dependency that is missing a license. This project apparently moved to another org which does have a license. This change ensures the licensed version is used instead.
> Addresses Fossa Failures due to Apache Dubbo indirect dependency

- .codecov.yaml
- .github/workflows/components-contrib.yml
v1 is deprecated per https://github.com/codecov/codecov-action
> Updated codecov Action to v3

- tests/certification/flow/retry/retry.go
- tests/certification/go.mod
- tests/certification/pubsub/mqtt/go.mod
- tests/certification/pubsub/mqtt/mqtt_test.go
See https://github.com/dapr/dapr/pull/4926
Thankfully, in this repo the only impact was in 2 tests.
> Ensure we're using the right version of cenkalti/backoff

- bindings/zeebe/jobworker/jobworker.go
- go.mod
- go.sum
- tests/e2e/bindings/zeebe/command/activate_jobs_test.go
- tests/e2e/bindings/zeebe/command/cancel_instance_test.go
- tests/e2e/bindings/zeebe/command/complete_job_test.go
- tests/e2e/bindings/zeebe/command/create_instance_test.go
- tests/e2e/bindings/zeebe/command/deploy_process_test.go
- tests/e2e/bindings/zeebe/command/fail_job_test.go
- tests/e2e/bindings/zeebe/command/publish_message_test.go
- tests/e2e/bindings/zeebe/command/set_variables_test.go
- tests/e2e/bindings/zeebe/command/throw_error_test.go
- tests/e2e/bindings/zeebe/command/topology_test.go
- tests/e2e/bindings/zeebe/command/update_job_retries_test.go
- tests/e2e/bindings/zeebe/docker-compose.yml
- tests/e2e/bindings/zeebe/helper.go
- tests/e2e/bindings/zeebe/jobworker/jobworker_test.go
- tests/e2e/bindings/zeebe/processes/calc.bpmn
The actual implementation of the Zeebe job worker binding auto-completes a job automatically if a success response will be returned or if an error occurs. In case of an error, the binding will create an incident. But there is also a case that a process can throw a business error. This can actually not be handled, because of this auto-completion functionality. 
This change introduces a new flag "autocomplete" which is enabled by default to keep backward compatibility. Auto-completion is also the most common way to handle worker results. If a worker should return a business error, then this flag can be set to false and the worker can complete the job itself with either an incident, business error or a success response.
The PR adds also new tests to test this behavior and fixes also the …
> Add auto-completion flag for Zeebe

- bindings/azure/eventhubs/eventhubs.go
- bindings/azure/eventhubs/eventhubs_test.go
Hi,
We are currently adopting the naming change from this PR #1292 to the KEDA Eventhub Scaler. But the naming change includes only the pubsub component and not the eventhub binding. So there are two different naming schemas for storage leases, and this makes it more difficult to integrate that in the KEDA Scaler.
See  this discussion on KEDA: [https://github.com/kedacore/keda/issues/3022](https://github.com/kedacore/keda/issues/3022)
Before doing the KEDA change, it makes sense to use a unique naming schema for pubsub and binding. So I've made a proposal for it.
What do you think?
> binding.eventhub: use same name schema for storage leases like on pubsub.eventhub

- bindings/cron/cron.go
The cron binding did not resume correctly after a context cancellation and a new context. This is currently not (yet) used in Dapr so no end-user impact yet.
> bindings.cron: ensure it can resume correctly after context cancellation

- .github/workflows/conformance.yml
Ensures the CosmosDB Binding conformance test is actually run. Manually verified test passes against Master and #1876 from @RyanLettieri
> Enable CosmosDB Binding conformance test

- .github/workflows/dapr-bot.yml
Give access to `/ok-to-test` to several more people working on certification tests.
> Allow more folks to run `/ok-to-test`

- internal/component/azure/servicebus/subscription.go
In the methods used to read from Azure Service Bus (used by the ASB Queue binding and the ASB pubsub components), in case of errors (for example, a prolonged network failure of usually > 1 min) a channel that was used as semaphore to limit concurrency (`activeMessagesChan`) was not drained, eventually reaching the concurrency limit. This caused the component to stop reading new messages from Azure Service Bus.
I was able to reproduce the error by turning off WiFi on my laptop for a prolonged amount of time, about 1 min; the repro is consistent. Our certification tests did not catch this issue because they cannot interrupt the network for such a long time.
Additionally, upon review of the usage of other channels used to limit concurrency, a smaller issue was found with `handleChan` which …
> Ensure locks in channels are properly released

- tests/e2e/pubsub/jetstream/authentication/authentication_test.go
```shell
=== RUN   TestAuthentication
=== RUN   TestAuthentication/Valid_jwt_and_valid_seed
err: nats: no servers available for connection
authentication_test.go:56: Did not expect error during connect nats: no servers available for connection
=== RUN   TestAuthentication/Valid_jwt_and_invalid_seed
err: dial tcp [::1]:4222: connect: network is unreachable
=== RUN   TestAuthentication/Invalid_jwt_and_valid_seed
err: nats: no servers available for connection
--- FAIL: TestAuthentication (0.00s)
--- FAIL: TestAuthentication/Valid_jwt_and_valid_seed (0.00s)
--- PASS: TestAuthentication/Valid_jwt_and_invalid_seed (0.00s)
--- PASS: TestAuthentication/Invalid_jwt_and_valid_seed (0.00s)
FAIL
FAIL    github.com/dapr/components-contrib/tests/e2e/pubsub/jetstream/authentication    0.009s
FAIL
```
> optimize: add e2etests buildtags for e2e

- go.mod
- go.sum
- internal/eventbus/README.md
- internal/eventbus/event_bus.go
- internal/eventbus/event_bus_test.go
- pubsub/in-memory/in-memory.go
- pubsub/in-memory/in-memory_test.go
Updated the `pubsub.in-memory` component to support subscribing to wildcard topics. This will be needed for E2E tests in the runtime.
Note: this includes a partial fork `github.com/asaskevich/EventBus` (the library that was used before by the component) to include the required changes. Not the entire package was forked (just the 2 files that were needed), and some methods were removed.
Fixes #1964
> pubsub.in-memory: add support for wildcard topics

- lock/redis/standalone.go
- lock/responses.go
PR dapr/dapr#4989 (issue dapr/dapr#4988) updated the names of some
enums in `UnlockResponse.Status` ProtoBuff definition:
* `LOCK_UNEXIST` became `LOCK_DOES_NOT_EXIST `
* `LOCK_BELONG_TO_OTHERS`  became `LOCK_BELONGS_TO_OTHERS`
Code implementing Distributed Lock component in components-contrib
needs to be updated to account for this modification.
This PR accomplishes this by updating contants mapping back to the
two enums above to match their new names.
Fixes dapr/components-contrib#1950
Please reference the issue this PR will close: #1950 
> Update code to reflect renaming on UnlockResponse.Status

- internal/component/kafka/consumer.go
ConsumeClaim should not return err when retry recovery failed.
`ConsumeClaim` return error will cause restart loop of consume, if initialOffset is oldest, this message will be consumed forever. So we should log error and let it go like no retry does.
> fix(kafka): ConsumeClaim should not return err when retry recovery failed

- bindings/azure/servicebusqueues/servicebusqueues.go
- tests/certification/bindings/azure/servicebusqueues/README.md
- tests/certification/bindings/azure/servicebusqueues/servicebusqueue_test.go
This commit lets metadata bind to a message and be read when
the message is received. This allows for the distributed tracing
of events.
This is required for https://github.com/dapr/dapr/issues/4884.
Other binding/pubsubs will need to be examined but this was chosen
as the first attempt. Once the dapr changes are committed, we can go
through the other input bindings.
Signed-off-by: Hal Spang <halspang@microsoft.com>
This PR starts to address https://github.com/dapr/dapr/issues/4884 but requires changes in dapr/dapr after.
> Allow metadata to flow through service bus queue

- state/azure/cosmosdb/cosmosdb.go
- state/azure/cosmosdb/cosmosdb_test.go
Addresses some issue related to the handling of nulls / nil values on Cosmos DB State store. #1970 
- No longer treats empty / nil values as binary data on Set operations.
- Allows returning of nil values in Get operation.
- Falls back to returning raw string if a byte string cannot be decoded (in Get operation).
> Fix CosmosDB state store handling of nulls 

- state/mysql/mySQLFactory.go
- state/mysql/mysql.go
- state/mysql/mysql_integration_test.go
- state/mysql/mysql_test.go
- tests/config/state/tests.yml
This PR contains fixes (and general refactorings) to the MySQL state store. We should be able to mark this as beta now.
1. Improved sanitization of table and DB names, to prevent (self-inflicted, by an admin) SQL injections
2. Ensure component correctly handles first-write-wins concurrency (and enabled that in conf tests)
3. General cleanups
> Fixes to MySQL state store

- tests/certification/pubsub/azure/servicebus/go.mod
Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>
Corrected module name from servicebusqueue_test to servicebus_test in go mod file.
> Corrected module name in go mod file

- .github/infrastructure/docker-compose-rethinkdb.yml
- .github/workflows/conformance.yml
- state/rethinkdb/rethinkdb.go
- tests/config/state/rethinkdb/statestore.yml
- tests/config/state/tests.yml
- tests/conformance/common.go
This makes RethinkDB a Beta component.
Note:
RethinkDB does **not support ETag**. As such the ETag capability has been removed from the set of returned capabilities.
> Enable conformance tests for rethinkdb

- state/rethinkdb/rethinkdb.go
- tests/config/state/tests.yml
Rethinkdb state store: Remove falsely advertised transaction support
RethinkDB does not support multi-item / multi-document transactions and as such should not advertise transaction support.
> Rethinkdb state store: Remove falsely advertised transaction support

- .github/workflows/conformance.yml
Run conformance tests against master every 8 hours instead of 30 minutes.
Tests will still run on PR of course, and via `/ok-to-test`
> Reduce conformance test run frequency

- secretstores/aws/parameterstore/parameterstore.go
- secretstores/aws/parameterstore/parameterstore_test.go
Closes: #2001
I've created https://github.com/dapr/docs/issues/2763 as documentation is needed for this.
> Add prefix option to AWS SSM Parameter Store secret store component

- .github/workflows/components-contrib.yml
Disable broken go vulnerability check in workflow. Will eventually reenable
> Disable broken go vulnerability check in workflow

- bindings/alicloud/dingtalk/webhook/settings.go
- bindings/alicloud/nacos/settings.go
- bindings/alicloud/oss/oss.go
- bindings/alicloud/rocketmq/settings.go
- bindings/alicloud/sls/sls.go
- bindings/aws/dynamodb/dynamodb.go
- bindings/aws/kinesis/kinesis.go
- bindings/huawei/obs/obs.go
- bindings/influx/influx.go
- bindings/ipfs/metadata.go
- bindings/ipfs/operation-add.go
- bindings/ipfs/operation-get.go
- bindings/ipfs/operation-ls.go
- bindings/ipfs/operation-pin-add.go
- bindings/ipfs/operation-pin-ls.go
- bindings/ipfs/operation-pin-rm.go
- bindings/localstorage/localstorage.go
- bindings/zeebe/client.go
- bindings/zeebe/client_test.go
- bindings/zeebe/jobworker/jobworker.go
- metadata/duration.go
- metadata/utils.go
- metadata/utils_test.go
- pubsub/rocketmq/metadata.go
- secretstores/local/file/filestore.go
Fixes #2050
Original issue was introduced when adding request context in bindings. The mitchelh/mapstructure library does not natively support converting of `time.duration` and this PR had to add this.
> Fix Zeebe metadata duration issue & provide metadata parsing utility

- .github/workflows/conformance.yml
Add pubsub.redis conformance test accidentally removed in #2058
> Add pubsub.redis conformance test accidentally removed in #2058

- README.md
Includes image of contributors in Readme.md
This is just for fun. It makes it more apparent that this repo has a lot of contributors.
> Includes image of contributors in Readme.md

- .github/workflows/conformance.yml
- internal/component/kafka/producer.go
- pubsub/kafka/kafka.go
- tests/config/pubsub/tests.yml
- tests/conformance/pubsub/pubsub.go
Adding conformance for bulk publish. 
This is currently using the existing subscriber to subscribe to the bulk published events as well.
For the mapping of errors from kafka, I was able to manually modify the bulk publish conf test locally and simulate a partial failure for a single message. I did modify the max message size for producer also locally and made the single failure message larger than the accepted size. 
The BulkPublishResponse got from BulkPublish is as following 
```
{[{11 FAILED kafka server: Message was too large, server rejected it to avoid allocation error.} {12 SUCCESS <nil>} {13 SUCCESS <nil>} {14 SUCCESS <nil>} {15 SUCCESS <nil>} {16 SUCCESS <nil>} {17 SUCCESS <nil>} {18 SUCCESS <nil>} {19 SUCCESS <nil>} {20 SUCCESS <nil>}]}
```
Here 11 -> 20 are the entry IDs and …
> Adding conformance for bulk publish and properly map kafka errors on bulk publish

- internal/component/kafka/consumer.go
ConsumeClaim should also return when messages channel is closed, otherwise we will got nil message from a closed channel. This pr fix https://github.com/dapr/components-contrib/pull/2049#discussion_r978507084
> fix(kafka): ConsumeClaim should return when messages channel closed

- internal/utils/utils.go
- metadata/utils.go
- pubsub/azure/eventhubs/eventhubs.go
- pubsub/azure/eventhubs/eventhubs_test.go
For consistency, use request level metadata for bulk publish instead of component level. Note, the util has been copied from #2100.
Please reference the issue this PR will close: #2090 
> Azure Event Hubs bulk publish to use request metadata

- pubsub/rabbitmq/metadata.go
- pubsub/rabbitmq/metadata_test.go
- pubsub/rabbitmq/rabbitmq.go
- pubsub/rabbitmq/rabbitmq_test.go
Added `username` and `password` arguments to pubsub.rabbitmq metadata and provide it to `amqp.Dial`.
**Caution:** This is probably a breaking change because the `host` argument was missused to also include credentials.
Please reference the issue this PR will close: #1719
> Added username and password arguments to pubsub.rabbitmq metadata

- pubsub/envelope.go
- pubsub/envelope_test.go
Closes https://github.com/dapr/dapr/issues/5137
Signed-off-by: Yash Nisar <yashnisar@microsoft.com>
Add time to CloudEvent automatically if not present
https://github.com/dapr/dapr/issues/5137
Tested with dapr changes: https://github.com/dapr/dapr/commit/7cde7b7e8c0786334eb0e26304fa642a18674c24
Request:
```
dapr publish --publish-app-id order-processor --pubsub orderpubsub --topic orders --data '{"specversion" : "1.0", "type" : "com.dapr.cloudevent.sent", "source" : "testcloudeventspubsub", "subject" : "Cloud Events Test", "id" : "someCloudEventId", "datacontenttype" : "application/cloudevents+json", "data" : {"orderId": "100"}}'
```
Response:
```
INFO[0034] HTTP API Called: POST …
```
> Add time to CloudEvent automatically if not present

- tests/config/pubsub/tests.yml
Onboard the following conformance tests
1. Azure Event Hubs - Bulk Publish
2. Azure Service Bus - Bulk Publish and Bulk Subscribe
Main issue: dapr/dapr#2218
> Onboard Azure EH and SB to bulk pub/sub conformance tests

- .github/workflows/conformance.yml
Based on comment https://github.com/dapr/components-contrib/pull/2126#discussion_r982685145
> removing conf workflow run for PR targetting feature branch

- middleware/http/oauth2/oauth2_middleware.go
1. Use UUIDv4 (random) rather than UUIDv1 (time-based, predictable)
2. Correctly return in case of error
> Fixes in OAuth2 middleware

- configuration/redis/redis.go
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>
Using `PSubscribe` when a pattern is provided, else use `Subscribe`
Please reference the issue this PR will close: #1999
> fix redis subscribe all keys

- .github/workflows/certification.yml
- .github/workflows/conformance.yml
This is a follow-up on #2154 and changes how the bot reports the result.
The problem is that in this repo, there are many dozens of tests, so the bot was reporting a table with a lot of results. This could have easily caused information overload, making maintainers/approvers miss important information.
This PR changes how the bot reports the result.
If everything is successful, only a single checkmark is sent:
If at least one test fails, the status changes and only the list of failed components is shown:
Likewise, this also changes the bot to actually check that all tests that were triggered reported a status. Before, if a test for a component failed to report a result for whatever reason, it was not included in the output. Now, those are included as missing as well:
> Bot doesn't report full table of results

- internal/component/azure/servicebus/subscription.go
- pubsub/azure/servicebus/servicebus.go
(In draft until we complete validation with @halspang in the long-haul cluster)
In the long-haul clusters, we have seen that the pubsub app sometimes enters into a weird state.
The only relevant log message is that it begins receiving payloads from Azure Service Bus with 0 messages. When that happens, something else gets messed up.
This is an attempt to fix the issue by causing the ASB components to force-reconnect to ASB when they receive 0 messages. This means changing the behavior to assume the connection is down.
> Azure Service Bus: consider receiving 0 messages as an error that requires reconnecting

- go.mod
- go.sum
Remove unnecessary replace statements in `go.mod`
> Remove unnecessary replace statements in `go.mod`

- internal/component/kafka/auth.go
Signed-off-by: Sky Ao <aoxiaojian@gmail.com>
When auth is required, even the tls is not required, we need to set config.net.tls.enable=true.
https://github.com/dapr/components-contrib/issues/2182
> rollback code to set config.net.tls.enable=true when auth is required and tls is not required

- .github/workflows/fossa.yml
Only remove Fossa test temporarily. Results will still be available in the Fossa portal.
> Remove Fossa test temporarily

- go.mod
- go.sum
- pubsub/mqtt/mqtt.go
- tests/certification/pubsub/mqtt/go.mod
- tests/certification/pubsub/mqtt/go.sum
Signed-off-by: shivam <shivamkm07@gmail.com>
The fix in upstream mqtt component for disabling autoack was merged recently(https://github.com/eclipse/paho.mqtt.golang/pull/578). The PR upgrades the mqtt component to use the upstream instead of the fork
> Upgrade mqtt component to upstream

- .github/infrastructure/docker-compose-postgresql.yml
Postgres releases a new major version every year or so, and they sometimes have backwards-incompatible changes. When Postgres 15 came out a few days ago, our cert tests started to fail right away (the bug was in our tests making assumptions they should not have made).
This pins postgres to a specific version in our test infra so we can upgrade at our own pace.
Also adds a (commented-out) service for deploying pgadmin, useful for local debugging.
> Pin postgres version in test infra

- .build-tools/component-folders.json
- .github/workflows/certification.yml
- .github/workflows/conformance.yml
- bindings/azure/eventhubs/eventhubs_integration_test.go
- bindings/azure/servicebusqueues/servicebusqueues.go
- bindings/rabbitmq/rabbitmq_integration_test.go
- internal/component/azure/servicebus/handler_pubsub.go
- internal/component/azure/servicebus/message_pubsub.go
- internal/component/azure/servicebus/message_pubsub_test.go
- internal/component/azure/servicebus/message_test.go
- internal/component/azure/servicebus/metadata.go
- pubsub/azure/eventhubs/eventhubs_integration_test.go
- pubsub/azure/servicebus.queues/servicebus.go
- pubsub/azure/servicebus.topics/servicebus.go
- pubsub/azure/servicebus/queues/servicebus.go
- pubsub/azure/servicebus/topics/servicebus.go
- test.log
- tests/certification/pubsub/azure/servicebus/servicebus_test.go
- tests/config/pubsub/azure/servicebus/queues/pubsub.yml
- tests/config/pubsub/azure/servicebus/topics/pubsub.yml
- tests/config/pubsub/tests.yml
- tests/conformance/common.go
Creates a new component for using Azure Service Bus Queues as pubsub (before it was only available as a binding). Will be called `pubsub.azure.servicebus.queues`.
This PR's intent is to rename the existing `pubsub.azure.servicebus` component to `pubsub.azure.servicebus.topics` (maintaining the old name as alias for backwards-compatibility).
I also added conformance tests for the new component, which are passing, but won't be able to run with `/ok-to-test` in this PR because they require a pipeline change and the pipeline always runs from master. Here's the log when I run them locally: https://pastebin.com/ywQnHc66 (too big for GitHub to post here)
Fixes #2130
> New PubSub component: Azure Service Bus Queues

- nameresolution/mdns/mdns.go
- nameresolution/mdns/mdns_test.go
1. If the host doesn't support IPv6 (or supports only IPv6), allow the client to resolve IPs
3. Better concurrency handling with picking an address from the list via round-robin
> Fixes to mDNS resolver

- docs/developing-component.md
It's pretty common to get into different errors while tidying or building `dapr/dapr` with local `dapr/components-contrib`. Usually checking out the latest released version helps.
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>
> Add note how to avoid compatibility issues between repos

- pubsub/hazelcast/hazelcast.go
See #1808
(Doesn't close the issue yet, which will stay open until the component is actually removed)
> Add note that pubsub.hazelcast is deprecated

- .github/infrastructure/docker-compose-mariadb.yml
- .github/infrastructure/docker-compose-mysql.yml
- .github/workflows/conformance.yml
- tests/config/state/mysql/mariadb/statestore.yaml
- tests/config/state/mysql/mysql/statestore.yaml
- tests/config/state/tests.yml
- tests/conformance/common.go
Makes the conformance tests for state.mysql run against MariaDB too.
> Run conf tests for state.mysql against MariaDB too

- .github/workflows/certification.yml
Signed-off-by: zhangchao <zchao9100@gmail.com>
These protobuf registration conflict warning outputs in certification tests are useless, change GOLANG_PROTOBUF_REGISTRATION_CONFLICT to ignore can disable these logs.
```
WARNING: proto: file "dapr/proto/runtime/v1/dapr.proto" has a name conflict over dapr.proto.runtime.v1.ActiveActorsCount
previously from: "github.com/dapr/dapr/pkg/proto/runtime/v1"
currently from:  "github.com/dapr/go-sdk/dapr/proto/runtime/v1"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```
Please make sure you've completed the …
> change GOLANG_PROTOBUF_REGISTRATION_CONFLICT from warn to ignore

- pubsub/aws/snssqs/snssqs.go
Multiple users of the AWS SQS component reported a regression caused by this commit: https://github.com/dapr/components-contrib/commit/704f4dd7307d96252d7cc92cf792fcfdebea3c6c.
Fixes https://github.com/dapr/components-contrib/issues/2266.
> Fix deletion of sqs queue regression

- bindings/azure/storagequeues/storagequeues.go
- tests/certification/bindings/azure/storagequeues/components/decode/azure_queue_storage.yaml
- tests/certification/bindings/azure/storagequeues/storagequeue_test.go
Adds base64 encoding option for Service Bus Queues binding
Fixes #2249
> Storage Queues Binding: Add b64encoding option for messages

- .github/workflows/conformance.yml
- .golangci.yml
- bindings/kubemq/kubemq.go
- bindings/kubemq/kubemq_integration_test.go
- bindings/kubemq/kubemq_test.go
- bindings/kubemq/options.go
- tests/config/bindings/kubemq/binding.yml
- tests/config/bindings/tests.yml
- tests/conformance/common.go
Signed-off-by: Lior Nabat <lior.nabat@gmail.clom>
This PR is to add KubeMQ Binding - Queue feature to DAPR.
This PR passed:
1. make lint
2. make test
3. go test -v -tags=conftests -count=1 ./tests/conformance -run="TestBindingsConformance/kubemq"
* [ x] Code compiles correctly
* [ x] Created/updated tests
> Adding KubeMQ Binding - Queue

- bindings/azure/cosmosdb/cosmosdb.go
- state/azure/cosmosdb/cosmosdb.go
- state/azure/tablestorage/tablestorage.go
User agents were not implemented when migrating to the Track 2 SDKs for CosmosDB. This sets the Dapr version user agent.
> Adding CosmosDB and TableStorage Dapr User Agents

- bindings/azure/storagequeues/storagequeues.go
- bindings/azure/storagequeues/storagequeues_test.go
Adds ability to configure the Azure Storage Queue visibility timeout via `visibilityTimeout` metadata option. Default remains at 30 seconds.
Fixes #2259
> ASQ Binding: Make visibilityTimeout configurable

- tests/certification/bindings/azure/storagequeues/components/visibilityTimeout/azure_queue_storage.yaml
- tests/certification/bindings/azure/storagequeues/components/visibilityTimeout/localsecrets.yaml
- tests/certification/bindings/azure/storagequeues/storagequeue_test.go
- tests/certification/flow/watcher/watcher.go
Adds certification test case for Azure Storage Queues Binding's queue visibilityTimeout option.
Also fixes major bug in certification test framework. Previously `watcher.FailIfNotExpected` which is used to ensure no unexpected data / events were delivered in the case of an Unordered Queue never actually failed when unexpected data was sent.
This will likely result in other certification tests failing, but if so I will be opening separate issues for those failures and ask various team members to address accordingly.
> ASQ Binding: Cert Test: Add queue visibilityTimeout test

- state/postgresql/postgresdbaccess.go
- state/postgresql/postgresql_query.go
- state/postgresql/postgresql_query_test.go
- tests/config/state/tests.yml
Postgres State Store: Add Support for First-Write concurrency
Allows table name to be customized.
fixes #1163
> Postgres State Store: Add Support for First-Write concurrency

- bindings/rabbitmq/rabbitmq_integration_test.go
- pubsub/azure/eventhubs/eventhubs_integration_test.go
- state/cockroachdb/cockroachdb_access.go
- state/gcp/firestore/firestore.go
- state/memcached/memcached.go
- state/mysql/mysql.go
- state/oracledatabase/oracledatabaseaccess.go
- state/postgresql/postgresdbaccess.go
- state/postgresql/postgresql_query.go
- state/redis/redis.go
- state/request_options.go
- state/request_options_test.go
- state/zookeeper/zk.go
- Removed `state.DeleteWithOptions` and `state.SetWithOptions` which were useless at this point (likely a leftover from when there were retries, but now they're just "passthrough" functions)
- Some improvements in etag handling in Postgres
- Other minor refactorings
Also fixed syntax errors in `bindings/rabbitmq/rabbitmq_integration_test.go`  and `pubsub/azure/eventhubs/eventhubs_integration_test.go`. Those files are unused but they kept popping up as errors in VS Code's "problems" tab
> Some misc refactorings in state stores

- .github/scripts/dapr_bot.js
- .github/workflows/dapr-bot.yml
Dapr bot in contrib should also get triggered on adding labels to PRs. This also adds support for handling "new component" and creating an issue in dapr/dapr.
Closes #2209
> Dapr bot support labels on PRs, add support for "new component"

- pubsub/mqtt/mqtt.go
Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>
Retained Message is the responsibility of broker, where-in the concept is to simply add a flag `Retain` to a message, so that when a new subscriber comes in or a subscriber re-connects, this retained message is played. 
Hence, here in daprd, we still need to ACK a Retained message.
Please reference the issue this PR will close: #2300 
> Mqtt pub/sub: Ack Retained Messages

- state/azure/cosmosdb/cosmosdb.go
- tests/certification/state/azure/cosmosdb/cosmosdb_test.go
Signed-off-by: Ryan Lettieri <ryanLettieri@microsoft.com>
Changed an asterisk to an ampersand to fix a nil pointer being dereferenced.
When attempting to create a state transaction request in cosmosDB with an etag, a nil pointer was being dereferenced.
This PR will close: #[_[2319]_](https://github.com/dapr/components-contrib/issues/2319)
> Hotfix: Cosmosdb StateTransactionRequest with etag crash

- secretstores/hashicorp/vault/vault_test.go
Tests in `vault_test.go` had the following:
```go
// This call will throw an error on Windows systems because of the of
// the call x509.SystemCertPool() because system root pool is not
// available on Windows so ignore the error for when the tests are run
// on the Windows platform during CI
_ = target.Init(m)
```
As of Go 1.18 this is not the case for Windows anymore and
we can instead enforce error checking. References:
* https://github.com/golang/go/issues/16736
* https://github.com/golang/go/issues/18609
* https://github.com/rancher/system-agent/pull/84
* https://github.com/jaegertracing/jaeger/pull/2756
Given Dapr depends on Go 1.19, we can enforce tests on `Init` result
and remove this comment.
While enforcing error checking we notice that the code above was
actually hiding errors …
> Enforce error checking for Vault component initialization on tests.

- bindings/http/http.go
- bindings/http/http_test.go
Adding support for an optional metadata field `treatNon200AsError` that will prevent the binding from returning an error object when the upstream service returns a non-2xx error; this component keeps the existing behavior by default (i.e a 500 or other status code will result in an error being returned), which will unfortunately swallow the HTTP server's response. 
This is related to an issue opened in the Java SDK (https://github.com/dapr/java-sdk/issues/783) -- while this won't fix the open issue immediately it will allow for clients to decide if they want to receive the response object even if the response is not 2xx. 
> Allow non-200 responses to be treated as non-errors

- go.mod
- go.sum
- middleware/http/ratelimit/ratelimit_middleware.go
We need to set a value for the X-Forwarded-For header or the upstream library won't rate-limit requests. Additionally, upgraded the tollbooth library to v7.
Fixes #2343
> Fix ratelimit middleware not working

- pubsub/mqtt/metadata.go
- pubsub/mqtt/mqtt.go
- tests/certification/pubsub/mqtt/mqtt_test.go
- tests/config/pubsub/mqtt/mosquitto/pubsub.yml
Extracted from #2350 with the fix for the MQTT PubSub component only
The fix for the MQTT binding component will not be included in the hotfix
> [Hotfix release-1.9] MQTT PubSub: Resume subscriptions after a reconnection

- go.mod
- go.sum
Revert #2398 because wazero 1.0.0-pre.6 (and pre.7) do not compile on Linux Arm (not Arm64).
FYI @codefromthecrypt
> Revert wazero dependency to 1.0.0-pre.4

- pubsub/jetstream/jetstream.go
- pubsub/jetstream/metadata.go
- pubsub/jetstream/metadata_test.go
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>
Adds ability to setup domain and api prefix for JetStream.
This would still require two instances of JetStream - one for publishing, targeted at original stream and one domain with a mirror.
https://github.com/dapr/components-contrib/issues/2265
> Add domain and apiPrefix for JetStream

- .github/infrastructure/terraform/certification/pubsub/aws/snssqs/snssqs.tf
- .github/workflows/certification.yml
- tests/certification/pubsub/aws/snssqs/README.md
- tests/certification/pubsub/aws/snssqs/components/existing_queue/localsecrets.yaml
- tests/certification/pubsub/aws/snssqs/components/existing_queue/pubsub.yaml
- tests/certification/pubsub/aws/snssqs/snssqs_test.go
Provides the AWS SNS/SQS PubSub Certification Test Plan and Test Code. 
Tests for Existing Queue and Topics.
It depends on issue #2282 
This PR makes progress towards #1339 and #1971 but does not complete these. More component metadata tests will need to be added.
> AWS SNS/SQS PubSub Certification Tests - Exiting Queue/Topics tests

- tests/certification/state/azure/blobstorage/components/aadtest/blobaad.yaml
State Azure Blob Cert test: AAD test was not actually using AAD
Fix certification test.
> Fix State Azure Blob cert test

- internal/component/azure/servicebus/subscription.go
Signed-off-by: Joni Collinge <jonathancollinge@live.com>
[Reverts changes to active message snapshotting](https://github.com/dapr/components-contrib/pull/2346#discussion_r1052712437) as `activeMessages` is a map of message sequence number -> message and is being flattened to a slice. Reference: https://github.com/dapr/components-contrib/pull/2438#discussion_r1070259105. cc: @mukundansundar 
> Fix bug in ASB pubsub

- go.mod
- go.sum
- tests/certification/bindings/alicloud/dubbo/go.mod
- tests/certification/bindings/alicloud/dubbo/go.sum
Fixes #2425
Addresses the Apache Dubbo Binding CVE (though Dapr isn't vulnerable to it) by replacing the UUID package used.
This updates the Dubbo library to the latest commit in the `dapr-support` branch, based on my PR https://github.com/apache/dubbo-go/pull/2181.
> Addresses UUID CVE in Apache Dubbo Binding

- internal/component/azure/servicebus/subscription.go
Moves the ASB implementation to use sync.Map instead of native map and mutex to handle active message tracking. This is because we've been seeing crashes in the E2E related to the active message access (even when all writes are protected a write mutex and all read protected by a read mutex 🤔). I can confirm that this change DOES stop the sidecar crashing during the Azure E2E. However, it DOES NOT fix the Azure E2E tests. They still fail. I've also ran the E2E tests against 1.9.5 and they also fail and do not include the most recent changes.
UPDATE: Interestingly reverting to using `append` also stops the crash.
Please …
> Use sync.Map for ASB active messages

- bindings/localstorage/localstorage.go
- bindings/localstorage/localstorage_test.go
- tests/certification/bindings/localstorage/components/localstorage.yaml
- tests/certification/bindings/localstorage/localstorage_test.go
1. Adds checks and enforcements on rootPath. Also includes ability to disallow certain root paths such as `/var/run/secrets` (also if there are symlinks to those paths)
2. Closes file descriptor that was left open after reading a file
3. If the file doesn't exist when reading it, returns a more specific error message
Fixes #2444
Fixes #2374
> bindings.localstorage fixes

- metadata/utils.go
This method is used by paths including the one that checks for Azure AD credentials. This makes the keys case-insensitive so the matching is more lenient (e.g. `azureClientId` vs `azureClientID`)
> Make keys in GetMetadataProperties case-insensitive

- bindings/http/http.go
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>
This check here is little problematic - 
https://github.com/dapr/components-contrib/blob/7067334215da45305c687498fb538b35231c8080/bindings/http/http.go#L157
It might be possible that the the pem bytes that are passed are large in length, in that case the condition will evaluate to `true` and it will return from here. Where as we would want it to treat as pembytes in next line.
I was aable to reproduce it with self signed cert with open ssl.
The error logged will be something like - 
```text
failed to read "MTLSRootCA" file: open -----BEGIN CERTIFICATE-----
MIICHzCCAcWgAwIBAgIUVmulwhIO5Y2A8ACi3OcX94denFEwCgYIKoZIzj0EAwIw
......
IsCxyWZQ37yZpvS82Z/SnCIZuw==
-----END CERTIFICATE-----
: file name too long
```
We can invert the logic like …
> [HTTP Binding] fix error: filename too long

- nameresolution/mdns/mdns.go
Quick fix related to the work on shutdown improvements.
Currently the mDNS resolver is the only (left) component that listens to shutdown signals via the OS (like os.Interrupt), rather than shutting down on context cancellation. This fixes it so the component shuts down in a more streamlined way.
> mdns: shut down on context cancelation and not on signal

- state/gcp/firestore/firestore.go
- state/gcp/firestore/firestore_test.go
Adds `noindex` boolean metadata property to prevent the value from being indexed.
Closes #2478
> Firestore State Store: Adds `noindex` option to skip indexing of value.

- state/sqlite/sqlite_dbaccess.go
This makes SQLite behave more like Postgres, where the "expiration_time" column does not have an index by default.
For an explanation on why: https://v1-10.docs.dapr.io/reference/components-reference/supported-state-stores/setup-postgresql/#ttls-and-cleanups
> [release-1.10] SQlite: do not create an index on expiration_time by default

- bindings/azure/servicebusqueues/servicebusqueues.go
- internal/component/azure/servicebus/client.go
- internal/component/azure/servicebus/errors.go
- pubsub/azure/servicebus/queues/servicebus.go
- pubsub/azure/servicebus/topics/servicebus.go
This PR is an attempt at fixing #2483 , although I am not able to repro the issue so I can't validate this. The approach is two-fold:
1. We are already treating "context deadline exceeded" errors as errors that would require disconnecting and reconnecting. However, it seems that the check `errors.Is(err, context.DeadlineExceeded)` may not be detecting those errors, perhaps because an upstream library is wrapping the errors some way. Based on looking into how the Service Bus SDK works, I've seen a sign that something like that may be happening. So, I've changed the code to be more lax and also accept errors whose stringified message is "context deadline exceeded" (but which are not  context.DeadlineExceeded) as errors that would require reconnecting.
2. In parallel, I've added more logs …
> [release-1.10] Fix "Azure Service Bus does not recover from failures when publishing"

- bindings/azure/servicebusqueues/servicebusqueues.go
- internal/component/azure/servicebus/errors.go
- pubsub/azure/servicebus/servicebus.go
Backports #2487 into release-1.9 for a hotfix
Because the components were heavily refactored, the fix was ported manually as a new code change
> [release-1.9] Backport fix for Azure Service Bus

- bindings/azure/eventgrid/eventgrid.go
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
Make use of CloudEvent content header constant to avoid duplication
Please reference the issue this PR will close: #2496
> Refactor: Make use of CloudEvent content header constant to avoid code duplication

- bindings/localstorage/localstorage.go
- bindings/localstorage/localstorage_test.go
Fixes a regression introduced in #2449 which accidentally made it not possible to use relative paths.
> [release-1.10] bindings.localstorage: allow relative paths agian

- .github/scripts/dapr_bot.js
- .github/workflows/certification.yml
- .github/workflows/components-contrib-all.yml
- .github/workflows/components-contrib.yml
- .github/workflows/conformance.yml
Changes below:
On every PR against Master
- Only run tests against Linux AMD64 (Use `/ok-to-test` for complete test matrix)
- Do not run certification tests. (Use `/ok-to-test` for all certification tests as necessary).
PR and Push against `Release-*`:
- Run complete build test matrix
- Run non-cloud certification tests
- Run non-cloud conformance tests
Using `/ok-to-test`:
- Runs complete build test matrix
- Runs complete conformance test matrix
- Runs complete certification test matrix
Scheduled runs:
- Conformance (full matrix) every 8 hours
- Certification (full matrix) every 8 hours
- Build / Lint / Unit test (full matrix) every 6 hours
> Reduce default contrib test runs on PR. Moves them to `/ok-to-test` and scheduled runs.

- internal/component/azure/servicebus/errors.go
- internal/component/azure/servicebus/receiver.go
- internal/component/azure/servicebus/subscription.go
Fixes #2532
Improves ASB lock renewal in a few ways to improve the user experience:
- Reduce the likelihood of users seeing warning messages in the logs saying that lock renewal failed if the message was already completed in the meanwhile. This is done by:
- After taking the snapshot, check if the message is still active before attempting to renew the locks
- Improved the error message in case of "locklost" errors, to make it more concise and explain more clearly than this is not a serious issue in _most_ cases. 
- Before: "WARN[0100] Error renewing message locks for topic topic2: couldn't renew active message lock for message 22de340330524da39a28dd86bdf36fd1, (locklost): rpc: failed, status code 410 and description: The lock supplied is invalid. Either the lock expired, or the message …
> [release-1.10] Improve lock handling and renewal for ASB messages (fix #2532)

- bindings/http/http.go
- bindings/http/http_test.go
HTTP Binding
Makes the timeout waiting for a response customizable via metadata `responseTimeout`. The value is a duration of the form `1s`, `5m` etc.
> HTTP binding: Make response timeout customizable

- docs/developing-component.md
Fixing broken links on the development doc:
#2559 was created for the defect
> Fix broken links to bindings tutorial

- docs/developing-component.md
As suggested by @berndverst just linking to the repo. I linked to the bindings quickstart, instead of a specific app (E.g. the node app like before)
Follow up PR from https://github.com/dapr/components-contrib/pull/2560, based on feedback from @berndverst in #2559
> Just pointing to the bindings tutorial

- go.mod
- go.sum
This PR updates [wazero](https://wazero.io/) to [1.0.0-pre.9][1]. Notably:
* This release includes our last breaking changes before 1.0.0 final:
* Requires at least Go 1.18
* This release also integrates Go context to limit execution time. More details on the [Release Notes][1]
* We are now passing third-party integration test suites: wasi-testsuite, TinyGo's, Zig's.
It also updates [http-wasm](https://http-wasm.io) to [3.3.0][2], which syncs to wazero 1.0.0-pre.9
[1]: https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.9
[2]: https://github.com/http-wasm/http-wasm-host-go/releases/tag/v3.3.0
It is a trivial change, so I haven't created an issue, but will do if necessary
> deps: updates wazero to 1.0.0-pre.9, http-wasm-host-go to v3.3.0

- .github/workflows/certification.yml
- .github/workflows/conformance.yml
The branch with Node.js 16 seems to not work well. We will live with a version that shows a warning in the meanwhile.
> Downgrade AWS action in cert/conf tests

- .github/workflows/components-contrib.yml
- .github/workflows/conformance.yml
Tiny workflow change for merge queue triggers.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
> Merge queue support for required workflows

- state/cockroachdb/cockroachdb.go
- state/cockroachdb/cockroachdb_access.go
- state/cockroachdb/cockroachdb_access_test.go
- state/cockroachdb/cockroachdb_integration_test.go
- state/cockroachdb/cockroachdb_query.go
- state/cockroachdb/cockroachdb_query_test.go
- tests/certification/state/cockroachdb/README.md
- tests/certification/state/cockroachdb/cockroachdb_test.go
- tests/config/state/tests.yml
Part of the larger [issue](https://github.com/dapr/dapr/issues/5899) and https://github.com/dapr/components-contrib/issues/2288.
Adds TTL support to the cockroachDB state store by running a garbage collector which runs at a configurable interval, which deletes items saved.
Cleanups are coordinated in a new `dapr_metadata` table.
Follows much of the same implementation as [postgres](https://github.com/dapr/components-contrib/pull/2302)
Docs PR:  https://github.com/dapr/docs/pull/3226
/cc @ItalyPaleAle
> Adds TTL support to the CockroachDB state.

- go.mod
- go.sum
- internal/authentication/azure/auth.go
- internal/authentication/azure/auth_test.go
- tests/certification/bindings/azure/blobstorage/go.mod
- tests/certification/bindings/azure/blobstorage/go.sum
- tests/certification/bindings/azure/cosmosdb/go.mod
- tests/certification/bindings/azure/cosmosdb/go.sum
- tests/certification/bindings/azure/eventhubs/go.mod
- tests/certification/bindings/azure/eventhubs/go.sum
- tests/certification/bindings/azure/servicebusqueues/go.mod
- tests/certification/bindings/azure/servicebusqueues/go.sum
- tests/certification/bindings/azure/storagequeues/go.mod
- tests/certification/bindings/azure/storagequeues/go.sum
- tests/certification/pubsub/azure/eventhubs/go.mod
- tests/certification/pubsub/azure/eventhubs/go.sum
- tests/certification/pubsub/azure/servicebus/topics/go.mod
- tests/certification/pubsub/azure/servicebus/topics/go.sum
- tests/certification/secretstores/azure/keyvault/go.mod
- tests/certification/secretstores/azure/keyvault/go.sum
- tests/certification/state/azure/blobstorage/go.mod
- tests/certification/state/azure/blobstorage/go.sum
- tests/certification/state/azure/cosmosdb/go.mod
- tests/certification/state/azure/cosmosdb/go.sum
- tests/certification/state/azure/tablestorage/go.mod
- tests/certification/state/azure/tablestorage/go.sum
This adds an additional authentication method after MSI attempted: Azure CLI credential
This is particularly helpful for using Dapr locally in development.
Fixes #2469
Because the ChainedTokenCredential attempts auth methods sequentially we do not obtain the ManagedIdentityCredential and CLICredential this way -- instead we run these in parallel in different go routines. Whichever method finishes first is used.
NOTE
This PR needs to be revert if Azure SDK for GO / azidentity 1.3.0 is not released and used by Dapr 1.11 release time. This PR uses 1.3.0-Beta.3 and needs to be updated.
> Dapr 1.11: Support Azure CLI Credential for Azure Track 2 components

- state/redis/redis.go
As discussed with @yaron2 we are adding a warning to the `Multi` (transaction) interface for Redis to warn users that Redis is not transactional and should not be used as actor state store.
> Addition to Hotfix 1.10.3: Add warning to Redis State Store: Do not use as Actor State

- go.mod
- go.sum
- tests/certification/bindings/azure/servicebusqueues/go.mod
- tests/certification/bindings/azure/servicebusqueues/go.sum
- tests/certification/pubsub/azure/servicebus/topics/go.mod
- tests/certification/pubsub/azure/servicebus/topics/go.sum
Fixes #2617 
By upgrading Azure service Bus SDK to 1.2.1
> [Release 1.10] Upgrade service bus SDK to 1.2.1

- internal/component/kafka/auth.go
- internal/component/kafka/auth_test.go
- internal/component/kafka/kafka.go
- internal/component/kafka/metadata.go
- internal/component/kafka/metadata_test.go
- pubsub/jetstream/metadata.go
Restore Kafka CA Cert Auth without Password Support by introducing new auth type `certificate`
Fixes #2639 
Fixes #2645 
For Hotfix 1.10.3
> Restore Kafka CA Cert Auth without Password support, fix Jetstream pubsub issue

- bindings/azure/blobstorage/blobstorage.go
- state/azure/blobstorage/blobstorage.go
- state/mongodb/mongodb.go
Some `context.TODO()`s slipped through when merging https://github.com/dapr/components-contrib/pull/2474
> Remove `context.TODO()`s with passed context.

- bindings/redis/redis.go
- bindings/redis/redis_test.go
- tests/certification/bindings/redis/components/retryOptions/redis.yaml
- tests/certification/bindings/redis/components/standard/redis.yaml
- tests/certification/bindings/redis/docker-compose.yml
- tests/certification/bindings/redis/redis_test.go
Adds "increment" operation for Redis Binding.
Also adds TTL support for "create" and "increment" operation via the standard "ttlInSeconds" request metadata.
Unit tests and certification test updates included. Also updates certification test to a different Redis port so not to clash with Redis already installed via Dapr CLI.
#2537 
> Support Increment Operation, TTL in Redis Binding

- internal/authentication/azure/auth.go
Azure Workload Identity Support
Fixes #1567
The implementation here comes directly from the Azure SDK for Go. I have manually verified in my AKS cluster that I am able to authenticate using Workload Identity from the Dapr sidecar!
> Add support for Workload identity

- .devcontainer/devcontainer.json
- tests/certification/state/sqlite/sqlite_test.go
Fixes #2628
The race condition was in the tests and not in the component itself.
PS: Also includes fixing a typo in devcontainer.json. Since otherwise I couldn't run the tests in a dev container / codespace
> Fixed race condition in SQLite cert test

- tests/conformance/workflows/workflows.go
- workflows/requests.go
- workflows/temporal/temporal.go
- workflows/workflow.go
Reverts dapr/components-contrib#2653
Because https://github.com/dapr/dapr/pull/6049 is no close to being ready to be merged, and with this PR merged in master our cert tests are broken (and so is our ability to merge any PR in dapr/components-contrib), we are going to revert this PR.
Once the runtime PR is ready, please re-open a PR to get the changes merged
This is @berndverst and I's decision
> Revert "Creation of request and interface method for Workflow raise event"

- bindings/graphql/graphql.go
- bindings/graphql/graphql_test.go
previous pr: #2522; rebased against master so couldn't re-open previous pr
attempt to idiomatically add support for graphql variables in the bindingrequest's metadata to help prevent injection attacks as outlined in https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#injection-prevention
Please reference the issue this PR will close: #2517
> graphql binding variable support

- state/sqlserver/migration.go
- state/sqlserver/sqlserver_test.go
> SQL Server: case-insensitive matching for `database` in connstring

- .github/infrastructure/docker-compose-oracledatabase.yml
- .github/scripts/test-info.mjs
- go.mod
- go.sum
- state/oracledatabase/dbaccess.go
- state/oracledatabase/oracledatabase.go
- state/oracledatabase/oracledatabase_integration_test.go
- state/oracledatabase/oracledatabase_test.go
- state/oracledatabase/oracledatabaseaccess.go
- state/sqlite/sqlite_dbaccess.go
- tests/config/state/oracledatabase/statestore.yml
- tests/config/state/tests.yml
- tests/conformance/common.go
- tests/conformance/state/state.go
> Spin-off from #2688 as while working on that, I noticed the issues were much bigger than originally thought
Contains a large number of fixes, some critical, to the component:
- State table name was hardcoded rather than read from the metadata
- Transactions had queries executed in the wrong order: first all sets, then all deletes
- Transactions were not concurrency-safe, since the transaction handler was stored as property in the object
- TTLs were not updated when a row was updated
- Lots more fixes
Conformance tests are now enabled and passing for the component
> Many fixes to Oracle Database state store - now beta

- nameresolution/kubernetes/kubernetes.go
- nameresolution/kubernetes/kubernetes_test.go
Very small perf tweaks to K8s nameresolver.
```
Before:
BenchmarkResolve-4   3176529      377.0 ns/op   104 B/op   5 allocs/op
After:
BenchmarkResolve-4   10297288     115.0 ns/op   52 B/op   2 allocs/op
```
It's 70% faster. Although we're still talking about 262ns :) Also, causes 3 less allocations on the heap (less work on the GC).
> Small perf tweaks to K8s nameresolver

- .github/scripts/test-info.mjs
- crypto/azure/keyvault/algorithms.go
- crypto/azure/keyvault/component.go
- crypto/azure/keyvault/jwk.go
- crypto/azure/keyvault/metadata.go
- crypto/pubkey_cache.go
- go.mod
- go.sum
- tests/config/crypto/azure/keyvault/azure-keyvault.yaml
- tests/config/crypto/tests.yml
- tests/conformance/common.go
Spin-off from #2237
Includes a new SubtleCrypto component for Azure Key Vault, which uses keys stored within the vault (as keys, so the key material never leaves the vault and all operations are performed within the vault).
Conformance tests are enabled.
> Note that conformance tests are enabled for asymmetric ciphers only. Although Azure Key Vault supports symmetric ciphers too (AES), they are only available in the "Managed HSM" tier, which is insanely expensive and not suitable for our CI.
> Crypto component for Azure Key Vault

- bindings/wasm/output.go
- bindings/wasm/output_test.go
- go.mod
- go.sum
This updates [wazero](https://wazero.io/) to [1.0.0](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0) which begins our compatability promise.
On behalf of everyone in the community, I want to thank you for trying wazero before we became stable. We will not raise unsolicited pull requests anymore. That said, if any update gives you problems, please feel free to contact [us](https://wazero.io/community/) on slack or via a GitHub issue.
```bash
$ go test -run='^$' -bench '^Benchmark.*' ./bindings/wasm ./middleware/http/wasm -count=6 > old.txt
$ go test -run='^$' -bench '^Benchmark.*' ./bindings/wasm ./middleware/http/wasm -count=6 > new.txt
$ benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: github.com/dapr/components-contrib/bindings/wasm
│   old.txt   │ …
```
> deps: updates wazero to 1.0.0

- configuration/azure/appconfig/appconfig.go
- configuration/azure/appconfig/appconfig_test.go
- configuration/azure/appconfig/metadata.go
- configuration/postgres/metadata.go
- configuration/postgres/postgres.go
- configuration/postgres/postgres_test.go
- configuration/redis/metadata.go
- configuration/redis/redis.go
- configuration/redis/redis_test.go
- configuration/store.go
- lock/redis/standalone.go
- lock/store.go
- metadata/utils.go
Standardized the metadata parsing in configstores and lockstores.
Adds the `GetComponentMetadata` interface method required for checking the validity of `metadata.yaml` files.
> Standardize metadata parsing in configstores and lockstore

- secretstores/kubernetes/metadata.yaml
Create component metadata for secretstores.kubernetes.
This component seems to require no specific metadata to work so I left metadata **empty**.
Please reference the issue #2586 .
> Create component metadata for secretstores.kubernetes

- internal/component/postgresql/postgresql.go
- tests/certification/state/cockroachdb/cockroachdb_test.go
- tests/certification/state/cockroachdb/go.mod
We don't need this (it was a leftover from when we were using pgx as a db/sql driver).
Removing this is actually gonna reduce our memory footprint.
> Remove pgx/stdlib import

- state/rethinkdb/rethinkdb.go
- state/rethinkdb/rethinkdb_test.go
The implementation of the "Multi" method in RethinkDB was not correct, as it caused operations to be executed in the wrong order and it was not using a transaction (per comment on code: `best effort, no transacts supported`)
In essence, RethinkDB was not supporting transactions, and advertising the existence of the Multi method can cause users to believe it does, with dangerous potentials for data loss.
> RethinkDB: Disable transactions that were not working

- secretstores/hashicorp/vault/vault.go
Tiny fix when vault kv prefix is empty, found this when debugging #2711. When disables the `vaultKVUsePrefix`, formatting a URL like `http://localhost:8200/v1/secret/data//mysecret` will cause a redirect to `http://localhost:8200/v1/secret/data/mysecret`, which means sending 2 requests every time getting a secret.
Please reference the issue this PR will close: #N/A
> Fix vault prefix empty

- state/alicloud/tablestore/tablestore.go
Currently, the Alicloud table store state backend did not implement the interface related to `state.FeatureTransactional` feature, causing Dapr to fail to launch.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/6138
> disable featureTransactional in alicloud tablestore statae backend

- .github/workflows/certification.yml
- .github/workflows/conformance.yml
The coverage reports workflow runs weekly and uses the conformance and certification test coverage of last successful run. But currently the retention days of the reports published is set to 1, and so if all scheduled runs of cert or conf failed one day before running the coverage reports workflow(scheduled cert tests have been failing too much recently: https://github.com/dapr/components-contrib/actions/workflows/certification.yml?query=event%3Aschedule) , it fails. e.g. run: https://github.com/dapr/components-contrib/actions/runs/4585905816/jobs/8098332455
The PR increases the retention days to 7 so that it picks up any scheduled successful run in last 7 days.
We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to …
> Increase code_cov retention time

- internal/component/sql/cleanup.go
- state/sqlserver/sqlserver.go
MS SQL requires parameters in the query to be named, while MySQL wants them positional. This changes the internal/component/sql package to support both.
Fixes our cert tests not working in master at the moment: https://github.com/dapr/components-contrib/actions/runs/4610099241
> Fixes MS SQL TTL not working

- internal/component/kafka/metadata.go
- internal/component/kafka/metadata_test.go
Fixes a regression introduced in #2720 (unreleased) that caused Kafka to ignore the "consumerID" property set by the Dapr runtime when "consumerGroup" is not present.
> Fix Kafka ignoring "consumerID"

- secretstores/local/env/envstore.go
- secretstores/local/env/envstore_test.go
- secretstores/local/env/metadata.yaml
Adds a new option to the Local Env secret store to limit operations to keys with a given prefix.
For example, if the component is initialized with the metadata `prefix="MYAPP_"`, then:
- `Get` with key `FOO` will look for `MYAPP_FOO`. The result will be still returned as `FOO` (i.e. the prefix name is removed from the returned values)
- `GetBulk` will only return env vars with the prefix `MYAPP_` (which is stripped from the returned value)
Also included:
1. Added `metadata.yaml` for the component
2. The denylist now denies every secret that starts with `DAPR_` (after resolving the prefix), for future-proofing the component.
Tests have been included in the unit tests for the component
Docs issue: dapr/docs#3329
> Env secret store: add "prefix" metadata option (+ metadata.yaml)

- bindings/azure/signalr/metadata.yaml
- bindings/azure/signalr/signalr.go
Also two small fixes:
- Ensures that HTTP client uses at least TLS 1.2
- Removes prefix from logs, since in Dapr 1.10+ the component name is automatically included in logs
> Add metadata for bindings.azure.signalr

- secretstores/local/env/envstore.go
- secretstores/local/env/envstore_test.go
- secretstores/local/env/metadata.yaml
Looks like when matching env vars, Windows is case-insensitive, while other OS's are case-sensitive.
Changed the component and tests to maintain that behavior. Should fix test failures on Windows.
> Fix prefix on local env secret store on Windows

- state/azure/blobstorage/metadata.yaml
FYI @tmacam - this fixes up your metadata contribution.
cc @ItalyPaleAle
The command `make bundle-component-metadata` did not work because the number value was a number and not a string of a number.
> fixup: even numbers must be strings in metadata

- internal/component/postgresql/postgresdbaccess.go
- tests/certification/state/cockroachdb/cockroachdb_test.go
Fixes #2773
During upsert with etag, if no DB error is returned and rows affected is 0 an ETAG Mismatch error should be thrown.
This fixes that.
> fix postgres error handling for upsert with etag

- .build-tools/pkg/metadataschema/schema.go
- component-metadata-schema.json
We noticed the need for a better way of flagging deprecated properties
in metadata.yaml files other than adding "Deprecated" to their
`description`s. This is also helps when working with properties
that have aliases by marking undesired aliases as `deprecated`,
thus helping convergence to the preferred property names.
Related to PR #2784
> Adds new property "deprecated" to Metadata schema.

- state/mongodb/metadata.yaml
- state/postgresql/metadata.yaml
Improves metadata YAML for state.postgresql
* Move ConnectionString to Auth. Profiles
* Move Defaults from description into `default` fields.
* Fixes typo in state.mongodb metadata.yaml
> Improves metadata YAML for state.postgresql

- state/mysql/metadata.yaml
- state/mysql/mysql.go
Metadata YAML for state.mysql and metadata parsing improvement.
* Improves metadata parsing by avoiding indirection on parsing of
`timeoutInSeconds` and adding it directly in the metadata struct.
Before we had a `Time` field that wasn't used and was causing
validation problems with `make check-component-metadata`
> Metadata YAML for state.mysql and metadata parsing improvement.

- tests/certification/go.mod
- tests/certification/go.sum
Updating the certification tests to point to the latest commits in dapr/dapr, now that the set of features for v1.11 is stabilized.
N/A
> Point certification tests to latest dapr/dapr

- configuration/redis/metadata.yaml
- configuration/redis/redis.go
- configuration/redis/redis_test.go
- tests/certification/configuration/postgres/postgres_test.go
- tests/certification/configuration/redis/redis_test.go
- tests/certification/go.mod
- tests/certification/go.sum
Go-SDK Configuration subscribe method has been modified (https://github.com/dapr/go-sdk/pull/389), and so the configuration certification tests using go-sdk need to be updated. Also there were some unresolved comments in PR https://github.com/dapr/components-contrib/pull/2807. This PR also includes those changes.
> Update Go SDK version in certification tests

- bindings/redis/metadata.yaml
- internal/component/redis/settings.go
- internal/component/redis/v9client.go
Ensures Redis 7 v9 Client uses the approximate max length of a stream, instead of the exact length. This matches the Redis 6 (v8 Client) behavior.
This was an oversight due to significant SDK changes between v8 and v9 SDKs (which we both support).
> Makes Redis7 (v9 client) match the Redis6 (v8 client) behavior

- pubsub/jetstream/jetstream.go
The `QueueGroupName` was omitted from being set on the `ConsumerConfig` resulting in an error from server (NATS) due to misconfiguration.
Please reference the issue this PR will close: #2827 
> [jetstream] Fix setting omitted QueueGroupName on ConsumerConfig

- bindings/twilio/sendgrid/sendgrid.go
- bindings/twilio/sendgrid/sendgrid_test.go
Adding support for dynamic templates. This includes allowing to provide a template id and template JSON data.
Supports these additional optional metadata (in configuration or request):
* dynamicTemplateId: the template id. Eg. "d-123456"
* dynamicTemplateData: the JSON passed to Sendgrid to populate the template. Eg. '{"customerName":"John Smith"}'
Please reference the issue this PR will close: #2412
> Add dynamic template support to Twilio Sendgrid binding

- tests/config/bindings/tests.yml
- tests/config/configuration/tests.yml
- tests/config/crypto/tests.yml
- tests/config/pubsub/tests.yml
- tests/config/secretstores/tests.yml
- tests/config/state/tests.yml
- tests/config/workflows/tests.yml
- tests/conformance/README.md
- tests/conformance/bindings/bindings.go
- tests/conformance/common.go
- tests/conformance/common_test.go
- tests/conformance/configuration/configuration.go
- tests/conformance/crypto/crypto.go
- tests/conformance/pubsub/pubsub.go
- tests/conformance/secretstores/secretstores.go
- tests/conformance/state/state.go
- tests/conformance/utils/utils.go
- tests/conformance/utils/utils_test.go
- tests/conformance/workflows/workflows.go
In conformance tests, operations that are required in each component are always enabled (e.g. all secret stores must implement "get" and "bulkGet", so those shouldn't be optional).
Changes the meaning of "operations" in the YAMLs to indicate additional, optional operations.
Fixes #2846
> Conformance tests: always enable required operations

- go.mod
- go.sum
@Taction noticed a pretty bad bug where request correlation could be out-of-sync. This is fixed in http-wasm v0.5.0.
https://github.com/http-wasm/http-wasm-host-go/pull/69
* [n/a] Created/updated tests (tests are upstream)
* [n/a] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
> deps: updates http-wasm to v0.5.0

- bindings/mysql/metadata.yaml
- state/mysql/metadata.yaml
Follows a conversation on Discord with a user that wasn't clear that the MySQL components can be used with MariaDB too.
Also updated in docs: dapr/docs#3463
> [Metadata] Clarify that MySQL components work with MariaDB too

- internal/component/azure/servicebus/message.go
- internal/component/azure/servicebus/metadata_test.go
Azure Service Bus supports a delayed message sending feature. Today the time stamp must be provided in HTTP Date Format, but that is not very obvious. No error was returned when the provided timestamp was in the wrong format, and as such the delayed sending was not applied.
This PR surfaces the error, but it also attempts to use RFC 3339 as a fallback if the HTTP Date Format parsing failed.
Previously: "Sat, 15 Jun 2024 13:45:30 GMT" + no errors
Now: "2024-06-15T13:45:30.00000000Z" / "2024-06-15T13:45:30Z" or "Sat, 15 Jun 2024 13:45:30 GMT" + error if failed
Related: https://github.com/dapr/components-contrib/issues/2745
> ASB: ScheduledEnqueueTimeUtc improve date parsing and return err

- bindings/azure/servicebusqueues/metadata.yaml
No need for RCs, but this needs to be in the release branch in case we make hotfixes etc.
> [Release-1.11] fix metadata.yaml: rename binding to `azure.servicebus.queues`

- go.mod
- go.sum
- tests/certification/go.mod
- tests/certification/go.sum
Our mongo version 1.11.2 was retracted due to a data race condition. Upgrading the library as a result.
> [Release-1.11] Upgrade Mongo dependency due to retraction

- state/memcached/memcached.go
- state/memcached/memcached_test.go
- tests/certification/state/memcached/memcached_test.go
Currently, we are always passing the `ttlInSeconds` value as-is to memcached however, any value over 30 days will be treated as a UInix timestamp by memcached so will probably mark the key for expiration immediately.
PR changed client to conver `ttlInSeconds` to Unix timestamp when value is larger than 30 days.
https://github.com/memcached/memcached/wiki/Commands#standard-protocol
> memached: if tllInSeconds larger than 30 days, convert to unix timestamp

- bindings/rabbitmq/rabbitmq.go
- bindings/rabbitmq/rabbitmq_integration_test.go
RabbitMQ message header values can be used to set additional metadata on a message, e.g. a label or message id like in Azure ServiceBus' message properties. The metadata can already be defined when creating the message, but till these values are not set on the enqueued message and only define e.g. the priority, TTL ...
With this PR the passed in metadata values are also available on the message's header values.
Please reference the issue this PR will close: dapr/docs#3503
> [RabbitMQ] use metadata from request as header of the published message

- internal/authentication/azure/auth.go
Fixes https://github.com/dapr/components-contrib/issues/2913
Allows unlimited timeout for MSI (like in Dapr 1.10), but only in environments which appear to have MSI enabled such that we can quickly fall through to the CLI authentication method.
Unfortunately the Azure SDK for Go does not export the constants needed here, so I had to redeclare them. They originate from:
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/managed_identity_client.go
> [Release 1.11] AUTH: Detect Azure MSI compatible environments and remove timeout

- state/mysql/metadata.yaml
The metadata.yaml for MySQL was incorrect and was missing the TTL capability.
> Fixed ttl capability in MySQL state store

- bindings/azure/servicebusqueues/servicebusqueues.go
Azure Service Bus supports storing Application Properties (custom user attributes) that are not URL safe. When sending this as metadata (especially in the case of HTTP) we must encode these values.
Fixes https://github.com/dapr/components-contrib/issues/2901
> Ensure ASBQ custom attributes are urlencoded on delivery

- bindings/azure/servicebusqueues/servicebusqueues.go
Azure Service Bus supports storing Application Properties (custom user attributes) that are not URL safe. When sending this as metadata (especially in the case of HTTP) we must encode these values.
Fixes https://github.com/dapr/components-contrib/issues/2901
> [Release 1.10] ASBQ custom metadata fix. Cherry pick of #2923

- crypto/key.go
- tests/conformance/crypto/crypto.go
When marshalling the object returned by Azure Key Vault as JSON, it is now correctly formatted as JWK
This is blocking the completion of E2E tests for crypto: https://github.com/dapr/dapr/pull/6546
> Azure Key Vault crypto: fixed JSON marshalling of public keys

- go.mod
- go.sum
- tests/certification/go.mod
- tests/certification/go.sum
… consumption problems have been resolved. And break the package.
This update is important because from version v1.7.0 to v1.8.1 memory consumption problems have been resolved. And break the package.
> Update amqp091-go to fix memory issues

- go.mod
- go.sum
- tests/certification/go.mod
- tests/certification/go.sum
Cherry pick of:
- Fixes unlicensed dependencies: #2928 
- Update `amqp091-go` to fix rabbitmq memory issues: #2927
From `amqp091-go` `v0.8.0` release notes:
- memory leak https://github.com/rabbitmq/amqp091-go/issues/179
- the publishWithContext interface will not return when it times out https://github.com/rabbitmq/amqp091-go/issues/178
> [Release 1.11] Fix unlicensed deps, upgrade `amqp091-go` for rabbitmq memory issue

- pubsub/redis/metadata.yaml
- state/redis/metadata.yaml
[Redis State] Component Metadata Schema: sets `redisPassword` to sensitive.
> [Redis State] Component Metadata Schema: sets redisPassword to sensitive

- internal/component/azure/blobstorage/client.go
- internal/component/azure/blobstorage/client_test.go
Fixes an issue reported by users.
Azure Blob Storage components have an "endpoint" property which is meant to be used with emulators such as Azurite.
However, we've seen users accidentally setting this property to their Azure Blob Storage endpoint, such as `https://myaccount.blob.core.windows.net/mycontainer`. Until 1.11.0, this did not cause any issue (for unclear reasons). Starting in 1.11.0, Dapr handles this "how it's supposed to", but this can cause issues with customers.
This PR changes the behavior by:
1. Show a log when a custom endpoint is used
2. If the "endpoint" metadata is set to the value it would have when using Azure Blob Storage, it is ignored (and a warning is shown).
> Azure Blob Storage: gracefully handle setting "endpoint" to non-emulator

- bindings/http/http.go
- bindings/http/http_test.go
1. Remove the "path sanitization" that disallowed `..` in URLs, since there is no reason for doing that
2. Increased TLS handshake timeout to 15s
3. Some other small fixes and tweaks
> Fixes in HTTP binding

- bindings/mysql/metadata.yaml
- bindings/mysql/mysql.go
- bindings/mysql/mysql_integration_test.go
- bindings/mysql/mysql_test.go
Fixes #2973 
Adds support for query parameters in the MySQL binding. This allows executing parametrized queries (such as `SELECT * FROM table WHERE id = ?`) which are extremely important to prevent SQL injections.
PS: this is an alpha component and doesn't have certification tests. The feature is being validated in the integration tests (which don't run in the CI but pass locally)
> MySQL binding: allow passing parameters for queries

- bindings/postgres/postgres.go
- tests/certification/bindings/postgres/README.md
- tests/certification/bindings/postgres/postgres_test.go
Adds support for parametrized queries in the Postgres binding. These are queries that accept positional parameters such as `$1` and that are replaced while being executed.
Using parametrized queries is extremely important for security, as it prevents SQL Injection attacks.
This works by adding a new metadata option to the binding called `params`, which contains a JSON-encoded list of parameters. The query can then reference them in order. This works for both the "exec" and "query" operations.
Example:
```go
resp, err = client.InvokeBinding(ctx, &daprClient.InvokeBindingRequest{
Name:      "mybinding",
Operation: "query",
Metadata: map[string]string{
"sql":    "SELECT * FROM " + tableName + " WHERE key = $1 OR value = $2",
"params": `[1, "foo"]`,
},
})
```
Behavior is validated in …
> Postgres binding: support parametrized queries

- go.mod
- go.sum
- tests/certification/go.mod
- tests/certification/go.sum
Upgrades EventHubs SDK and `go-amqp` SDK for stability bugfixes
github.com/Azure/go-amqp from v1.0.0 to v1.0.1:
- Fixed an issue that could cause links to terminate with error "received disposition frame with unknown link handle X".
github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs from  v1.0.0 to v1.0.1:
- GetPartitionProperties and GetEventHubProperties now retry properly on failures.
- Connection recovery could artificially fail, prolonging recovery.
> Chore: Upgrade EventHubs and go-amqp deps for bugfixes

- middleware/http/wasm/benchmark_test.go
- state/requests.go
Signed-off-by: Edoardo Vacchi <evacchi@users.noreply.github.com>
https://github.com/dapr/components-contrib/pull/2817/ updated to use `url` instead of `path`, however the companion benchmark was not update. Related: https://github.com/dapr/samples/pull/154
I haven't opened an issue since the change is trivial, but will do if requested.
> wasm: update benchmark to use `url` instead of `path`

- bindings/azure/openai/openai.go
- go.mod
- go.sum
This PR fixes some linting errors that is causing https://github.com/dapr/dapr/pull/6678 to fail.
The OpenAI space is rapidly getting updates so errors like this can be expected.
Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/2716
> Fix lint failure for openai binding

- .build-tools/pkg/metadataschema/validators.go
Docs: https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-scopes/
~~When https://github.com/dapr/dapr/pull/6714 is merged, this list may need to be expanded again~~
Also includes changes from dapr/dapr#6714
> Metadata: add other built-in properties for pubsub

- state/azure/cosmosdb/cosmosdb.go
- state/store.go
This indicates the maximum number of operations allowed in a transaction. The interface is optional.
> Added `MultiMaxSize` to Cosmos DB state store

- bindings/wasm/output.go
- bindings/wasm/output_test.go
- bindings/wasm/testdata/http/Makefile
- bindings/wasm/testdata/http/main.go
- go.mod
- go.sum
Add support for `wasi-http` client calls from the WASM binding. This enables developers of WASM bindings to make calls into Dapr (e.g. storage) or any other URL.
I will add documentation once there is agreement that this PR is ready to merge, but prior to merging it.
See discussion in #2990 
> Add support for wasi-http in the wasm binding.

- state/jetstream/jetstream.go
Add closer to NATS Jetstream datastore to help with graceful shutdown
Please reference the issue this PR will close: #2953 
> Add closer to jetstream state

- bindings/azure/openai/metadata.yaml
- bindings/azure/openai/openai.go
This PR adds `get-embedding` operation to get embeddings of any string to the Azure OpenAI output binding
Please reference the issue this PR will close: #3018 
> #3018: Add `get-embedding` operation to Azure OpenAI

- bindings/azure/storagequeues/storagequeues.go
Add metadata for dequeued message in bindings.azure.storagequeues
Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/2375
> Add metadata for dequeued message in bindings.azure.storagequeues

- bindings/rabbitmq/rabbitmq.go
> use rabbitmq message's header values as metadata values in the binding

- middleware/http/bearer/bearer_middleware.go
Fixes (maybe) #3025, as the JWKS from Azure AD is known for omitting the `alg` property.
I say "maybe" because I am not able to reproduce #3025 correctly. However, I've seen in other cases that this property was needed for the jwx library when verifying tokens from Azure AD. The JWKS document that Azure AD uses does not include the `alg` property ([example](https://login.microsoftonline.com/common/discovery/v2.0/keys)), so this helps the jwx library do hints.
> Bearer middleware: add "infer algorithm from key"

- internal/wasm/wasm_test.go
Windows clocks often don't give microsecond scope reading reliably. Our "strict mode" test was accidentally verifying a lower bound of time spent sleeping, when the important part is the upper bound. This removes the lower bound, so that tests pass on both unix and windows.
See https://github.com/dapr/components-contrib/pull/2884#issuecomment-1664498860
* [n/a] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
> wasm: fixes test flake on Windows and strict mode

- state/etcd/etcd.go
- tests/conformance/state/state.go
Add state store conformance tests to ensure that the `ttlExpireTime` metadata key is returned when Getting keys which have a `ttlInSeconds` set.
`ttlExpireTime` is needed for state clients (like actors) to have a copy of the expiry time of TTL keys expire so that they can update their local cache when appropriate.
PR shouldn't be merged until all `TTL` enabled state stores implement this metadata response.
See https://github.com/dapr/dapr/pull/6400 https://github.com/dapr/components-contrib/issues/2857 for more info.
> Conformance Tests: State- ` ttlExpireTime`

- pubsub/envelope.go
- pubsub/envelope_test.go
This partially fixes https://github.com/dapr/dapr/issues/6800. This PR assigns the trace fields provided in the method signature only if the cloud event envelope doesn't already have them.
To fully resolve the issue, a change is needed in Dapr to pass in empty values instead of `00-000-...` values which indicate empty spans.
> Retain cloudevent trace fields

- bindings/rabbitmq/metadata.yaml
- pubsub/gcp/pubsub/metadata.yaml
- pubsub/pulsar/metadata.yaml
- state/memcached/metadata.yaml
PRs #3057, #3066, #3071, #3061 contained a large number of factual errors, such as:
- Missing metadata properties
- Mismatched type and examples (description indicated a number, but example was for booleans)
- Missing `sensitive: true`
- Incorrect grouping of metadata options for auth profiles
- Typos and other bad wording
> Fixed a large number of errors in metadata.yaml

- bindings/azure/signalr/metadata.yaml
- bindings/azure/signalr/signalr.go
- bindings/azure/signalr/signalr_test.go
1. Update the "send message" related actions to use the latest api version 2022-11-01
2. Try to improve the 'negotiate' experience described in #2012 with a new operation type `clientNegotiate`, this method **calculates** the token when AccessKey is provided in the `connectionString`, and **invokes **the `generateToken` REST API when AAD auth is used. Users can invoke this output binding to get the `negotiate` response and return back to the SignalR client. With this change, the overall SignalR experience described by https://github.com/dapr/components-contrib/issues/2012#issuecomment-1229992939 can be simplified to:
```javascript
import { DaprClient } from '@dapr/dapr';
import express from 'express';
const client = new DaprClient(process.env.DAPR_HOST || 'http://localhost', …
```
> Adding client negotiate support for signalr binding

- bindings/aws/s3/s3.go
- nameresolution/consul/consul.go
- secretstores/hashicorp/vault/vault.go
- secretstores/hashicorp/vault/vault_test.go
Log usage of TLS skipped verification at info level the same as done for Kafka.
> Add insecureskipverify warnings

- state/aws/dynamodb/dynamodb.go
Defines the DynamoDB Transaction limit of 100 operations in a single transaction, similar to the way it is defined for CosmosDB.
This is necessary for Workflow, so it can be inferred what the max parallel operation batch size should be.
> Define DynamoDB Transaction limit

- .github/scripts/dapr_bot.js
This adds a command which allows rerunning of just the failed jobs on an existing workflow run ID.
This can help with reducing unnecessary workflow runs. It also allows trusted community members who are not approvers to perform this action (the same people who can run `/ok-to-test`).
Usage:
`\rerun <ID>`, where the ID is obtained from URL of a given workflow run
> Add `\rerun <ID>` command for failed jobs in workflows

- pubsub/jetstream/jetstream.go
Fixes #3079 
Uses `AckWait` time (if configured) in `Nak`, such that messages to be retried aren't instantly retried. This matches the behavior of the NATSStreaming component which is now deprecated.
~* [ ] Created/updated tests~
~* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_~
> Jetstream pubsub: Use AckWait time for Retry delay

- bindings/postgres/metadata.yaml
- configuration/postgres/metadata.yaml
- internal/authentication/postgresql/metadata.go
- state/postgresql/metadata.yaml
Fixes #3002
Adds a metadata property `queryExecMode`, which exposes the low level Statement Query Execution mode. In certain advanced scenarios, for example when using **pgBouncer** the correct mode must be chosen by the user for the Postgres components to work.
Allowed values:
```yaml
- "cache_statement"
- "cache_describe"
- "describe_exec"
- "exec"
- "simple_protocol"
```
See also https://github.com/jackc/pgx/issues/602#issuecomment-532236718 for reference.
~* [ ] Created/updated tests~
~* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]~
> Postgres components: Adds `queryExecMode` option

- go.mod
- go.sum
- tests/certification/go.mod
- tests/certification/go.sum
Pulling in `fix(client): force Event Hubs to use V1_0_0_0` by @dnwe in https://github.com/IBM/sarama/pull/2633
This should avoid dapr hitting any issues with Azure Event Hubs users who might not have followed the instructions in dapr/docs#3474 to pin their version number.
A small number of other changes are included in the release, but nothing I'd deem to be any additional risk over the existing upgrade to v1.41.0:
https://github.com/IBM/sarama/releases/tag/v1.41.1
Fixes #3104
> chore(deps): bump sarama to v1.41.1

- .github/workflows/conformance.yml
Noticed in our yaml files that the `conformance.yml` workflow was referencing the `certification` test path, which is just confusing because that's the wrong test path. It's a copy pasta error. It should be removed to avoid confusion as well as since it's not even being used.
> rm unused code

- bindings/gcp/bucket/bucket.go
- bindings/gcp/bucket/bucket_test.go
Fixed a typo in JSON tag that was causing authentication to fail.
Please reference the issue this PR will close: #3012
> Fix GCP storage bucket binding authentication issue

- go.mod
- go.sum
- tests/certification/go.mod
- tests/certification/go.sum
Fixes [GHSA-6xv5-86q9-7xr8](https://github.com/advisories/GHSA-6xv5-86q9-7xr8)
> [sec] Update github.com/cyphar/filepath-securejoin due to CVE

- bindings/redis/redis.go
- bindings/redis/redis_test.go
The Redis SDK returns a special value `redis: nil` when a key does not exist. This was not handled correctly by the binding.
It was already fixed in Dapr 1.11, but not in Dapr 1.10.X
Fixes #3140
> [Release 1.10 only] Fix Redis Binding Get Op for unknown keys

- .github/infrastructure/terraform/infra-setup/gcp/dapr-gh-gcp-wif/README.md
- .github/infrastructure/terraform/infra-setup/gcp/dapr-gh-gcp-wif/main.tf
This PR renames GCP WIF pool/provider names.
The previous GCP WIF used for the GHA workflows was not working correctly, so I needed to recreate it with a new name.
The Terraform script that creates these resources have been executed and the output will be supplied to
`components-contrib` maintainer to modify the GHA secrets:
```golang
workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER_NAME }}
service_account: ${{ secrets.GCP_WIF_SA_EMAIL }}
```
Once the GHA secrets have been updated, we can run the GCP Certification tests.
> [GCP Certification Tests] renames GCP WIF pool/provider names

- .github/scripts/test-info.mjs
GCP certification tests have been broken for many weeks due to failed auth.
Disabling them for now to avoid wasting CI cycles and causing noise.
> Disable broken GCP cert tests

- .golangci.yml
- tests/conformance/README.md
- tests/conformance/bindings_test.go
- tests/conformance/common.go
- tests/conformance/configuration_test.go
- tests/conformance/crypto_test.go
- tests/conformance/lock_test.go
- tests/conformance/pubsub_test.go
- tests/conformance/secretstores_test.go
- tests/conformance/state_test.go
- tests/conformance/workflow_test.go
Tidying up how tests are loaded: rather than a single, "fat" `common.go`, each component type has the loader in its own `_test.go` file. This helps keeping the code.
> Conformance test: move loader to each component type's folder

- pubsub/gcp/pubsub/pubsub.go
- state/gcp/firestore/firestore.go
GCP cert tests were failing after switching to dapr/dapr master, due to the way the context used for initialising the connection to GCP was managed.
This PR closes https://github.com/dapr/components-contrib/issues/3129
> Fixes GCP components failing to authenticate

- .github/scripts/test-info.mjs
Re-enables the GCP tests that were disabled because they were failing.
This PR should be merged only after https://github.com/dapr/components-contrib/pull/3169 is merged into master.
> Re-enabling the failing GCP tests

- .build-tools/pkg/metadataschema/validators.go
- state/mysql/metadata.yaml
Adds metadata fields needed for the outbox pattern
> Adds outbox metadata fields

- .build-tools/pkg/metadataschema/validators.go
Updating the route documentation link to direct users to the proper part on the docs page. Currently they are taken to the top of the page, but its just bc the link is for `specifying` when it should just be `specify` for: https://docs.dapr.io/developing-applications/building-blocks/bindings/howto-triggers/#specify-a-custom-route
> fix typo to direct users to proper part on docs page

- pubsub/rabbitmq/rabbitmq.go
Backport of https://github.com/dapr/components-contrib/pull/3198
> [1.12] pubsub/rabbitmq: return error if reconnect errors in Init

- state/mysql/mysql.go
- state/sqlite/sqlite_dbaccess.go
#3159 introduced a regression that caused sets with first-write-wins fail if the table was empty
The issue was due to a "FROM" statement in the CTE that should not have been there.
Also improved how the SQLite component detects etag failures when FWW is used
> Fixes first-write-wins with SQLite and MySQL

- bindings/azure/blobstorage/metadata.yaml
- internal/component/azure/blobstorage/client.go
- internal/component/azure/blobstorage/metadata.go
- state/azure/blobstorage/v1/metadata.yaml
- state/azure/blobstorage/v2/metadata.yaml
Adds a new metadata option `disableEntityManagement` to use Azure Blob Storage components with minimal Entra ID permissions.
Fixes #3208
> Azure BlobStorage components: Add `disableEntityManagement` metadata option

- state/cassandra/cassandra.go
- state/cassandra/metadata.yaml
Adds TLS (SSL) support Cassandra State store via `EnableHostVerification` metadata option.
> Adds TLS support to Cassandra State Store

- common/authentication/sqlite/metadata.go
- nameresolution/sqlite/sqlite.go
- state/sqlite/sqlite_dbaccess.go
- state/sqlite/sqlite_test.go
The `_pragma=foreign_keys(1)` option should be added only if the component requires it. Users should not be allowed to specify that.
> SQLite: allow enabling foreign keys in `GetConnectionString`

- state/sqlite/sqlite_dbaccess.go
By default the Go database/sql package opens multiple connections to a database.
However, when using SQLite with an in-memory database, this can cause conflicts if two transactions are executed at the same time.
When the SQLite database is stored on disk, the WAL allows multiple operations in parallel and keeps them pending for up to "busyTimeout". However when the database is in-memory, based on some real-world data, a transaction blocks the database and busyTimeout isn't respected.
Using a single connection makes it so Go never tries to create 2 transactions in parallel.
> SQLite: when connecting to an in-memory database, limit to 1 concurrent connection

- common/component/postgresql/postgresql_query.go
- common/component/postgresql/postgresql_query_test.go
- state/README.md
- state/azure/cosmosdb/cosmosdb_query.go
- state/azure/cosmosdb/cosmosdb_query_test.go
- state/mongodb/mongodb_query.go
- state/mongodb/mongodb_query_test.go
- state/query/filter.go
- state/query/query.go
- state/redis/redis_query.go
- state/redis/redis_query_test.go
- tests/config/state/redis/v6/statestore.yaml
- tests/conformance/state/state.go
- tests/state/query/q4-notequal.json
- tests/state/query/q6-notequal.json
- tests/state/query/q7.json
- tests/state/query/q8.json
In this PR have been added the follow filter operation for the query in the state component
- NEQ  ->  Not Equal !=
- GT -> Greater Than >
- GTE -> Greater Than Equals >=
- LT -> Less Than <
- LTE -> Less Than Equals <=
These operations are implemented in the Redis, MongoDB, CosmosDB, Postgresql, CockroachDB state 
> Add new filters type in the query of the state component

- state/sqlserver/migration.go
> Fix SQL Server state store not working with case-sensitive collations

- common/component/kafka/kafka.go
- common/component/kafka/metadata.go
- common/component/kafka/metadata_test.go
- pubsub/kafka/metadata.yaml
Partially closes https://github.com/dapr/components-contrib/issues/2173#issuecomment-1835795781.
> Add kafka configuration to pub/sub

- state/sqlserver/migration.go
The fix in #3272 allowed support for case-sensitive database collations, but wasn't enough for server collations
Fixes #3271
> [release-1.12] Fixup from #3272: support case-sensitive SERVER collation

- common/authentication/sqlite/metadata_test.go
Only adds unit tests, mostly focused on the `GetConnectionString` method; no code changes
> Add unit tests for SQLite metadata package

- bindings/kafka/metadata.yaml
- common/component/kafka/kafka.go
- common/component/kafka/metadata.go
- pubsub/kafka/metadata.yaml
I've had issues using the AWS IAM auth type I added until I realized the problem was that I was using the authType `awsIAM` but the component implementation was looking for `awsiam`...
This PR fixes that making the official name of the auth type `awsiam` going forward. Additionally I changed the switch statement to lowercase the authType so the switch statements located in kafka.go and metadata.go behave the same way
> kafka awsiam authtype fix name

- common/component/sql/migrations/sqlserver/sqlserver_migrations.go
- common/component/sql/migrations/sqlserver/sqlserver_migrations_test.go
- common/component/sqlserver/drop_schema.go
- state/sqlserver/sqlserver_integration_test.go
Adds a package with utilities to perform migrations for SQL Server, similarly to what we have for Postgres and SQLite, based on the same interfaces.
This package is not _yet_ used in the SQL Server components, but it's implemented here as a first step.
Normally these migration packages are tested by the respective components' certification tests. Since this is not (yet) used in a component, I've added integration tests. However, these require a SQL Server container running so will not run in CI.
Output of the tests on my machine:
```
$ go test -v -count=1 .
=== RUN   TestMigration
=== RUN   TestMigration/Metadata_table
=== RUN   TestMigration/Metadata_table/Create_new
time="2023-12-20T00:08:54.569431243Z" level=info msg="Ensuring metadata table '[md7b24248].[metadata_1]' exists" …
```
> Add migration utils for SQL Server

- internal/component/kafka/consumer.go
1.12 port of https://github.com/dapr/components-contrib/pull/3297
> fix kafka consumer

- common/authentication/aws/aws.go
- state/aws/dynamodb/dynamodb.go
- state/aws/dynamodb/dynamodb_test.go
I added a Get check to a dummy key on component Init for aws Dynamodb. This will prevent Dapr from initialising if we have wrong component info (credentials/table name).
https://github.com/dapr/components-contrib/issues/3190
> state.dynamodb: validate AWS connection

- common/component/kafka/consumer.go
- common/component/kafka/metadata.go
- common/component/kafka/metadata_test.go
Pass Message Key and other message metadata as metadata in Kafka.pubsub consumer.
Currently, only message value is passed to endpoint.
Fixes #2213
> Kafka: Add message key and other metadata as metadata in consumer

- state/redis/redis_query.go
- tests/certification/state/redis/components/docker/default/redisstatestore.yaml
- tests/certification/state/redis/docker-compose.yml
- tests/certification/state/redis/redis_test.go
In RediSearch 2.8 the returned data structure of an `FT.SEARCH` changed, breaking the state Query API.
PR updates the redis Query function to parse both the old and new returned structures. Adds a query certification test.
https://docs.redis.com/latest/stack/release-notes/redisearch/redisearch-2.8-release-notes/
> Fix Redis Query for RediSearch 2.8+

- common/component/postgresql/v1/postgresql.go
- common/component/postgresql/v1/postgresql_test.go
- state/mysql/mysql.go
- state/mysql/mysql_test.go
- state/postgresql/v2/postgresql.go
- state/postgresql/v2/postgresql_integration_test.go
- state/sqlite/sqlite_dbaccess.go
- state/sqlserver/sqlserver.go
When Multi is invoked with a single operation, on SQL state stores (Postgres v1/v2, CockroachDB, MySQL, SQLite, MS SQL Server) we can omit starting a transaction, as a single operation is going to be executed atomically regardless.
This should offer some non-insignificant perf benefits thanks to:
- Reducing the number of round-trips to the DB from 3 to 1
- Reducing locks used inside the DB server
> Improve Multi perf on SQL state stores with 1 op only

- common/authentication/sqlserver/metadata.go
- state/sqlserver/metadata.go
- state/sqlserver/metadata.yaml
- state/sqlserver/migration.go
- state/sqlserver/sqlserver.go
- state/sqlserver/sqlserver_integration_test.go
- state/sqlserver/sqlserver_test.go
- tests/certification/state/sqlserver/components/docker/customschemawithindex/sqlserver.yaml
- tests/certification/state/sqlserver/sqlserver_test.go
Similarly to other databases like Postgres and SQLite, moving auth code for MS SQL Server to a shared package.
> Create shared auth package for SQL Server

- common/component/kafka/metadata.go
- common/component/kafka/metadata_test.go
This is a follow-up PR based on the comment https://github.com/dapr/components-contrib/pull/3310#discussion_r1447069372
> Kafka: Removed the AWS creds check from kafka metadata

- .github/workflows/generate-component-metadata-for-tag.yml
Updated the github workflow by installing Go first to then run Go commands with the rebuilding and bundling of the metadata.
If you execute the workflow as is, then you will see an issue due to upgrading go versions to 1.21, as the toolchain is not present in Go 1.20.
```
go: errors parsing go.mod:
... unknown directive: toolchain
...
```
Follow up question: Are there other workflows not executing that need this same update? should this workflow be added to execute main to catch in future?
Figured I'd just open PR with fix rq.
> fix(build): fix broken workflow by setting up go first

- pubsub/redis/redis.go
- pubsub/redis/redis_test.go
Redis does not handle event metadata at all. We had a P0 issue in runtime that was discovered because of Pulsar pubsub and it could not be reproduced with Redis because of inconsistency of handling event metadata - in this case, Redis simply drops it. This PR brings the Redis component (stable) at the same level of compatibility we should have across beta and stable pubsub components (IMO) regarding event metadata handling. This is not a P0 (IMO), it will just block the E2E test to reproduce the P0 bug we will need to fix.
Related to the following issues:
- P0 in runtime that fixes conflict of event metadata for pubsub: https://github.com/dapr/dapr/issues/7413 …
> FIX: Redis to handle event metadata.

- pubsub/pulsar/metadata.go
- pubsub/pulsar/metadata.yaml
- pubsub/pulsar/pulsar.go
- pubsub/pulsar/pulsar_test.go
Reported by users, the Pulsar component has hardcoded concurrency settings which provides very limited performance at moderate to high scale scenarios, causing bottlenecks and issues.
I'm targeting this for 1.13 as Pulsar is a stable component and this is an issue that prevents a lot of production scenarios. Will merge if we have consensus for a 1.13 release, otherwise i'll target the PR against main branch for 1.14.
> Enable configurable concurrency for pulsar

- common/authentication/azure/auth.go
This seems to be causing some issues for customers, and in a cloud service the CLI credentials would not work anyways.
> Azure auth: do not use CLI provider by default when running in a cloud service

- common/component/azure/servicebus/metadata.go
- common/component/azure/servicebus/metadata_test.go
ASB `autodeleteonidlesec` should throw a warning if the value provided is less than 300 (5 minutes). This is the minimum duration required for this feature.
See https://learn.microsoft.com/en-us/azure/service-bus-messaging/advanced-features-overview#autodelete-on-idle
> Azure Service Bus: enforce `autodeleteonidlesec` minimum 300

- common/component/azure/eventhubs/eventhubs.go
This is an attempt to recover eventhubs topic subscription upon error.
~* [ ] Created/updated tests~
~* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_~
> Recover interrupted eventhubs subscriptions

- internal/component/azure/eventhubs/eventhubs.go
[Release 1.12] Cherry Pick Recover interrupted eventhubs subscriptions (#3344)
> [Release 1.12] Cherry Pick Recover interrupted eventhubs subscriptions (#3344)

- common/component/kafka/consumer.go
- common/component/kafka/kafka.go
- pubsub/kafka/kafka.go
Reported by Dapr Kafka users trying out 1.13-rc.2: Upon receiving a sigterm, Dapr would continue to consume events and deliver them to be the app, causing the graceful draining process to be not work as expected and keep the app busy.
This PR was tested in a pre-production environment at large scale and was confirmed to solve the issue.
> [1.13] Fix Kafka consumer cancellation

- .build-tools/cmd/cmd-bundle-component-metadata.go
- .build-tools/component-folders.yaml
This is used for the component metadata bundler
> [chore] Update component-folders.yaml

- state/postgresql/v2/postgresql.go
Currently, for postgres v2 users if the sidecar restarts, then they will see this err due to the setup for the migrations:
```
failed to perform migration 0: failed to create state table: ERROR: relation \"<tablename>\" already exists
```
Question:
- are other v2 components at risk of seeing this err?
- how was this not caught in a test?
- should a follow up issue for tests to catch this be created for the future?
> fix: create table for migration only if not exists

- state/postgresql/v2/postgresql.go
> [1.13] fix: create table for migration only if not exists (#3356)

- configuration/azure/appconfig/appconfig.go
- configuration/azure/appconfig/appconfig_test.go
gRPC forces lowercase metadata, but the appconfig component expects camel case metadata. This means AppConfig doesn't work with gRPC.
This is now fixed.
> Fix Azure App Config not working with gRPC

- go.mod
- go.sum
Upgraded http-wasm host to the lates to allow a fix and source address retrieval.
Ping @daixiang0
> chore: upgrades http-wasm host to v0.6.0.

- go.mod
- go.sum
- tests/certification/go.mod
- tests/certification/go.sum
- tests/e2e/pubsub/jetstream/go.mod
- tests/e2e/pubsub/jetstream/go.sum
Fixes 2 possible data corruption issues. See:
- https://github.com/klauspost/compress/issues/875
- https://github.com/klauspost/compress/issues/922
> [release-1.13] Update klauspost/compress dependency

- go.mod
- go.sum
- tests/certification/go.mod
- tests/certification/go.sum
- tests/e2e/pubsub/jetstream/go.mod
- tests/e2e/pubsub/jetstream/go.sum
Fixes 2 possible data corruption issues. See:
- https://github.com/klauspost/compress/issues/875
- https://github.com/klauspost/compress/issues/922
> Update klauspost/compress dependency

- bindings/kafka/kafka.go
- common/component/kafka/consumer.go
- common/component/kafka/kafka.go
- common/component/kafka/mocks/consumergroup.go
- common/component/kafka/mocks/mock_ISchemaRegistryClient.go
- common/component/kafka/subscriber.go
- common/component/kafka/subscriber_test.go
- pubsub/kafka/kafka.go
- tests/certification/go.mod
- tests/certification/go.sum
Updates the kafka consumer group to correctly respect context cancellation for individual topic subscriptions. The consumer will be reloaded for every topic subscription, or un-subscription, using the same consumer group. Ensures there are no infinite tight loops, and only a singular consumer is run at a time. Ensures all go routines have returned on close.
> PubSub Kafka: Respect Subscribe context

- common/component/kafka/kafka.go
Fixes a possible nil pointer reference error when closing a Kafka componet, the `cg` field can be nil.
> kafka: bugfix possible nil pointer error on close

- common/component/kafka/kafka.go
- common/component/kafka/kafka_test.go
Fixing bug with new Avro conversion when message values are NULL
#3387
> Fixing bug with new Avro conversion when message values are NULL

- .github/holopin.yml
The `yaml` file to award contribution badges has been updated such that each contributor can be awarded a Components badge for their contribution to this repo.
This PR fixes #3394  
Please make sure you've  completed the relevant tasks for this PR, out of the following list:
> Update holopin.yml to award components badge to contributors

- bindings/postgres/metadata.yaml
- bindings/postgres/postgres.go
- common/authentication/aws/aws.go
- common/authentication/postgresql/metadata.go
- common/component/postgresql/v1/postgresql.go
- common/component/postgresql/v1/postgresql_query.go
- configuration/postgres/metadata.yaml
- configuration/postgres/postgres.go
- state/postgresql/v1/metadata.yaml
- state/postgresql/v2/metadata.yaml
- state/postgresql/v2/postgresql.go
- tests/utils/configupdater/postgres/postgres.go
Fixes some bugs and other issues, including unnecessary metadata options and uneven info in `metadata.yaml` files, introduced in #3324
> Fixups from #3324

- bindings/aws/sns/metadata.yaml
- bindings/aws/sns/sns.go
Add metadata schema for aws sns binding.
https://github.com/dapr/components-contrib/issues/3432
> feat: add aws sns metadata schema

- bindings/redis/metadata.yaml
- common/component/redis/redis.go
- common/component/redis/redis_test.go
- common/component/redis/settings.go
- common/component/redis/settings_test.go
- common/component/redis/v8client.go
- common/component/redis/v9client.go
- configuration/redis/metadata.yaml
- pubsub/redis/metadata.yaml
- state/redis/metadata.yaml
This PR allows users to use private certs when connecting to Redis. It adds two additional fields to all the Redis-based components' metadata.
> Redis private certificates

- common/component/azure/servicebus/message_pubsub.go
- common/component/azure/servicebus/message_pubsub_test.go
Service Bus PubSub (and Bindings) Components: Add `ApplicationProperties` to metadata payload on subscription (in the same way these are set from metadata when publishing through Dapr)
#3428
~* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_~
> ASB: Add support for ApplicationProperties in subscriptions

- .github/workflows/generate-component-metadata-for-tag.yml
- common/component/azure/servicebus/message_pubsub.go
If we leave the workflow definition file as is, then it will not work. It will err with `The specified go version file at: go.mod does not exist`. This is because the workflow steps set up Go referencing a go mod file before actually downloading the repo code that contains the go mod file that the precursor step needs. This PR fixes that issue, and bumps setup-go versions.
> build: fix github wf to generate metadata bundle

- pubsub/rabbitmq/rabbitmq.go
- pubsub/rabbitmq/rabbitmq_test.go
Added a new RabbitMQ subscription argument to enable [Single Active Consumer](https://www.rabbitmq.com/docs/consumers#single-active-consumer) (`x-single-active-consumer`)
Usage with declarative subscription
```yaml
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
name: orders
spec:
topic: orders
routes:
default: /orders
pubsubname: orderpubsub
metadata:
queueName: "foo-queue-quorum"
queueType: quorum
singleActiveConsumer: "true"
scopes:
- order-processor-sdk
```
Please reference the issue this PR will close: #3120
> Add RabbitMQ single active consumer argument

- pubsub/solace/amqp/metadata.yaml
`pubsub.solace.amqp`'s `metadata.yaml` now has a name and type reflective of its component `spec.type`, aligned with all other `metadata.yaml` files. It's title also now is the proper formatting of the component.
Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/3451
> fix: pubsub.solace.amqp metadata.yaml name/title fix

- tests/certification/bindings/rabbitmq/components/exclusive/rabbitmq.yaml
Create a missing component spec - ensuring that the sidecar continues running after component failure.
Does not fully close the issue but arose from/is tracked by https://github.com/dapr/components-contrib/issues/3449
Successful run: https://github.com/dapr/components-contrib/actions/runs/9604165214
Latest merge from main was blocked by a dockerhub registry outage
> fix workflow stable component cert - bindings.rabbitmq

- tests/certification/state/mysql/docker-compose.yaml
This changes the flag used to use the mysql_native_password plugin
Does not fully close the issue but arose from/is tracked by #3449 
> fix workflow stable component cert - state.mysql

- CONTRIBUTING.md
- pubsub/gcp/pubsub/metadata.go
- pubsub/gcp/pubsub/metadata.yaml
- pubsub/gcp/pubsub/pubsub.go
- pubsub/gcp/pubsub/pubsub_test.go
Adds metadata settings for GCP PubSub component to configure the `MaxOutstandingMessages`, `MaxOutstandingBytes`, and `NumGoroutines` settings in the underlying [Google Cloud pubsub package](https://pkg.go.dev/cloud.google.com/go/pubsub).
Please reference the issue this PR will close: [#3441](https://github.com/dapr/components-contrib/issues/3441)
> Support configurable MaxOutstanding* and NumGoroutines settings for GCP PubSub component

- .github/infrastructure/docker-compose-mysql.yml
Applies the same update as #3450, this time to the docker manifest used for component conformance test.
There are no more instances of the deprecated flag `--default-authentication-plugin` existing in this repo.
Does not close but arose from/is tracked by #3457 
> fix: conformance - state.mysql.mysql

- pubsub/aws/snssqs/snssqs.go
Changed native map to xsync.MapOf which is safe for concurrent access
Please reference the issue this PR will close: #3430 
> change topicArns to map safe for concurrent access

- .github/workflows/certification.yml
- .github/workflows/conformance.yml
> ci: fix spelling in two workflows

- .build-tools/go.mod
- .github/workflows/components-contrib-all.yml
- .github/workflows/components-contrib.yml
- .golangci.yml
- Makefile
- bindings/redis/metadata.yaml
- bindings/redis/redis.go
- bindings/redis/redis_test.go
- common/component/redis/redis.go
- common/component/redis/redis_test.go
- common/component/redis/settings.go
- common/component/redis/v8client.go
- common/component/redis/v9client.go
- configuration/redis/metadata.yaml
- configuration/redis/redis.go
- configuration/redis/redis_test.go
- go.mod
- lock/redis/standalone.go
- pubsub/redis/metadata.yaml
- pubsub/redis/redis.go
- state/redis/metadata.yaml
- state/redis/redis.go
- tests/certification/go.mod
- tests/e2e/pubsub/jetstream/go.mod
- tests/utils/configupdater/redis/redis.go
Implements EntraID / AAD support for Azure Cache for Redis across all components
For a component yaml file to use Azure Cache for Redis with Entra ID see this:
This will assume that either your UserPrincipal (via AzureCLICredential) or the SystemAssigned Managed Identity have the RedisDataOwner role permission. If a user-assigned identity is to be used the `azureClientID` property needs to be specified.
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
name: statestore
spec:
type: state.redis
initTimeout: 30s
metadata:
- name: redisHost
value: MYHOSTNAME.redis.cache.windows.net:6380
- name: useEntraID
value: "true"
- name: enableTLS
value: "true"
```
Adds #3088
Manually modified …
> Adds EntraID auth support to all Redis Components

- .build-tools/go.mod
- .github/workflows/components-contrib-all.yml
- .github/workflows/components-contrib.yml
- .golangci.yml
- Makefile
- bindings/redis/metadata.yaml
- bindings/redis/redis.go
- bindings/redis/redis_test.go
- common/component/redis/redis.go
- common/component/redis/redis_test.go
- common/component/redis/settings.go
- common/component/redis/v8client.go
- common/component/redis/v9client.go
- configuration/redis/metadata.yaml
- configuration/redis/redis.go
- configuration/redis/redis_test.go
- go.mod
- lock/redis/standalone.go
- pubsub/redis/metadata.yaml
- pubsub/redis/redis.go
- state/redis/metadata.yaml
- state/redis/redis.go
- tests/certification/go.mod
- tests/e2e/pubsub/jetstream/go.mod
- tests/utils/configupdater/redis/redis.go
Cherry-pick of #3470 
- Also updates Go Patch version.
- Also upgrades Linter and linter config
> [Release 1.14] Cherry Pick of 3470 - Azure Auth for all Redis Components

- Makefile
Now instead of `make lint` which will complain about historical lint errors, you can also run:
```
get fetch upstream # update your upstream references
LINT_BASE=upstream/main make lint
```
This will only lint the commits you added since the commit pointed to by `LINT_BASE`. Under the hood this uses `git rev-parse` so you can use friendly names like tags, branch names or simply commit IDs.
> Update linter command to support diff linting

- common/component/kafka/consumer.go
- common/component/kafka/metadata_test.go
Sending special characters in Kafka message metadata will cause an error when metadata is converted to HTTP headers.
Error: 
```
WARN[0009] Error processing Kafka message: topic/0/13 [key=]. Error: error returned from app channel while sending pub/sub event to app: retriable error occurred: Post "http://127.0.0.1:56012/handle-message": net/http: invalid header field value for "My-Header". Retrying...
```
Go validates header value using the function `ValidHeaderFieldValue`, for reference and allowed format, see more [here](https://github.com/golang/net/blob/4542a42604cd159f1adb93c58368079ae37b3bf6/http/httpguts/httplex.go#L303)
Please reference the issue this …
> Fix kafka metadata to HTTP headers conversion of invalid characters

- secretstores/aws/parameterstore/parameterstore.go
- secretstores/aws/parameterstore/parameterstore_test.go
Removes the writing to a dummy key to check for access, because that might be disallowed for some policies.
The change was introduced in 1.13 (https://github.com/dapr/components-contrib/pull/3301).
This needs to be patched into 1.13 and 1.14.
[This issue](https://github.com/dapr/components-contrib/issues/3516) was related to AWS Secrets manager, but the same applies for parameter store too.
> Removes the dummy check for AWS Parameter Store access validation

- .github/scripts/components-scripts/conformance-bindings.influx-setup.sh
- .github/scripts/components-scripts/docker-compose.sh
- secretstores/aws/secretmanager/secretmanager.go
- secretstores/aws/secretmanager/secretmanager_test.go
- tests/certification/flow/dockercompose/dockercompose.go
- tests/certification/pubsub/pulsar/pulsar_test.go
Cherrypicks https://github.com/dapr/components-contrib/pull/3519
> [1.13] Cherrypick: Removes check for dummy key in AWS Secrets manager (#3519)

- bindings/kafka/metadata.yaml
- common/component/kafka/consumer.go
- common/component/kafka/kafka.go
- common/component/kafka/metadata.go
- common/component/kafka/metadata_test.go
- pubsub/kafka/metadata.yaml
In continuation of the issue https://github.com/dapr/components-contrib/issues/3503, make the escaping headers Opt-in via the component setting
Please reference the issue this PR will close: #3503
> Add Kafka metadata opt-in setting to escapeHeaders

- common/component/kafka/kafka.go
- common/component/kafka/kafka_test.go
Addressed issue in Kafka-pubsub for avro null messages
- was not properly tested end to end so the value never comes as NULL but as `"null"` which is the JSON representation
#3510
> Addressed issue in Kafka-pubsub for avro null messages

- common/component/kafka/consumer.go
Resolving a weird edge case in case of a poison pill message
- Moving the `session.Context().Done()` case ensures the next message is NOT processed while the pod is terminating...
#3529
> Resolving a weird edge case in case of a poison pill message being retried, followed by a pod restart

- Makefile
We install lint under GOPATH while if users install one under `/usr/local/bin` which is front of the GOPATH, even we upgrade, users still use old lint.
> CI: correct upgrade lint path

- .build-tools/pkg/metadataschema/builtin-authentication-profiles.go
- .build-tools/pkg/metadataschema/validators.go
If choose postgresql `AWS: Access Key ID and Secret Access Key` as the Authentication Profile, there are multiple fields for `AWS AccessKey, AWS Region, and AWS Secret Key" .` 
The reason is bc for PostgreSQL itself has `awsIAM` as the metadata,  which already include accessKey, secretKey and awsRegion. But during the building it will append built-in auth profile again, which bring these duplicated fields.  This PR tweak the logic of the building process, which filters out those fields for the postgres component. 
Before the change:
```
{
"title": "AWS: Access Key ID and Secret Access Key",
"description": "Authenticate using an Access Key ID and Secret Access Key included in the metadata",
"metadata": [
{
"name": "useAWSIAM",
"description": "Must be set to `true` to enable the component …
```
> fix: drop duplicate aws auth field in postgresql

- go.mod
- state/mongodb/mongodb.go
- state/mongodb/mongodb_test.go
By not keeping the client when `Ping` fails we're later unable to properly invoke `Disconnect` which leads to leaked resources, most notably goroutines created on the mongo-go-driver.
> mongodb: fix goroutine leak on failed server connections

- conversation/README.md
- conversation/converse.go
- conversation/metadata.go
- conversation/openai/openai.go
- go.mod
- go.sum
Implement conversation API with origin openai component.
Please reference the issue this PR will close: #3517
> init conversation API with openai component

- .build-tools/pkg/metadataschema/builtin-authentication-profiles.go
- .build-tools/pkg/metadataschema/validators.go
- secretstores/aws/parameterstore/parameterstore.go
- secretstores/aws/parameterstore/parameterstore_test.go
> Cherrypicking into release 1.13

- bindings/http/metadata.yaml
We are missing this field on the http binding. It is in the logic, and docs:
https://github.com/dapr/components-contrib/commit/9e9d7086e171ee0c99ba295ddf445287effd62f7#diff-50e6b52eb3eded23c24e7ac1117cb029862ee7ead109191d65cc1b13d54ed8daR185
https://docs.dapr.io/reference/components-reference/supported-bindings/http/
> fix(metadata): add missing field to http binding

- common/authentication/postgresql/metadata.go
In the event someone is using AWS IAM authentication, then they can leverage the loading of default credentials here: https://github.com/dapr/components-contrib/blob/9012bdce7f0eb67c1c22fa1928a657b27d4bdd31/common/authentication/aws/aws.go#L105
Alternatively, they can supply the access key and secret key. Therefore, the accesskey and secretkey fields are optional, not required.
> fix(metadata): make access/secret keys optional

- pubsub/redis/metadata.yaml
- state/redis/metadata.yaml
Some redis components have the auth profile section for username/pwd, and others don't. I've ensured it's on all now.
> fix(redis): make auth profiles consistent for username/pwd

- common/component/azure/blobstorage/request.go
[Azure-BlobStorage] Log debug instead of warn when metadata has disallowed characters
Log debug instead of warn when metadata has disallowed characters
Please reference the issue this PR will close: [#_[4399]_](https://github.com/dapr/docs/issues/4399)
> [Bindings][BlobStorage] Update request.go - Log debug instead of warning

- common/authentication/aws/x509.go
oops 😅 
Need this to prevent the nil pointer issue upon component close that I thought that I fixed here: 
https://github.com/dapr/components-contrib/pull/3607
> fix: initialize the close chan

- pubsub/pulsar/metadata.go
- pubsub/pulsar/metadata.yaml
- pubsub/pulsar/pulsar.go
- pubsub/pulsar/pulsar_test.go
- Fixes `subscribeType` metadata field not being respected
- Fixes bug not allowing to connect to remote endpoints starting with `pulsar://` or `pulsar+ssl://`
Currently, we have the `subscribeType` configuration field [documented](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-pulsar/#spec-metadata-fields) but not respected and the same field as subscription metadata is respected, but not documented.
```
var defaultSubscription = &common.Subscription{
PubsubName: pubsubName,
Topic:      topicName,
Route:      "/orders",
Metadata:   map[string]string{"subscribeType": "key_shared"},
}
```
This PR uses the value in the configuration as default and overrides with the subscription metadata if one is set.
https://github.com/dapr/components-contrib/issues/3601
Please …
> Fixes `subscribeType` metadata field not being respected for Pulsar pub sub

- common/authentication/aws/aws.go
- common/authentication/aws/static.go
- common/authentication/aws/static_test.go
- common/authentication/aws/x509.go
fixes a bug introduced here https://github.com/dapr/components-contrib/pull/3591/files#diff-017233cbc5865ed02ab3eacc4bc99b36ced96fcaf3420176e41d414444e41bc9
previously it was possible to get an aws session without providing access key and secret key, and we would pick the credentials from the environment. But since that PR, specifically because of this
```
func newStaticIAM(_ context.Context, opts Options, cfg *aws.Config) (*StaticAuth, error) {
auth := &StaticAuth{
logger:        opts.Logger,
region:        &opts.Region,
endpoint:      &opts.Endpoint,
accessKey:     &opts.AccessKey,
secretKey:     &opts.SecretKey,
sessionToken:  &opts.SessionToken,
assumeRoleARN: &opts.AssumeRoleARN,
sessionName:   &opts.SessionName,
```
and the later check
```
if a.accessKey != nil && a.secretKey != nil …
```
> fix get aws creds from environment

- .github/infrastructure/docker-compose-sqlserver.yml
- tests/certification/state/azure/cosmosdb/cosmosdb_test.go
- tests/certification/state/memcached/memcached_test.go
- tests/certification/state/sqlserver/sqlserver_test.go
> Fixes state cert tests

- .build-tools/builtin-authentication-profiles.yaml
- pubsub/kafka/metadata.yaml
got docs PR upstream and noticed a few things here and I cross referenced things:
https://github.com/dapr/docs/pull/4456
with https://github.com/dapr/components-contrib/pull/3617 we need to mark accesskey and secretkey as non-required fields in the metadata too.
> style: improve clarity on aws changes

- .build-tools/builtin-authentication-profiles.yaml
- .build-tools/pkg/metadataschema/builtin-authentication-profiles.go
- bindings/kafka/metadata.yaml
- bindings/postgres/metadata.yaml
- configuration/postgres/metadata.yaml
- pubsub/kafka/metadata.yaml
- state/postgresql/v1/metadata.yaml
- state/postgresql/v2/metadata.yaml
I realized in looking more at the other component types that my making the metadata fields a pointer then had unintended side effects marking some `region` fields not required when they should be. This PR corrects that and makes a deep copy instead of the pointer to avoid the unintended side effects.
Postgres is still good
```
{
"title": "AWS: Access Key ID and Secret Access Key",
"description": "Authenticate using an Access Key ID and Secret Access Key included in the metadata",
"metadata": [
{
"name": "useAWSIAM",
"description": "Must be set to `true` to enable the component to retrieve access tokens from AWS IAM.\nThis authentication method only works with AWS Relational Database Service for PostgreSQL databases.",
"required": true,
"type": "bool",
"example": "\"true\""
},
{
"name": …
```
> fix: make sure region field is required on other components

- common/authentication/postgresql/metadata.go
oopsies. We need this additional if check to support moving people from the aws prefixed fields that will be deprecated to the "region" field that will be the preferred one.
> fix(pg): add region field too

- .build-tools/go.mod
- go.mod
- tests/certification/go.mod
- tests/e2e/pubsub/jetstream/go.mod
Updates cert tests to 1.15.0-rc.18 and uses Go 1.23.6
> Update cert tests and build chain to latest

- bindings/gcp/bucket/bucket.go
- bindings/gcp/bucket/bucket_test.go
- secretstores/gcp/secretmanager/secretmanager.go
- secretstores/gcp/secretmanager/secretmanager_test.go
This PR adds support for implicit Workload Identity authentication by using GCP SDK standard ADC order of authentication lookup.
Application Default Credentials (ADS) search order:
https://cloud.google.com/docs/authentication/application-default-credentials#order
Please reference the issue this PR will close: #945 #3651 
> GCP Secret Manager and Storage Bucket Binding implicit authentication support with Workload Identity

- .build-tools/go.mod
- .build-tools/go.sum
- bindings/aws/s3/s3.go
- bindings/gcp/bucket/bucket.go
- bindings/http/http.go
- bindings/rabbitmq/rabbitmq.go
- common/authentication/aws/x509_test.go
- go.mod
- go.sum
- metadata/utils.go
- middleware/http/oauth2/oauth2_middleware.go
- middleware/http/opa/middleware.go
- pubsub/azure/eventhubs/eventhubs.go
- pubsub/azure/servicebus/topics/servicebus.go
- pubsub/mqtt3/mqtt.go
- pubsub/rabbitmq/rabbitmq.go
- pubsub/rocketmq/rocketmq.go
- state/etcd/etcd.go
- state/rethinkdb/rethinkdb_test.go
- tests/utils/configupdater/postgres/postgres.go
Certification tests will fail until we also update dapr/dapr to use kit@main.
We should merge this PR as is- failing certification tests. Then update dapr/dapr, then come back to updating the go.mod for certification tests here.
This is happening because of the removal of the `dapr/kit/utils` package, in favor of proper package naming.
> Updates dapr/kit to main

- common/component/kafka/consumer.go
- common/component/kafka/consumer_test.go
This prevents the Kafka PubSub components from intermittently dropping message during the retry cycle when it coincides with the consumers rebalancing or any other event requiring re-initialization of the consumer.
The detailed description of the error is in the issue referenced below.
This also reverts some of the changes from #3610. That PR was trying to resolve the same issue, but wasn't successful. This has been confirmed by the author (@passuied).
Please reference the issue this PR will close: #3849
* This is a bug fix and doesn't need documentation update.
> Fixed Kafka PubSub intermittently dropping messages while retrying

- bindings/kafka/metadata.yaml
- common/component/kafka/kafka.go
- common/component/kafka/kafka_test.go
- common/component/kafka/metadata.go
- pubsub/kafka/metadata.yaml
Allow specifying the Consumer Group rebalancing strategy from metadata
#3841
> Allow specifying the Consumer Group rebalancing strategy from metadata

- bindings/azure/eventhubs/metadata.yaml
`make bundle-component-metadata` fails because of this
> fix default value in azure eventhubs binding metadata.yaml

- .build-tools/component-folders.yaml
- .build-tools/pkg/metadataschema/schema.go
- component-metadata-schema.json
- conversation/deepseek/metadata.yaml
- metadata/utils.go
opening https://github.com/dapr/components-contrib/pull/3705 again
we really need this merged... otherwise the metadata schema does not contain the conversation components
> add conversation components to component metadata schema and bundle

- bindings/kafka/metadata.yaml
- common/component/kafka/consumer.go
- common/component/kafka/kafka.go
- common/component/kafka/metadata.go
- common/component/kafka/metadata_test.go
- common/component/kafka/producer.go
- common/component/kafka/producer_test.go
- pubsub/kafka/metadata.yaml
Implement ability to exclude metadata items from being added as headers when publishing, and similarly from being converted from headers to metadata when consuming messages.
Forwarding certain metadata as headers has some unwanted downstream side effects.
#3858
> Implement ability to exclude metadata items from being converted to/from headers

- common/component/kafka/subscriber.go
- common/component/kafka/subscriber_test.go
- pubsub/pubsub.go
When running Dapr with `dapr.io/block-shutdown-duration`, Kafka subscriptions are stopped before the graceful shutdown starts. This prevents Kafka from triggering a rebalance, which only occurs when the consumer group is properly closed. As a result, messages are not consumed by other members of the consumer group until the session timeout expires, leading to message processing delays during application shutdown.
This PR modifies the Kafka component's shutdown behavior to ensure proper consumer group closure during graceful shutdown:
1. **Enhanced Context Handling**: Added logic to detect when the subscription context is canceled due to shutdown (using ) `pubsub.ErrGracefulShutdown`
2. **Graceful Consumer Group Closure**: When shutdown is detected, the consumer group is explicitly closed …
> fix: Fix kafka consumer shutdown

- pubsub/jetstream/metadata.yaml
- pubsub/kubemq/metadata.yaml
- pubsub/rocketmq/metadata.go
- pubsub/rocketmq/metadata.yaml
- pubsub/rocketmq/rocketmq.go
Separating the pusbub changes from PR:
https://github.com/dapr/components-contrib/pull/3949
For each dapr release there is an endgame task to ensure that components are properly registered across contrib and dapr/dapr. I took the time to fix all the issues that I came across, cross referencing the docs. This PR adds missing metadata.yaml files.
You will also see TODO comments here and there. That is from me going through the code to manually create the metadata.yaml files and add todos i deemed necessary for the component. I also updated any interface{} to any that I came across along the way.
Yes, I did cross ref the docs too so the links should be 99.9% correct unless I made a typo or missed something accidentally.
We strive to have all PR being opened based on an issue, where the …
> feat: add pubsub proper registrations

- secretstores/alicloud/parameterstore/metadata.yaml
- secretstores/huaweicloud/csms/csms.go
- secretstores/huaweicloud/csms/metadata.yaml
- secretstores/local/file/filestore.go
- secretstores/local/file/metadata.yaml
- secretstores/tencentcloud/ssm/metadata.yaml
- secretstores/tencentcloud/ssm/ssm.go
Separating the secretstore changes from PR: 
https://github.com/dapr/components-contrib/pull/3949
For each dapr release there is an endgame task to ensure that components are properly registered across contrib and dapr/dapr. I took the time to fix all the issues that I came across, cross referencing the docs. This PR adds missing metadata.yaml files.
You will also see TODO comments here and there. That is from me going through the code to manually create the metadata.yaml files and add todos i deemed necessary for the component. I also updated any `interface{}` to `any` that I came across along the way.
Yes, I did cross ref the docs too so the links should be 99.9% correct unless I made a typo or missed something accidentally.
We strive to have all PR being opened based on an issue, where …
> feat: proper secretstore registration fixes

- middleware/http/bearer/metadata.yaml
- middleware/http/oauth2/metadata.yaml
- middleware/http/oauth2clientcredentials/metadata.yaml
- middleware/http/opa/metadata.yaml
- middleware/http/ratelimit/metadata.yaml
- middleware/http/routerchecker/metadata.yaml
- middleware/http/sentinel/metadata.yaml
- middleware/http/wasm/metadata.yaml
Separating the middleware changes from PR:
https://github.com/dapr/components-contrib/pull/3949
For each dapr release there is an endgame task to ensure that components are properly registered across contrib and dapr/dapr. I took the time to fix all the issues that I came across, cross referencing the docs. This PR adds missing metadata.yaml files.
You will also see TODO comments here and there. That is from me going through the code to manually create the metadata.yaml files and add todos i deemed necessary for the component. I also updated any interface{} to any that I came across along the way.
Yes, I did cross ref the docs too so the links should be 99.9% correct unless I made a typo or missed something accidentally.
We strive to have all PR being opened based on an issue, where the …
> feat: add middleware comp proper registrations

- common/authentication/aws/x509.go
- common/authentication/aws/x509_test.go
- common/authentication/azure/auth.go
- common/authentication/azure/spiffe.go
- common/component/azure/blobstorage/client.go
- state/azure/blobstorage/v2/metadata.yaml
- tests/e2e/pubsub/jetstream/go.sum
Signed-off-by: Jonathan Collinge <jonathancollinge@live.com>
Adds a new Azure SPIFFE OIDC authentication profile. This allows Azure users to create federated credentials for Azure AD (EntraID) Applications that directly target the SPIFFE ID of the Dapr App. This allows users to natively integrate their Dapr SPIFFE IDs into their IAM and achieve cross cloud federation without needing to host the application on the same provider and leverage the native IAM providers. For instance Dapr deployment running on AWS could access resources on Azure without needing to use secrets via a federated app credential.
This PR builds on
- https://github.com/dapr/dapr/pull/8662
- https://github.com/dapr/kit/pull/118
```
export DAPR_REGISTRY=docker.io/<your_docker_hub_account>
export DAPR_TAG=dev …
```
> Add Azure spiffe oidc auth profile

- pubsub/aws/snssqs/subscription_mgmt.go
- tests/certification/bindings/zeebe/command/create_instance_test.go
- tests/certification/flow/sidecar/sidecar.go
In certification tests, wait for sidecar to be healthy before continuing with the test.
Also added a small improvement in AWS SQS/SNS to wait for subscriptions to be unsubscribed on close before stopping the subscriber loop, otherwise the stopped sidecars were not really unsubscribing and stopping the consuming loop.
> Fix certification pubsub errors

- pubsub/aws/snssqs/subscription_mgmt.go
- tests/certification/bindings/zeebe/command/create_instance_test.go
- tests/certification/flow/sidecar/sidecar.go
Ref: https://github.com/dapr/components-contrib/pull/3988
In certification tests, wait for sidecar to be healthy before continuing with the test.
Also added a small improvement in AWS SQS/SNS to wait for subscriptions to be unsubscribed on close before stopping the subscriber loop, otherwise the stopped sidecars were not really unsubscribing and stopping the consuming loop.
> [1.16] Fix certification pubsub errors

- bindings/gcp/bucket/bucket.go
- bindings/gcp/bucket/bucket_test.go
- bindings/gcp/bucket/metadata.yaml
Allows sending `contentType` metadata to gcs
PR will close: #3997
**Note:** We expect contributors to open a corresponding documentation PR in the [dapr/docs](https://github.com/dapr/docs/) repository. As the implementer, you are the best person to document your work! Implementation PRs will not be merged until the documentation PR is opened and ready for review.
> add contentType metadata support for GCP bucket operations

- secretstores/aws/secretmanager/secretmanager.go
- secretstores/aws/secretmanager/secretmanager_test.go
Replaced the JSON marshal/unmarshal approach in `getSecretManagerMetadata` with `kitmd.DecodeMetadata` to properly handle string-to-boolean conversion for the `multipleKeyValuesPerSecret` field.
Please reference the issue this PR will close: #4045
**Note:** We expect contributors to open a corresponding documentation PR in the [dapr/docs](https://github.com/dapr/docs/) repository. As the implementer, you are the best person to document your work! Implementation PRs will not be merged until the documentation PR is opened and ready for review.
> Fix aws secrets manager yaml
